import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../shared/providers/app_settings_providers.dart';

class AppStrings {
  /// زبان‌هایی که در زمان دانلود بسته‌ی زبان (JSON) بارگذاری شده‌اند —
  /// جدا از [_localizedValues] که همراه خود اپ کامپایل می‌شود. با
  /// [registerDownloadedLanguage] پر می‌شود (هم موقع نصب دستی، هم موقع
  /// بازیابیِ بسته‌های قبلاً دانلودشده در شروع اپ).
  static final Map<String, Map<String, String>> _downloadedValues = {};

  /// یک بسته‌ی زبانِ دانلودشده را در حافظه ثبت می‌کند تا [get] بتواند از آن
  /// استفاده کند. کلیدهایی که در بسته نباشند همچنان از فارسی/انگلیسیِ
  /// درون‌اپ گرفته می‌شوند (بسته‌ی ناقص هم اپ را خراب نمی‌کند).
  static void registerDownloadedLanguage(String code, Map<String, String> values) {
    _downloadedValues[code] = values;
  }

  static void unregisterDownloadedLanguage(String code) {
    _downloadedValues.remove(code);
  }

  /// همه‌ی کلیدهای پایه (بر اساس فارسی) — مرجع تولید بسته‌ی زبانِ جدید.
  static Iterable<String> get baseKeys => _localizedValues['fa']!.keys;

  static const Map<String, Map<String, String>> _localizedValues = {
    'fa': {
      // ناوبری پایین صفحه
      'settings': 'تنظیمات',
      'home': 'خانه',
      'routes': 'مسیرها',
      'search': 'جستجو',
      'voice': 'صدا',
      'favorites': 'علاقه‌مندی‌ها',

      // صفحه تنظیمات
      'general_settings': 'تنظیمات عمومی',
      'vehicle_routing_section': 'خودرو و مسیریابی',
      'support_section': 'پشتیبانی',
      'voice_settings': 'تنظیمات صدا',
      'voice_settings_desc': 'تنظیمات راهنما و اعلان‌ها',
      'map_layers': 'نقشه و لایه‌ها',
      'map_layers_desc': 'تنظیمات نمایش و تم نقشه',
      'map_settings': 'تنظیمات نقشه',
      'map_settings_desc': 'حالت آنلاین/آفلاین و نمایش دسته‌های POI روی نقشه',
      'download_map_title': 'دانلود نقشه',
      'download_map_subtitle': 'برای مسیریابی بدون اینترنت، نقشه‌های مورد نظر خود را دانلود کنید.',
      'map_mode_online': 'آنلاین',
      'map_mode_online_desc': 'نیازمند اینترنت',
      'map_mode_offline': 'آفلاین (نصب)',
      'map_mode_offline_desc': 'از نقشه‌های دانلودشده',
      'all_countries': 'همه کشورها',
      'search_country_hint': 'جستجوی کشور...',
      'all_countries_count': 'همه کشورها ({count})',
      'map_downloaded': 'دانلود شده',
      'map_not_downloaded': 'دانلود نشده',
      'map_downloading': 'در حال دانلود',
      'map_download_action': 'دانلود',
      'map_delete_action': 'حذف',
      'map_pause_action': 'توقف',
      'map_update_action': 'به‌روزرسانی',
      'device_storage_title': 'فضای ذخیره‌سازی دستگاه',
      'device_storage_free': '{value} آزاد',
      'device_storage_used': 'استفاده‌شده: {used} از {total}',
      'vehicle_model': 'مدل خودرو',
      'vehicle_model_desc': 'انتخاب نشانگر خودرو روی نقشه',
      'saved_places': 'مکان‌های ذخیره شده',
      'saved_places_desc': 'مدیریت نشان‌ها و آدرس‌های منتخب',
      'about_app': 'درباره برنامه',
      'about_app_desc': 'نسخه برنامه و اطلاعات توسعه‌دهنده',
      'logout': 'خروج از حساب کاربری',

      // پیکر خودرو
      'choose_vehicle_title': 'انتخاب خودرو',
      'peykan_default': 'پیکان (پیش‌فرض)',
      'peykan_desc': 'نمای دوبعدی، همیشه در دسترس',
      'bmw_i8': 'BMW i8 (مدل سه‌بعدی)',
      'bmw_i8_desc': 'رندر کامل سه‌بعدی متصل به GPS',

      // پیکر استایل نقشه
      'map_style_title': 'استایل نقشه',
      'day_mode': 'روز',
      'day_mode_desc': 'رنگ‌های روشن',
      'night_mode': 'شب',
      'night_mode_desc': 'رنگ‌های تیره',
      'theme_type': 'نوع تم',

      // صفحه تنظیمات صدا
      'voice_guidance': 'راهنمای صوتی',
      'voice_engine_type': 'نوع موتور صوتی',
      'recorded_files_title': 'فایل‌های ضبط شده',
      'recorded_files_subtitle': 'صدای طبیعی و آفلاین (بدون اعلام نام خیابان)',
      'smart_tts_title': 'صدای هوش مصنوعی',
      'smart_tts_subtitle': 'صدای روان و دقیق نورال؛ اعلام نام خیابان‌ها (با کش آفلاین)',
      'tts_model_missing': 'مدل‌های صوتی یافت نشد. برای استفاده از TTS باید مدل‌ها را نصب کنید.',
      'installing': 'در حال نصب...',
      'percent_sign': '٪',
      'auto_install_models': 'نصب خودکار مدل‌ها',
      'tts_download_failed': 'آماده‌سازی صدای هوش مصنوعی ناموفق بود. اتصال اینترنت را بررسی کنید.',
      'select_speaker': 'انتخاب گوینده',
      'female_voice': 'صدای زن',
      'male_voice': 'صدای مرد',
      'volume_label': 'بلندی صدا',
      'playback_speed': 'سرعت پخش',
      'play_sample': 'پخش نمونه',
      'advanced_settings': 'تنظیمات پیشرفته',
      'announce_street_names': 'اعلام نام خیابان‌ها',
      'tts_only_note': 'فقط در حالت TTS فعال می‌شود',
      'announce_street_names_desc': 'اعلام دقیق نام معابر و خیابان‌ها',
      'camera_radar_alert': 'هشدار صوتی دوربین و رادار',
      'alert_sound': 'صدای هشدار',
      'alert_sound_default': 'پیش‌فرض',
      'duck_music': 'کاهش صدا هنگام پخش موزیک',
      'duck_music_desc': 'صدای راهنما روی موزیک/پادکست دیگر پایین میاد',
      'speed_medium': 'متوسط',
      'speed_slow': 'کند',
      'speed_fast': 'سریع',
      'voice_engine_download_title': 'آماده‌سازی صدا برای استفادهٔ آفلاین',
      'voice_engine_fa_name': 'موتور صوتی فارسی',
      'voice_engine_fa_desc': 'صدای طبیعی فارسی',
      'installed_label': 'نصب شده',
      'not_installed_label': 'نصب نشده',
      'retry_install': 'تلاش مجدد',
      'install_now': 'نصب کن',
      'engine_version_prefix': 'نسخه',
      'language_program': 'زبان برنامه',
      'language_program_desc': 'فارسی، English و بسته‌های زبان',
      'map_display': 'نمایش نقشه',
      'map_source': 'منبع نقشه',
      'online_map': 'آنلاین',
      'offline_map': 'آفلاین',
      'map_three_d': 'نمای سه‌بعدی',
      'map_three_d_desc': 'در زوم نزدیک و هنگام مسیریابی',
      'map_angle': 'زاویهٔ نمایش',
      'map_color_mode': 'حالت رنگ نقشه',
      'dynamic_color': 'رنگ پویا',
      'poi_map_title': 'نقاط نمایشی روی نقشه (POI)',
      'show_all_categories': 'نمایش همهٔ دسته‌ها',
      'poi_selection_desc': 'فقط دسته‌های انتخاب‌شده روی نقشه نشان داده می‌شوند',
      'poi_visible': 'روی نقشه نمایش داده می‌شود',
      'poi_hidden': 'پنهان است',
      'offline_maps_download': 'دانلود نقشه‌های آفلاین',
      'close_zoom_map_ready': 'نقشهٔ آماده با زوم خیابانی ۱۶',
      'manage_download': 'مدیریت دانلود',
      'download_select_other_region': 'کشور یا منطقهٔ دیگر را از فهرست دانلود انتخاب کنید.',
      'map_list_unavailable': 'فهرست نقشه‌ها در دسترس نیست.',
      'voice_guidance_title': 'صدای راهنما',
      'voice_not_selected': 'هنوز بستهٔ صوتی انتخاب نشده است',
      'voice_downloaded_label': 'بستهٔ صوتی دانلود شده',
      'voice_select_from_downloads': 'برای انتخاب، یک بسته را از پایین دانلود کنید.',
      'voice_download_packs': 'دانلود بسته‌های صوتی',
      'voice_list_unavailable': 'فهرست بسته‌های صوتی در دسترس نیست.',
      'voice_offline_pack': 'بستهٔ صوتی آفلاین',
      'download_label': 'دانلود',
      'select_label': 'انتخاب',
      'active_label': 'فعال',
      'delete_label': 'حذف',
      'poi_fuel': 'جایگاه سوخت',
      'poi_parking': 'پارکینگ',
      'poi_speed_camera': 'دوربین سرعت',
      'poi_speed_bump': 'سرعت‌گیر',
      'poi_traffic_light': 'چراغ راهنمایی',
      'poi_health': 'امکانات درمانی',
      'poi_public': 'امکانات عمومی',

      // صفحه مکان‌های ذخیره‌شده
      'saved_places_title': 'مکان‌های مورد علاقه',
      'no_places_yet': 'هنوز مکانی ذخیره نکرده‌اید',
      'db_error': 'خطا در خواندن دیتابیس',
      'category_home': 'خانه',
      'category_work': 'محل کار',
      'category_other': 'سایر',
      'category_recent': 'اخیر',
      'place_count_suffix': 'مکان',
      'delete_this_category': 'حذف همه‌ی این دسته',
      'delete_this_place': 'حذف این مکان',
      'delete_short': 'حذف',
      'navigate_label': 'مسیریابی',
      'edit_label': 'ویرایش',
      'share_label': 'اشتراک‌گذاری',
      'add_new_place': '+ افزودن مکان جدید',
      'delete_category_dialog_title': 'حذف این دسته',
      'delete_category_confirm_prefix': 'همه‌ی',
      'delete_category_confirm_suffix': 'مکان این دسته حذف شود؟',
      'cancel': 'انصراف',
      'delete_all': 'حذف همه',
      'add_current_location_title': 'افزودن موقعیت فعلی',
      'place_name_hint': 'مثلاً خانه، محل کار...',
      'save_current_location': 'ذخیره موقعیت فعلی من',
      'edit_place_title': 'ویرایش مکان',
      'place_name_hint2': 'نام مکان',
      'address_optional_hint': 'آدرس (اختیاری)',
      'save_label': 'ذخیره',
      'point_saved_snackbar': 'به علاقه‌مندی‌ها اضافه شد',

      // صفحه مسیرها
      'routes_title': 'مسیریابی',
      'search_destination_placeholder': 'جستجوی مقصد...',
      'trip_history': 'تاریخچه سفرها',
      'no_trips_yet': 'هنوز سفری ثبت نشده است',
      'unknown_destination': 'مقصد نامشخص',
      'error_prefix': 'خطا',
      'suggested_routes': 'مسیرهای پیشنهادی',
      'fastest_route': 'سریع‌ترین مسیر',
      'challenging_route': 'مسیر چالش‌برانگیز',
      'economic_route': 'مسیر اقتصادی',
      'light_traffic': 'ترافیک سبک',
      'medium_traffic': 'ترافیک متوسط',
      'heavy_traffic': 'ترافیک سنگین',
      'start_routing': 'شروع مسیریابی',

      // صفحه جستجو
      'search_destination_address_placeholder': 'جستجوی مقصد یا آدرس...',
      'popular_categories': 'دسته‌بندی‌های محبوب',
      'recently_searched': 'اخیراً جستجو شده',
      'more_label': 'بیشتر',
      'gas_station': 'پمپ بنزین',
      'restaurant_label': 'رستوران',
      'park_label': 'پارک',
      'hotel_label': 'هتل',
      'shopping_label': 'خرید',
      'cafe_label': 'کافه',

      // صفحه پروفایل
      'account_title': 'حساب کاربری',
      'loading_error_prefix': 'خطا در بارگذاری',
      'abtin_user': 'کاربر آبتین',
      'abtin_navigator_user': 'کاربر آبتین نویگیتور',
      'field_name': 'نام',
      'default_username': 'نام کاربر',
      'field_lastname': 'نام خانوادگی',
      'field_email': 'ایمیل',
      'field_birthdate': 'تاریخ تولد',
      'field_phone': 'شماره همراه',
      'edit_info': 'ویرایش اطلاعات',
      'logout_account': 'خروج از حساب',
      'account_subtitle': 'اطلاعات حساب کاربری خود را مشاهده و ویرایش کنید',
      'not_set': 'ثبت نشده',
      'choose_photo_source': 'انتخاب عکس پروفایل',
      'take_photo': 'گرفتن عکس با دوربین',
      'choose_from_gallery': 'انتخاب از گالری',
      'save_changes': 'ذخیره تغییرات',
      'confirm_logout_title': 'خروج از حساب',
      'confirm_logout_message': 'آیا مطمئن هستید که می‌خواهید از حساب کاربری خود خارج شوید؟',
      'confirm': 'تأیید',

      // صفحه حریم خصوصی و درباره
      'privacy_policy_title': 'حریم خصوصی',
      'privacy_policy_body':
          'اپلیکیشن آبتین مپس متعهد به حفظ حریم خصوصی شماست. داده‌های مکانی شما فقط برای مسیریابی استفاده شده و به صورت محلی در دستگاه شما ذخیره می‌گردد. ما هیچ اطلاعات شخصی را بدون اجازه شما با اشخاص ثالث به اشتراک نمی‌گذاریم.',
      'about_abtin_maps_title': 'درباره آبتین مپس',
      'app_name': 'آبتین مپس',
      'version_label': 'نسخه ۱.۰.۰',
      'app_tagline': 'پیشرفته‌ترین سامانه مسیریابی و نقشه کاملاً بومی با قابلیت‌های آفلاین و آنلاین دقیق.',

      'coming_soon': 'به‌زودی',

      // صفحه دانلود نقشه
      'download_map_desc': 'برای مسیریابی بدون اینترنت، نقشه‌های مورد نظر خود را دانلود کنید.',
      'all_provinces': 'همه استان‌ها',
      'downloaded_ones': 'دانلودشده‌ها',
      'not_downloaded_ones': 'دانلودنشده‌ها',
      'map_label': 'نقشه',
      'graph_routing_label': 'گراف (مسیریابی)',
      'storage_space': 'فضای ذخیره‌سازی',
      'manage_map_storage': 'مدیریت فضای ذخیره‌سازی نقشه',
      'total_progress': 'کل پیشرفت',
      'download_speed': 'سرعت دانلود',
      'time_remaining': 'زمان باقی‌مانده',
      'map_download_success': 'نقشه «{name}» با موفقیت دانلود شد ✅',
      'map_download_error': 'خطا در دانلود نقشه «{name}»: {error}',
      'map_delete_success': 'نقشه «{name}» حذف شد',
      'graph_download_success': 'گراف مسیریابی «{name}» با موفقیت دانلود شد ✅',
      'graph_download_error': 'خطا در دانلود گراف مسیریابی «{name}»: {error}',
      'graph_delete_success': 'گراف مسیریابی «{name}» حذف شد',
      'map_graph_size_summary': '{mapSize} :نقشه  |  {graphSize} :(مسیریابی) گراف',
      'used_space_label': 'استفاده شده: {size}',
      'available_space_label': 'موجود: {size}',
      'remaining_minutes_suffix': 'دقیقه',

      // صفحه تنظیمات ظاهری (Appearance Settings)
      'appearance_settings': 'تنظیمات ظاهری',
      'appearance_desc': 'ظاهر نقشه و برنامه را مطابق سلیقه خود شخصی‌سازی کنید.',
      'map_display_mode': 'حالت نمایش نقشه',
      'map_display_mode_desc': 'حالت سه‌بعدی یا دوبعدی نقشه را انتخاب کنید.',
      'three_d': 'سه‌بعدی',
      'two_d': 'دوبعدی',
      'route_color': 'رنگ مسیر',
      'route_color_desc': 'رنگ مسیر مسیریابی روی نقشه را انتخاب کنید.',
      'app_main_color': 'رنگ اصلی برنامه',
      'app_main_color_desc': 'رنگ اصلی رابط کاربری برنامه را انتخاب کنید.',
      'custom_color': 'سفارشی',
      'display_mode': 'حالت نمایش',
      'display_mode_desc': 'حالت روشن یا تیره برنامه را انتخاب کنید.',
      'dark': 'تیره',
      'light': 'روشن',
      'system': 'سیستم',
      'element_density': 'تراکم نمایش عناصر',
      'element_density_desc': 'تراکم نمایش دکمه‌ها و عناصر روی نقشه و صفحات.',
      'low': 'کم',
      'medium': 'متوسط',
      'high': 'زیاد',
      'standard': 'استاندارد',
      'simple': 'ساده',
      'satellite': 'ماهواره‌ای',
      'hybrid': 'ترکیبی',
      'minimal': 'مینیمال',
      'appearance_subtitle': 'ظاهر نقشه و برنامه را مطابق سلیقه خود شخصی‌سازی کنید.',
      'map_display_3d': 'سه‌بعدی',
      'map_display_2d': 'دوبعدی',
      'selected_destination': 'مقصد انتخاب شده',
      'point_on_map': 'نقطه روی نقشه',
      'added_to_favorites': 'به علاقه‌مندی‌ها اضافه شد',

      // صفحه تنظیمات ظاهری (بازطراحی‌شده — دو ستونه با پیش‌نمایش زنده)
      'as_page_title': 'تنظیمات ظاهری',
      'as_page_subtitle':
          'ظاهر نقشه، مسیریابی، خودرو و المان‌ها را مطابق سلیقه خود شخصی‌سازی کنید',
      'as_save': 'ذخیره',
      'as_tab_map': 'نقشه',
      'as_tab_routing': 'مسیر',
      'as_tab_marker': 'خودرو و پیکان',
      'as_tab_color': 'رنگ‌بندی',
      'as_preset_title': 'پرست آماده',
      'as_preset_minimal': 'مینیمال',
      'as_preset_neon': 'نئون',
      'as_preset_classic': 'کلاسیک',
      'as_preset_custom': 'سفارشی',
      'as_preset_custom_hint': 'تنظیمات فعلی شما با هیچ پرستِ آماده‌ای دقیقاً یکسان نیست.',
      'as_live_preview': 'پیش‌نمایش زنده',
      'as_weather_city_demo': 'تهران',
      'as_weather_condition_sunny': 'آفتابی',
      'as_weather_temp_demo': '۲۸°C',
      'as_weather_title': 'ویجت آب‌وهوا روی نقشه',
      'as_weather_enable': 'نمایش آب‌وهوا روی نقشه',
      'as_weather_position': 'موقعیت',
      'as_weather_pos_top_left': 'بالا چپ',
      'as_weather_pos_top_right': 'بالا راست',
      'as_weather_pos_bottom_left': 'پایین چپ',
      'as_weather_pos_bottom_right': 'پایین راست',
      'as_weather_size': 'اندازه',
      'as_weather_bg_color': 'رنگ پس‌زمینه',
      'as_weather_bg_opacity': 'شفافیت پس‌زمینه',
      'as_day_night_route_title': 'تنظیم رنگ روز و شب',
      'as_day_night_title': 'حالت روز و شب نقشه',
      'as_marker_title': 'نشانگر جهت‌یابی',
      'as_day': 'روز',
      'as_night': 'شب',
      'as_tab_car': 'خودرو',
      'as_tab_pin': 'پیکان',
      'as_car_preview_label': 'خودرو (پیش‌نمایش)',
      'as_choose_vehicle_pin_label': 'انتخاب نمایش خودرو / پیکان',
      'as_body_color': 'رنگ بدنه',
      'as_pin_preview_label': 'پیکان (پیش‌نمایش)',
      'as_pin_color': 'رنگ پیکان',
      'as_pin_shadow': 'سایه پیکان',
      'as_pin_size': 'اندازه پیکان',
      'as_map_elements_title': 'المان‌های نقشه',
      'as_motorway': 'بزرگراه',
      'as_trunk': 'آزادراه',
      'as_main_road': 'خیابان اصلی',
      'as_sub_road': 'خیابان فرعی',
      'as_alley': 'کوچه',
      'as_ground': 'زمین',
      'as_road_arrows': 'فلش جهت خیابان',
      'as_road_arrow_color': 'رنگ فلش',
      'as_building': 'ساختمان',
      'as_green_space': 'فضای سبز',
      'as_water': 'آب',
      'as_show_label': 'نمایش',
      'as_road_width': 'عرض',
      'as_road_color': 'رنگ',
      'as_road_reset_default': 'بازنشانی به پیش‌فرض',
      'as_routing_title': 'مسیریابی',
      'as_route_color_default': 'رنگ مسیر (پیش‌فرض)',
      'as_route_width': 'عرض مسیر',
      'as_route_glow_effect': 'افکت گلو (دور مسیر)',
      'as_glow_intensity': 'شدت گلو',
      'as_route_line_type': 'نوع خط مسیر',
      'as_line_continuous': 'پیوسته',
      'as_line_dotted': 'نقطه‌ای',
      'as_line_dashed': 'بریده',
      'as_line_dot_dash': 'نقطه-بریده',
      'as_alt_lines_color': 'رنگ خطوط جایگزین',
      'as_heavy_traffic_color': 'رنگ ترافیک سنگین',
      'as_medium_traffic_color': 'رنگ ترافیک متوسط',
      'as_light_traffic_color': 'رنگ ترافیک روان',
      'as_map_view_mode_title': 'حالت نمایش نقشه',
      'as_view_2d': '۲ بعدی',
      'as_view_3d': '۳ بعدی',
      'as_3d_tilt_angle': 'زاویه دید ۳بعدی',
      'as_theme_mode_title': 'حالت تیره و روشن اپ',
      'as_theme_light': 'روشن',
      'as_theme_dark': 'تیره',
      'as_theme_system': 'طبق سیستم',
      'as_app_color_title': 'رنگ اپ',
      'as_app_color_subtitle': 'رنگ اصلی دکمه‌ها و برجسته‌های رابط کاربری',
      'as_reset_changes': 'بازنشانی تغییرات',
      'as_save_style': 'ذخیره استایل',
      'as_reset_snackbar': 'تغییرات به حالت اولیه برگشت',
      'as_save_snackbar': 'تغییرات ذخیره شد',
      'downloads_title': 'دانلودها',
      'downloads_maps_tab': 'نقشه',
      'downloads_voice_tab': 'ویس',
      'downloads_language_tab': 'زبان',
      'downloads_maps_error': 'خطا در بارگیری فهرست نقشه‌ها: {error}',
      'downloads_voice_error': 'خطا در بارگیری فهرست بسته‌های صوتی: {error}',
      'downloads_language_error': 'خطا در بارگیری فهرست زبان‌ها: {error}',
      'downloads_retry': 'تلاش مجدد',
      'downloads_empty_downloaded': 'چیزی دانلود نشده',
      'downloads_empty_available': 'چیزی برای دانلود نیست',

    },
    'en': {
      // ناوبری پایین صفحه
      'settings': 'Settings',
      'home': 'Home',
      'routes': 'Routes',
      'search': 'Search',
      'voice': 'Voice',
      'favorites': 'Favorites',

      // صفحه تنظیمات
      'general_settings': 'General Settings',
      'vehicle_routing_section': 'Vehicle & Routing',
      'support_section': 'Support',
      'voice_settings': 'Voice Settings',
      'voice_settings_desc': 'Guidance and notification settings',
      'map_layers': 'Map & Layers',
      'map_layers_desc': 'Map display and theme settings',
      'map_settings': 'Map Settings',
      'map_settings_desc': 'Online/offline mode and POI category visibility on the map',
      'download_map_title': 'Download Map',
      'download_map_subtitle': 'Download the maps you need for offline navigation.',
      'map_mode_online': 'Online',
      'map_mode_online_desc': 'Requires internet',
      'map_mode_offline': 'Offline (installed)',
      'map_mode_offline_desc': 'From downloaded maps',
      'all_countries': 'All Countries',
      'search_country_hint': 'Search country...',
      'all_countries_count': 'All Countries ({count})',
      'map_downloaded': 'Downloaded',
      'map_not_downloaded': 'Not downloaded',
      'map_downloading': 'Downloading',
      'map_download_action': 'Download',
      'map_delete_action': 'Delete',
      'map_pause_action': 'Pause',
      'map_update_action': 'Update',
      'device_storage_title': 'Device Storage',
      'device_storage_free': '{value} free',
      'device_storage_used': 'Used: {used} of {total}',
      'vehicle_model': 'Vehicle Model',
      'vehicle_model_desc': 'Choose the vehicle marker on the map',
      'saved_places': 'Saved Places',
      'saved_places_desc': 'Manage saved pins and addresses',
      'about_app': 'About the App',
      'about_app_desc': 'App version and developer info',
      'logout': 'Log Out',

      // پیکر خودرو
      'choose_vehicle_title': 'Select Vehicle',
      'peykan_default': 'Peykan (Default)',
      'peykan_desc': '2D view, always available',
      'bmw_i8': 'BMW i8 (3D Model)',
      'bmw_i8_desc': 'Full 3D render linked to GPS',

      // پیکر استایل نقشه
      'map_style_title': 'Map Style',
      'day_mode': 'Day',
      'day_mode_desc': 'Bright colors',
      'night_mode': 'Night',
      'night_mode_desc': 'Dark colors',
      'theme_type': 'Theme Type',

      // صفحه تنظیمات صدا
      'voice_guidance': 'Voice Guidance',
      'voice_engine_type': 'Voice Engine Type',
      'recorded_files_title': 'Recorded Files',
      'recorded_files_subtitle': 'Natural, offline voice (no street names)',
      'smart_tts_title': 'AI Voice',
      'smart_tts_subtitle': 'Fluent neural voice with street names (cached offline)',
      'tts_model_missing': 'Voice models not found. You need to install them to use TTS.',
      'installing': 'Installing...',
      'percent_sign': '%',
      'auto_install_models': 'Auto-install Models',
      'tts_download_failed': 'Preparing the AI voice failed. Check your internet connection.',
      'select_speaker': 'Select Speaker',
      'female_voice': 'Female Voice',
      'male_voice': 'Male Voice',
      'volume_label': 'Volume',
      'playback_speed': 'Playback Speed',
      'play_sample': 'Play Sample',
      'advanced_settings': 'Advanced Settings',
      'announce_street_names': 'Announce Street Names',
      'tts_only_note': 'Only available in TTS mode',
      'announce_street_names_desc': 'Precisely announce street and road names',
      'camera_radar_alert': 'Camera & Radar Voice Alerts',
      'alert_sound': 'Alert Sound',
      'alert_sound_default': 'Default',
      'duck_music': 'Lower Volume During Music',
      'duck_music_desc': 'Guidance voice lowers over music/podcast',
      'speed_medium': 'Medium',
      'speed_slow': 'Slow',
      'speed_fast': 'Fast',
      'voice_engine_download_title': 'Prepare voice for offline use',
      'voice_engine_fa_name': 'Persian Voice Engine',
      'voice_engine_fa_desc': 'Natural Persian voice',
      'installed_label': 'Installed',
      'not_installed_label': 'Not Installed',
      'retry_install': 'Retry',
      'install_now': 'Install',
      'engine_version_prefix': 'Version',
      'language_program': 'App Language',
      'language_program_desc': 'Persian, English, and language packs',
      'map_display': 'Map Display',
      'map_source': 'Map Source',
      'online_map': 'Online',
      'offline_map': 'Offline',
      'map_three_d': '3D View',
      'map_three_d_desc': 'At close zoom and during navigation',
      'map_angle': 'View angle',
      'map_color_mode': 'Map Color Mode',
      'dynamic_color': 'Dynamic Color',
      'poi_map_title': 'Map Points of Interest (POI)',
      'show_all_categories': 'Show All Categories',
      'poi_selection_desc': 'Only selected categories are shown on the map',
      'poi_visible': 'Shown on the map',
      'poi_hidden': 'Hidden',
      'offline_maps_download': 'Offline Map Downloads',
      'close_zoom_map_ready': 'Ready map with street-level zoom 16',
      'manage_download': 'Manage Downloads',
      'download_select_other_region': 'Choose another country or region from the download list.',
      'map_list_unavailable': 'Map list is unavailable.',
      'voice_guidance_title': 'Guidance Voice',
      'voice_not_selected': 'No voice pack is selected yet',
      'voice_downloaded_label': 'Voice pack downloaded',
      'voice_select_from_downloads': 'Download a pack below to select it.',
      'voice_download_packs': 'Download Voice Packs',
      'voice_list_unavailable': 'Voice pack list is unavailable.',
      'voice_offline_pack': 'Offline voice pack',
      'download_label': 'Download',
      'select_label': 'Select',
      'active_label': 'Active',
      'delete_label': 'Delete',
      'poi_fuel': 'Fuel Stations',
      'poi_parking': 'Parking',
      'poi_speed_camera': 'Speed Cameras',
      'poi_speed_bump': 'Speed Bumps',
      'poi_traffic_light': 'Traffic Lights',
      'poi_health': 'Health Services',
      'poi_public': 'Public Places',

      // صفحه مکان‌های ذخیره‌شده
      'saved_places_title': 'Favorite Places',
      'no_places_yet': "You haven't saved any places yet",
      'db_error': 'Error reading database',
      'category_home': 'Home',
      'category_work': 'Work',
      'category_other': 'Other',
      'category_recent': 'Recent',
      'place_count_suffix': 'places',
      'delete_this_category': 'Delete all in this category',
      'delete_this_place': 'Delete this place',
      'delete_short': 'Delete',
      'navigate_label': 'Navigate',
      'edit_label': 'Edit',
      'share_label': 'Share',
      'add_new_place': '+ Add New Place',
      'delete_category_dialog_title': 'Delete this category',
      'delete_category_confirm_prefix': 'Delete all',
      'delete_category_confirm_suffix': 'places in this category?',
      'cancel': 'Cancel',
      'delete_all': 'Delete All',
      'add_current_location_title': 'Add Current Location',
      'place_name_hint': 'e.g. Home, Work...',
      'save_current_location': 'Save My Current Location',
      'edit_place_title': 'Edit Place',
      'place_name_hint2': 'Place name',
      'point_saved_snackbar': 'Added to favorites',
      'address_optional_hint': 'Address (optional)',
      'save_label': 'Save',

      // صفحه مسیرها
      'routes_title': 'Routes',
      'search_destination_placeholder': 'Search destination...',
      'trip_history': 'Trip History',
      'no_trips_yet': 'No trips recorded yet',
      'unknown_destination': 'Unknown destination',
      'error_prefix': 'Error',
      'suggested_routes': 'Suggested Routes',
      'fastest_route': 'Fastest Route',
      'challenging_route': 'Challenging Route',
      'economic_route': 'Economic Route',
      'light_traffic': 'Light Traffic',
      'medium_traffic': 'Medium Traffic',
      'heavy_traffic': 'Heavy Traffic',
      'start_routing': 'Start Navigation',

      // صفحه جستجو
      'search_destination_address_placeholder': 'Search destination or address...',
      'popular_categories': 'Popular Categories',
      'recently_searched': 'Recently Searched',
      'more_label': 'More',
      'gas_station': 'Gas Station',
      'restaurant_label': 'Restaurant',
      'park_label': 'Park',
      'hotel_label': 'Hotel',
      'shopping_label': 'Shopping',
      'cafe_label': 'Cafe',

      // صفحه پروفایل
      'account_title': 'Account',
      'loading_error_prefix': 'Error loading',
      'abtin_user': 'Abtin User',
      'abtin_navigator_user': 'Abtin Navigator User',
      'field_name': 'Name',
      'default_username': 'Username',
      'field_lastname': 'Last Name',
      'field_email': 'Email',
      'field_birthdate': 'Birth Date',
      'field_phone': 'Phone Number',
      'edit_info': 'Edit Info',
      'logout_account': 'Log Out',
      'account_subtitle': 'View and edit your account information',
      'not_set': 'Not set',
      'choose_photo_source': 'Choose Profile Photo',
      'take_photo': 'Take a Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'save_changes': 'Save Changes',
      'confirm_logout_title': 'Log Out',
      'confirm_logout_message': 'Are you sure you want to log out of your account?',
      'confirm': 'Confirm',

      // صفحه حریم خصوصی و درباره
      'privacy_policy_title': 'Privacy Policy',
      'privacy_policy_body':
          'Abtin Maps is committed to protecting your privacy. Your location data is used only for navigation and is stored locally on your device. We never share your personal information with third parties without your consent.',
      'about_abtin_maps_title': 'About Abtin Maps',
      'app_name': 'Abtin Maps',
      'version_label': 'Version 1.0.0',
      'app_tagline': 'The most advanced, fully local navigation and mapping system, with precise offline and online capabilities.',

      'coming_soon': 'Coming soon',

      // صفحه دانلود نقشه
      'download_map_desc': 'Download the maps you need for offline navigation.',
      'all_provinces': 'All Provinces',
      'downloaded_ones': 'Downloaded',
      'not_downloaded_ones': 'Not Downloaded',
      'map_label': 'Map',
      'graph_routing_label': 'Graph (Routing)',
      'storage_space': 'Storage Space',
      'manage_map_storage': 'Manage Map Storage',
      'total_progress': 'Total Progress',
      'download_speed': 'Download Speed',
      'time_remaining': 'Time Remaining',
      'map_download_success': 'Map "{name}" downloaded successfully ✅',
      'map_download_error': 'Failed to download map "{name}": {error}',
      'map_delete_success': 'Map "{name}" deleted',
      'graph_download_success': 'Routing graph "{name}" downloaded successfully ✅',
      'graph_download_error': 'Failed to download routing graph "{name}": {error}',
      'graph_delete_success': 'Routing graph "{name}" deleted',
      'map_graph_size_summary': 'Map: {mapSize}  |  Graph (Routing): {graphSize}',
      'used_space_label': 'Used: {size}',
      'available_space_label': 'Available: {size}',
      'remaining_minutes_suffix': 'min',

      // Appearance Settings
      'appearance_settings': 'Appearance Settings',
      'appearance_desc': 'Customize the appearance of the map and app to your liking.',
      'map_display_mode': 'Map Display Mode',
      'map_display_mode_desc': 'Choose between 3D or 2D map mode.',
      'three_d': '3D',
      'two_d': '2D',
      'route_color': 'Route Color',
      'route_color_desc': 'Choose the navigation route color on the map.',
      'app_main_color': 'App Main Color',
      'app_main_color_desc': 'Choose the main UI color of the app.',
      'custom_color': 'Custom',
      'display_mode': 'Display Mode',
      'display_mode_desc': 'Choose light or dark mode for the app.',
      'dark': 'Dark',
      'light': 'Light',
      'system': 'System',
      'element_density': 'Element Density',
      'element_density_desc': 'Density of buttons and elements on the map and pages.',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'standard': 'Standard',
      'simple': 'Simple',
      'satellite': 'Satellite',
      'hybrid': 'Hybrid',
      'minimal': 'Minimal',
      'appearance_subtitle': 'Customize the appearance of the map and app to your liking.',
      'map_display_3d': '3D',
      'map_display_2d': '2D',
      'selected_destination': 'Selected Destination',
      'point_on_map': 'Point on map',
      'added_to_favorites': 'Added to favorites',

      // Appearance Settings (redesigned two-column screen)
      'as_page_title': 'Appearance Settings',
      'as_page_subtitle':
          'Customize the look of the map, routing, vehicle and elements to your taste',
      'as_save': 'Save',
      'as_tab_map': 'Map',
      'as_tab_routing': 'Routing',
      'as_tab_marker': 'Vehicle & Pin',
      'as_tab_color': 'Colors',
      'as_preset_title': 'Preset',
      'as_preset_minimal': 'Minimal',
      'as_preset_neon': 'Neon',
      'as_preset_classic': 'Classic',
      'as_preset_custom': 'Custom',
      'as_preset_custom_hint': "Your current settings don't exactly match any preset.",
      'as_live_preview': 'Live Preview',
      'as_weather_city_demo': 'Tehran',
      'as_weather_condition_sunny': 'Sunny',
      'as_weather_temp_demo': '28°C',
      'as_weather_title': 'Weather widget on map',
      'as_weather_enable': 'Show weather on map',
      'as_weather_position': 'Position',
      'as_weather_pos_top_left': 'Top left',
      'as_weather_pos_top_right': 'Top right',
      'as_weather_pos_bottom_left': 'Bottom left',
      'as_weather_pos_bottom_right': 'Bottom right',
      'as_weather_size': 'Size',
      'as_weather_bg_color': 'Background color',
      'as_weather_bg_opacity': 'Background opacity',
      'as_day_night_route_title': 'Day & Night Colors',
      'as_day_night_title': 'Map Day/Night Mode',
      'as_marker_title': 'Direction Marker',
      'as_day': 'Day',
      'as_night': 'Night',
      'as_tab_car': 'Car',
      'as_tab_pin': 'Arrow',
      'as_car_preview_label': 'Car (Preview)',
      'as_choose_vehicle_pin_label': 'Choose Car / Arrow Display',
      'as_body_color': 'Body Color',
      'as_pin_preview_label': 'Arrow (Preview)',
      'as_pin_color': 'Arrow Color',
      'as_pin_shadow': 'Arrow Shadow',
      'as_pin_size': 'Arrow Size',
      'as_map_elements_title': 'Map Elements',
      'as_motorway': 'Highway',
      'as_trunk': 'Freeway',
      'as_main_road': 'Main Street',
      'as_sub_road': 'Side Street',
      'as_alley': 'Alley',
      'as_ground': 'Ground',
      'as_road_arrows': 'Road direction arrows',
      'as_road_arrow_color': 'Arrow color',
      'as_building': 'Buildings',
      'as_green_space': 'Green Space',
      'as_water': 'Water',
      'as_show_label': 'Show',
      'as_road_width': 'Width',
      'as_road_color': 'Color',
      'as_road_reset_default': 'Reset to default',
      'as_routing_title': 'Routing',
      'as_route_color_default': 'Route Color (Default)',
      'as_route_width': 'Route Width',
      'as_route_glow_effect': 'Glow Effect (Route Outline)',
      'as_glow_intensity': 'Glow Intensity',
      'as_route_line_type': 'Route Line Type',
      'as_line_continuous': 'Solid',
      'as_line_dotted': 'Dotted',
      'as_line_dashed': 'Dashed',
      'as_line_dot_dash': 'Dot-Dash',
      'as_alt_lines_color': 'Alternative Lines Color',
      'as_heavy_traffic_color': 'Heavy Traffic Color',
      'as_medium_traffic_color': 'Medium Traffic Color',
      'as_light_traffic_color': 'Light Traffic Color',
      'as_map_view_mode_title': 'Map View Mode',
      'as_view_2d': '2D',
      'as_view_3d': '3D',
      'as_3d_tilt_angle': '3D Tilt Angle',
      'as_theme_mode_title': 'App Light & Dark Mode',
      'as_theme_light': 'Light',
      'as_theme_dark': 'Dark',
      'as_theme_system': 'System Default',
      'as_app_color_title': 'App Color',
      'as_app_color_subtitle': 'Primary color for buttons and UI accents',
      'as_reset_changes': 'Reset Changes',
      'as_save_style': 'Save Style',
      'as_reset_snackbar': 'Changes reverted to default',
      'as_save_snackbar': 'Changes saved',
      'downloads_title': 'Downloads',
      'downloads_maps_tab': 'Maps',
      'downloads_voice_tab': 'Voice',
      'downloads_language_tab': 'Language',
      'downloads_maps_error': 'Error loading map list: {error}',
      'downloads_voice_error': 'Error loading voice packages: {error}',
      'downloads_language_error': 'Error loading languages: {error}',
      'downloads_retry': 'Retry',
      'downloads_empty_downloaded': 'Nothing downloaded',
      'downloads_empty_available': 'Nothing to download',

    }
  };

  static String get(BuildContext context, WidgetRef ref, String key) {
    final lang = ref.watch(languageProvider);
    // اول بسته‌ی دانلودی همون زبان، بعد نسخه‌ی درون‌اپ همون زبون (فارسی/
    // انگلیسی)، و در نهایت فارسیِ همراه اپ به‌عنوان fallback نهایی.
    return _downloadedValues[lang]?[key] ??
        _localizedValues[lang]?[key] ??
        _localizedValues['fa']?[key] ??
        key;
  }

  /// Like [get], but substitutes `{param}` placeholders in the localized
  /// string with the given values, e.g.
  /// getWithParams(context, ref, 'map_download_error', {'name': p.name, 'error': e})
  static String getWithParams(
    BuildContext context,
    WidgetRef ref,
    String key,
    Map<String, Object?> params,
  ) {
    var value = get(context, ref, key);
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', '$paramValue');
    });
    return value;
  }
}
