# -*- coding: utf-8 -*-
# Translations of the 116 new keys — group A: ar, cs, da, de, el, es, fi, fr, he
T = {}

T["ar"] = {
 "ai_dashcam_title":"الكاميرا الذكية","ai_dashcam_desc":"تسجيل الفيديو ومساعد القيادة الذكي",
 "dashcam_video_size":"حجم الفيديو","dashcam_video_size_unlimited":"∞ دقيقة",
 "dashcam_video_size_value":"{value} دقيقة ({size} جيجابايت)","dashcam_driver_assistance":"مساعد القيادة الذكي",
 "dashcam_fixed_camera_height":"ارتفاع الكاميرا الثابت","dashcam_camera_height":"ارتفاع الكاميرا",
 "dashcam_vehicle_width":"عرض المركبة","dashcam_camera_lateral_displacement":"الإزاحة الجانبية للكاميرا",
 "dashcam_forward_collision":"اصطدام أمامي","dashcam_dangerous_headway":"مسافة خطرة عن المركبة الأمامية",
 "dashcam_stop_and_go":"توقف وانطلق","dashcam_lane_departure_solid":"الانحراف عن المسار (خط متصل)",
 "dashcam_lane_departure_dashed":"الانحراف عن المسار (خط متقطع)","dashcam_traffic_sign_recognition":"التعرف على الإشارات المرورية",
 "hud_title":"شاشة العرض الأمامية (HUD)","hud_menu_desc":"عرض معلومات المسار على الزجاج الأمامي",
 "hud_enable":"تفعيل HUD","hud_enable_desc":"عرض معلومات المسار على الزجاج الأمامي",
 "hud_brightness":"سطوع الشاشة","hud_mirror":"صورة معكوسة","hud_mirror_desc":"للعرض الصحيح على الزجاج",
 "hud_scale":"مقياس العرض","hud_position":"موضع العرض على الزجاج",
 "hud_position_desc":"تحريك عام لشاشة HUD على الزجاج الأمامي","hud_visible_info":"المعلومات القابلة للعرض",
 "hud_info_speed":"السرعة","hud_info_speed_limit":"السرعة القصوى","hud_info_maneuver":"المسار والمنعطف التالي",
 "hud_info_distance":"المسافة إلى المنعطف","hud_info_heading":"الاتجاه (البوصلة)","hud_info_route_alerts":"تنبيهات المسار",
 "hud_info_ai_alerts":"تنبيهات الذكاء الاصطناعي","hud_info_other":"معلومات أخرى","hud_preview":"معاينة",
 "hud_note":"ملاحظة: لأفضل رؤية، استخدم HUD في بيئة منخفضة الإضاءة.",
 "hud_launch":"تشغيل HUD","hud_no_active_navigation":"ابدأ التنقل لاستخدام HUD","hud_arrived":"وصلت إلى الوجهة",
 "dashcam_level_off":"إيقاف","dashcam_level_low":"منخفض","dashcam_level_normal":"عادي","dashcam_level_high":"مرتفع",
 "dashcam_meters_short":"م","delete_language_package_title":"حذف حزمة اللغة",
 "delete_language_package_confirm":"حذف حزمة «{name}»؟","start_button":"بدء",
 "route_road_prefix":"إلى {road}","route_maneuver_depart":"ابدأ القيادة{road}","route_maneuver_arrive":"وصلت إلى الوجهة",
 "route_maneuver_turn_left":"انعطف يسارًا{road}","route_maneuver_turn_right":"انعطف يمينًا{road}",
 "route_maneuver_slight_left":"انعطف يسارًا قليلًا{road}","route_maneuver_slight_right":"انعطف يمينًا قليلًا{road}",
 "route_maneuver_sharp_left":"انعطف يسارًا بحدة{road}","route_maneuver_sharp_right":"انعطف يمينًا بحدة{road}",
 "route_maneuver_uturn":"استدر للخلف{road}","route_maneuver_straight":"واصل مستقيمًا{road}",
 "route_maneuver_continue":"تابع{road}","route_maneuver_roundabout":"ادخل الدوار{road}",
 "route_maneuver_roundabout_exit":"اخرج من المخرج {exit} في الدوار{road}",
 "route_maneuver_merge":"اندمج في الحركة{road}","route_maneuver_on_ramp":"ادخل المنحدر{road}",
 "route_maneuver_off_ramp":"اخرج من المنحدر{road}",
 "route_error_no_route":"لم يتم العثور على مسار بين نقطة البداية والوجهة.",
 "route_error_no_segment":"نقطة البداية أو الوجهة ليست قريبة من شبكة طرق قابلة للملاحة.",
 "route_error_too_big":"طلب المسار كبير جدًا.",
 "route_error_online_failed":"تعذرت خدمة المسار عبر الإنترنت من حساب المسار.",
 "route_error_offline_unavailable":"المسار عبر الإنترنت غير متاح في الوضع دون اتصال.",
 "route_error_offline_not_found":"لم يتم العثور على مسار على الخريطة دون اتصال.",
 "route_error_online_not_found":"لم يتم العثور على مسار بين نقطة البداية والوجهة.",
 "route_error_invalid_coordinates":"إحداثيات نقطة البداية أو الوجهة غير صالحة.",
 "route_error_unreadable_response":"تعذر قراءة استجابة خدمة المسار.",
 "route_error_invalid_geometry":"هندسة المسار عبر الإنترنت غير مكتملة أو غير صالحة.",
 "route_error_invalid_response":"استجابة المسار عبر الإنترنت بتنسيق غير صالح.",
 "route_error_connection":"تعذر الاتصال بخدمة المسار عبر الإنترنت.",
 "route_error_unexpected":"حدث خطأ غير متوقع أثناء المسار عبر الإنترنت.",
 "route_error_http":"أعادت خدمة المسار عبر الإنترنت استجابة غير صالحة ({code}).",
 "route_error_timeout":"انتهت مهلة استجابة المسار عبر الإنترنت. تحقق من اتصال الإنترنت.",
 "route_error_offline_map_missing":"ثبّت خريطة ABM دون اتصال قبل المسار.",
 "route_error_offline_generic":"خطأ في المسار دون اتصال ABTINMAP: {error}",
 "route_error_offline_alternatives":"فشل إنشاء مسارات بديلة دون اتصال ABTINMAP: {error}",
 "route_error_online_failed_generic":"فشل المسار عبر الإنترنت.",
 "route_duration_minutes":"{value} دقيقة","route_duration_hours_minutes":"{hours} س {minutes} دقيقة",
 "route_no_destination":"لم يتم تحديد وجهة",
 "route_open_map_destination":"اضغط مطولًا على الخريطة لاختيار وجهة.",
 "route_destination_ready":"الوجهة جاهزة للملاحة",
 "route_location_unavailable":"الموقع الحالي غير متاح","route_location_ready":"الموقع الحالي جاهز",
 "route_check_gps":"تحقق من إذن الموقع ونظام GPS.",
 "route_accuracy":"دقة الموقع: {value} م",
 "route_select_destination":"اختيار الوجهة","route_change_destination":"تغيير الوجهة",
 "route_suggested_routes":"المسارات المقترحة","route_calculation_failed":"فشل حساب المسار: {error}",
 "route_download_offline_map":"نزّل خريطة المنطقة للمسار دون اتصال.",
 "route_online_not_found_check_internet":"لم يتم العثور على مسار عبر الإنترنت؛ تحقق من اتصال الإنترنت.",
 "route_set_location_destination_hint":"حدد موقعك ووجهتك لرؤية خيارات المسار هنا.",
 "route_distance_km":"{value} كم","route_distance_m":"{value} م","route_eta":"الوصول","route_remaining":"المتبقي",
 "route_time":"الوقت","route_preview_instruction":"انعطف يمينًا إلى شارع وليعصر",
 "route_selected":"المسار المحدد","route_numbered":"المسار {value}",
 "alert_speed_camera":"كاميرا السرعة","alert_speed_bump":"مطب السرعة","alert_police":"نقطة شرطة المرور",
 "alert_traffic_light":"إشارة مرور","abtin_maps_user":"مستخدم آبتين مابس","as_palette_title":"لوحة الألوان",
 "as_display_mode_subtitle":"اختر وضع النهار أو الليل",
 "as_weather_widget_subtitle":"إعدادات عرض أداة الطقس على الخريطة",
}

T["cs"] = {
 "ai_dashcam_title":"Chytrá kamera","ai_dashcam_desc":"Nahrávání videa a chytrý řidičský asistent",
 "dashcam_video_size":"Velikost videa","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Chytrý řidičský asistent",
 "dashcam_fixed_camera_height":"Pevná výška kamery","dashcam_camera_height":"Výška kamery",
 "dashcam_vehicle_width":"Šířka vozidla","dashcam_camera_lateral_displacement":"Boční posun kamery",
 "dashcam_forward_collision":"Čelní srážka","dashcam_dangerous_headway":"Nebezpečný odstup od vozidla vpředu",
 "dashcam_stop_and_go":"Stop and go","dashcam_lane_departure_solid":"Vybočení z jízdního pruhu (plná čára)",
 "dashcam_lane_departure_dashed":"Vybočení z jízdního pruhu (přerušovaná čára)","dashcam_traffic_sign_recognition":"Rozpoznávání dopravních značek",
 "hud_title":"Head-up displej (HUD)","hud_menu_desc":"Zobrazit informace o trase na čelním skle",
 "hud_enable":"Povolit HUD","hud_enable_desc":"Zobrazit informace o trase na čelním skle",
 "hud_brightness":"Jas displeje","hud_mirror":"Zrcadlový obraz","hud_mirror_desc":"Pro správné zobrazení na skle",
 "hud_scale":"Měřítko zobrazení","hud_position":"Pozice zobrazení na skle",
 "hud_position_desc":"Celkové umístění HUD na čelním skle","hud_visible_info":"Zobrazitelné informace",
 "hud_info_speed":"Rychlost","hud_info_speed_limit":"Maximální rychlost","hud_info_maneuver":"Trasa a další zatáčka",
 "hud_info_distance":"Vzdálenost k zatáčce","hud_info_heading":"Směr (kompas)","hud_info_route_alerts":"Upozornění na trase",
 "hud_info_ai_alerts":"Upozornění AI","hud_info_other":"Další informace","hud_preview":"Náhled",
 "hud_note":"Poznámka: pro nejlepší viditelnost používejte HUD v prostředí s nízkým osvětlením.",
 "hud_launch":"Spustit HUD","hud_no_active_navigation":"Spusťte navigaci pro použití HUD","hud_arrived":"Dorazili jste do cíle",
 "dashcam_level_off":"Vypnuto","dashcam_level_low":"Nízká","dashcam_level_normal":"Normální","dashcam_level_high":"Vysoká",
 "dashcam_meters_short":"m","delete_language_package_title":"Smazat jazykový balíček",
 "delete_language_package_confirm":"Smazat balíček „{name}“?","start_button":"Start",
 "route_road_prefix":"na {road}","route_maneuver_depart":"Vydejte se{road}","route_maneuver_arrive":"Dorazili jste do cíle",
 "route_maneuver_turn_left":"Odbočte vlevo{road}","route_maneuver_turn_right":"Odbočte vpravo{road}",
 "route_maneuver_slight_left":"Mírně vlevo{road}","route_maneuver_slight_right":"Mírně vpravo{road}",
 "route_maneuver_sharp_left":"Ostře vlevo{road}","route_maneuver_sharp_right":"Ostře vpravo{road}",
 "route_maneuver_uturn":"Otočte se{road}","route_maneuver_straight":"Pokračujte rovně{road}",
 "route_maneuver_continue":"Pokračujte{road}","route_maneuver_roundabout":"Vjeďte do kruhového objezdu{road}",
 "route_maneuver_roundabout_exit":"Opusťte kruhový objezd výjezdem {exit}{road}",
 "route_maneuver_merge":"Zařaďte se{road}","route_maneuver_on_ramp":"Vjeďte na nájezd{road}",
 "route_maneuver_off_ramp":"Sjeďte z výjezdu{road}",
 "route_error_no_route":"Mezi počátkem a cílem nebyla nalezena žádná trasa.",
 "route_error_no_segment":"Počátek nebo cíl není blízko sjízdné silniční sítě.",
 "route_error_too_big":"Požadavek na trasu je příliš velký.",
 "route_error_online_failed":"Online služba tras nedokázala vypočítat trasu.",
 "route_error_offline_unavailable":"Online trasy nejsou v offline režimu dostupné.",
 "route_error_offline_not_found":"Na offline mapě nebyla nalezena žádná trasa.",
 "route_error_online_not_found":"Mezi počátkem a cílem nebyla nalezena žádná trasa.",
 "route_error_invalid_coordinates":"Souřadnice počátku nebo cíle jsou neplatné.",
 "route_error_unreadable_response":"Odpověď služby tras nelze přečíst.",
 "route_error_invalid_geometry":"Geometrie online trasy je neúplná nebo neplatná.",
 "route_error_invalid_response":"Odpověď online tras má neplatný formát.",
 "route_error_connection":"Nepodařilo se připojit k online službě tras.",
 "route_error_unexpected":"Došlo k neočekávané chybě při online trasování.",
 "route_error_http":"Online služba tras vrátila neplatnou odpověď ({code}).",
 "route_error_timeout":"Vypršel časový limit odpovědi online tras. Zkontrolujte připojení k internetu.",
 "route_error_offline_map_missing":"Před trasováním nainstalujte offline mapu ABM.",
 "route_error_offline_generic":"Chyba offline trasování ABTINMAP: {error}",
 "route_error_offline_alternatives":"Selhalo vytvoření offline alternativních tras ABTINMAP: {error}",
 "route_error_online_failed_generic":"Online trasování selhalo.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} h {minutes} min",
 "route_no_destination":"Není vybrán žádný cíl",
 "route_open_map_destination":"Dlouze stiskněte mapu pro výběr cíle.",
 "route_destination_ready":"Cíl je připraven k navigaci",
 "route_location_unavailable":"Aktuální poloha není dostupná","route_location_ready":"Aktuální poloha je připravena",
 "route_check_gps":"Zkontrolujte oprávnění k poloze a GPS.",
 "route_accuracy":"Přesnost polohy: {value} m",
 "route_select_destination":"Vybrat cíl","route_change_destination":"Změnit cíl",
 "route_suggested_routes":"Navržené trasy","route_calculation_failed":"Výpočet trasy selhal: {error}",
 "route_download_offline_map":"Stáhněte mapu oblasti pro offline trasování.",
 "route_online_not_found_check_internet":"Online trasa nenalezena; zkontrolujte připojení k internetu.",
 "route_set_location_destination_hint":"Nastavte polohu a cíl, aby se zde zobrazily možnosti trasy.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Příjezd","route_remaining":"Zbývá",
 "route_time":"Čas","route_preview_instruction":"Odbočte vpravo na ulici Valiasr",
 "route_selected":"Vybraná trasa","route_numbered":"Trasa {value}",
 "alert_speed_camera":"Rychlostní kamera","alert_speed_bump":"Zpomalovací práh","alert_police":"Dopravní kontrola",
 "alert_traffic_light":"Semafor","abtin_maps_user":"Uživatel Abtin Maps","as_palette_title":"Barevná paleta",
 "as_display_mode_subtitle":"Vyberte denní nebo noční režim",
 "as_weather_widget_subtitle":"Nastavení zobrazení widgetu počasí na mapě",
}

T["da"] = {
 "ai_dashcam_title":"Smart kamera","ai_dashcam_desc":"Videooptagelse og smart kørselsassistent",
 "dashcam_video_size":"Videostørrelse","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Smart kørselsassistent",
 "dashcam_fixed_camera_height":"Fast kamerahøjde","dashcam_camera_height":"Kamerahøjde",
 "dashcam_vehicle_width":"Køretøjets bredde","dashcam_camera_lateral_displacement":"Kameraets laterale forskydning",
 "dashcam_forward_collision":"Frontalt sammenstød","dashcam_dangerous_headway":"Farlig afstand til køretøjet foran",
 "dashcam_stop_and_go":"Stop og kør","dashcam_lane_departure_solid":"Vognbaneskift (fuld optrukket linje)",
 "dashcam_lane_departure_dashed":"Vognbaneskift (stiplet linje)","dashcam_traffic_sign_recognition":"Genkendelse af trafikskilte",
 "hud_title":"Head-up display (HUD)","hud_menu_desc":"Vis ruteoplysninger på forruden",
 "hud_enable":"Aktivér HUD","hud_enable_desc":"Vis ruteoplysninger på forruden",
 "hud_brightness":"Skærmlysstyrke","hud_mirror":"Spejlbillede","hud_mirror_desc":"For korrekt visning på glasset",
 "hud_scale":"Visningsskala","hud_position":"Placering på glasset",
 "hud_position_desc":"Samlet placering af HUD på forruden","hud_visible_info":"Visbare oplysninger",
 "hud_info_speed":"Hastighed","hud_info_speed_limit":"Hastighedsgrænse","hud_info_maneuver":"Rute og næste sving",
 "hud_info_distance":"Afstand til sving","hud_info_heading":"Retning (kompas)","hud_info_route_alerts":"Ruteadvarsler",
 "hud_info_ai_alerts":"AI-advarsler","hud_info_other":"Andre oplysninger","hud_preview":"Forhåndsvisning",
 "hud_note":"Bemærk: Brug HUD i omgivelser med lav belysning for bedst synlighed.",
 "hud_launch":"Start HUD","hud_no_active_navigation":"Start navigation for at bruge HUD","hud_arrived":"Du er nået frem",
 "dashcam_level_off":"Fra","dashcam_level_low":"Lav","dashcam_level_normal":"Normal","dashcam_level_high":"Høj",
 "dashcam_meters_short":"m","delete_language_package_title":"Slet sprogpakke",
 "delete_language_package_confirm":"Slet pakken \"{name}\"?","start_button":"Start",
 "route_road_prefix":"til {road}","route_maneuver_depart":"Begynd at køre{road}","route_maneuver_arrive":"Du er nået frem",
 "route_maneuver_turn_left":"Drej til venstre{road}","route_maneuver_turn_right":"Drej til højre{road}",
 "route_maneuver_slight_left":"Sving let til venstre{road}","route_maneuver_slight_right":"Sving let til højre{road}",
 "route_maneuver_sharp_left":"Sving skarpt til venstre{road}","route_maneuver_sharp_right":"Sving skarpt til højre{road}",
 "route_maneuver_uturn":"Vend rundt{road}","route_maneuver_straight":"Fortsæt ligeud{road}",
 "route_maneuver_continue":"Fortsæt{road}","route_maneuver_roundabout":"Kør ind i rundkørslen{road}",
 "route_maneuver_roundabout_exit":"Forlad rundkørslen ved afkørsel {exit}{road}",
 "route_maneuver_merge":"Flet ind{road}","route_maneuver_on_ramp":"Kør ind på tilkørselsrampen{road}",
 "route_maneuver_off_ramp":"Kør ud ad frakørselsrampen{road}",
 "route_error_no_route":"Der blev ikke fundet nogen rute mellem start og destination.",
 "route_error_no_segment":"Start eller destination er ikke tæt på et kørbart vejnet.",
 "route_error_too_big":"Ruteanmodningen er for stor.",
 "route_error_online_failed":"Online-rutetjenesten kunne ikke beregne ruten.",
 "route_error_offline_unavailable":"Online-ruter er ikke tilgængelige i offline-tilstand.",
 "route_error_offline_not_found":"Der blev ikke fundet nogen rute på offline-kortet.",
 "route_error_online_not_found":"Der blev ikke fundet nogen rute mellem start og destination.",
 "route_error_invalid_coordinates":"Koordinaterne for start eller destination er ugyldige.",
 "route_error_unreadable_response":"Rutetjenestens svar kan ikke læses.",
 "route_error_invalid_geometry":"Online-rutens geometri er ufuldstændig eller ugyldig.",
 "route_error_invalid_response":"Online-rutesvaret har et ugyldigt format.",
 "route_error_connection":"Kunne ikke oprette forbindelse til online-rutetjenesten.",
 "route_error_unexpected":"Der opstod en uventet fejl under online-ruteberegning.",
 "route_error_http":"Online-rutetjenesten returnerede et ugyldigt svar ({code}).",
 "route_error_timeout":"Online-rutesvaret fik timeout. Tjek din internetforbindelse.",
 "route_error_offline_map_missing":"Installer et offline ABM-kort, før du ruteberegner.",
 "route_error_offline_generic":"Fejl i offline-ruteberegning ABTINMAP: {error}",
 "route_error_offline_alternatives":"Kunne ikke oprette offline alternative ruter ABTINMAP: {error}",
 "route_error_online_failed_generic":"Online-ruteberegning mislykkedes.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} t {minutes} min",
 "route_no_destination":"Ingen destination valgt",
 "route_open_map_destination":"Hold kortet nede for at vælge en destination.",
 "route_destination_ready":"Destinationen er klar til navigation",
 "route_location_unavailable":"Aktuel placering er ikke tilgængelig","route_location_ready":"Aktuel placering er klar",
 "route_check_gps":"Tjek placeringstilladelse og GPS.",
 "route_accuracy":"Placeringsnøjagtighed: {value} m",
 "route_select_destination":"Vælg destination","route_change_destination":"Skift destination",
 "route_suggested_routes":"Foreslåede ruter","route_calculation_failed":"Ruteberegning mislykkedes: {error}",
 "route_download_offline_map":"Download områdekortet til offline-ruteberegning.",
 "route_online_not_found_check_internet":"Online-rute ikke fundet; tjek din internetforbindelse.",
 "route_set_location_destination_hint":"Indstil din placering og destination for at se rutevalg her.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Ankomst","route_remaining":"Tilbage",
 "route_time":"Tid","route_preview_instruction":"Drej til højre ad Valiasr-gaden",
 "route_selected":"Valgt rute","route_numbered":"Rute {value}",
 "alert_speed_camera":"Fartkamera","alert_speed_bump":"Fartbump","alert_police":"Trafikkontrol",
 "alert_traffic_light":"Trafiklys","abtin_maps_user":"Abtin Maps-bruger","as_palette_title":"Farvepalet",
 "as_display_mode_subtitle":"Vælg dag- eller nattilstand",
 "as_weather_widget_subtitle":"Indstillinger for visning af vejrwidget på kortet",
}

T["de"] = {
 "ai_dashcam_title":"Smart-Kamera","ai_dashcam_desc":"Videoaufnahme und intelligenter Fahrassistent",
 "dashcam_video_size":"Videogröße","dashcam_video_size_unlimited":"∞ Min.",
 "dashcam_video_size_value":"{value} Min. ({size} GB)","dashcam_driver_assistance":"Intelligenter Fahrassistent",
 "dashcam_fixed_camera_height":"Feste Kamerahöhe","dashcam_camera_height":"Kamerahöhe",
 "dashcam_vehicle_width":"Fahrzeugbreite","dashcam_camera_lateral_displacement":"Seitliche Kameraverschiebung",
 "dashcam_forward_collision":"Frontkollision","dashcam_dangerous_headway":"Gefährlicher Abstand zum Fahrzeug voraus",
 "dashcam_stop_and_go":"Stop-and-Go","dashcam_lane_departure_solid":"Spurverlassen (durchgezogene Linie)",
 "dashcam_lane_departure_dashed":"Spurverlassen (gestrichelte Linie)","dashcam_traffic_sign_recognition":"Verkehrsschilderkennung",
 "hud_title":"Head-up-Display (HUD)","hud_menu_desc":"Routeninformationen auf der Windschutzscheibe anzeigen",
 "hud_enable":"HUD aktivieren","hud_enable_desc":"Routeninformationen auf der Windschutzscheibe anzeigen",
 "hud_brightness":"Displayhelligkeit","hud_mirror":"Spiegelbild","hud_mirror_desc":"Für korrekte Anzeige auf der Scheibe",
 "hud_scale":"Anzeigemaßstab","hud_position":"Anzeigeposition auf der Scheibe",
 "hud_position_desc":"Gesamtplatzierung des HUD auf der Windschutzscheibe","hud_visible_info":"Anzeigbare Informationen",
 "hud_info_speed":"Geschwindigkeit","hud_info_speed_limit":"Tempolimit","hud_info_maneuver":"Route und nächste Abbiegung",
 "hud_info_distance":"Entfernung zur Abbiegung","hud_info_heading":"Richtung (Kompass)","hud_info_route_alerts":"Routenwarnungen",
 "hud_info_ai_alerts":"KI-Warnungen","hud_info_other":"Weitere Informationen","hud_preview":"Vorschau",
 "hud_note":"Hinweis: Verwenden Sie das HUD bei schlechten Lichtverhältnissen für beste Sicht.",
 "hud_launch":"HUD starten","hud_no_active_navigation":"Navigation starten, um HUD zu nutzen","hud_arrived":"Sie sind angekommen",
 "dashcam_level_off":"Aus","dashcam_level_low":"Niedrig","dashcam_level_normal":"Normal","dashcam_level_high":"Hoch",
 "dashcam_meters_short":"m","delete_language_package_title":"Sprachpaket löschen",
 "delete_language_package_confirm":"Paket „{name}“ löschen?","start_button":"Start",
 "route_road_prefix":"auf {road}","route_maneuver_depart":"Losfahren{road}","route_maneuver_arrive":"Sie sind am Ziel angekommen",
 "route_maneuver_turn_left":"Links abbiegen{road}","route_maneuver_turn_right":"Rechts abbiegen{road}",
 "route_maneuver_slight_left":"Leicht links{road}","route_maneuver_slight_right":"Leicht rechts{road}",
 "route_maneuver_sharp_left":"Scharf links{road}","route_maneuver_sharp_right":"Scharf rechts{road}",
 "route_maneuver_uturn":"Wenden{road}","route_maneuver_straight":"Gerade weiterfahren{road}",
 "route_maneuver_continue":"Weiterfahren{road}","route_maneuver_roundabout":"In den Kreisverkehr einfahren{road}",
 "route_maneuver_roundabout_exit":"Kreisverkehr an Ausfahrt {exit} verlassen{road}",
 "route_maneuver_merge":"Einfädeln{road}","route_maneuver_on_ramp":"Auf die Auffahrt fahren{road}",
 "route_maneuver_off_ramp":"Von der Ausfahrt abfahren{road}",
 "route_error_no_route":"Keine Route zwischen Start und Ziel gefunden.",
 "route_error_no_segment":"Start oder Ziel liegt nicht in der Nähe eines befahrbaren Straßennetzes.",
 "route_error_too_big":"Die Routenanfrage ist zu groß.",
 "route_error_online_failed":"Der Online-Routendienst konnte die Route nicht berechnen.",
 "route_error_offline_unavailable":"Online-Routen sind im Offline-Modus nicht verfügbar.",
 "route_error_offline_not_found":"Auf der Offline-Karte wurde keine Route gefunden.",
 "route_error_online_not_found":"Keine Route zwischen Start und Ziel gefunden.",
 "route_error_invalid_coordinates":"Die Koordinaten von Start oder Ziel sind ungültig.",
 "route_error_unreadable_response":"Die Antwort des Routendienstes kann nicht gelesen werden.",
 "route_error_invalid_geometry":"Die Geometrie der Online-Route ist unvollständig oder ungültig.",
 "route_error_invalid_response":"Die Online-Routenantwort hat ein ungültiges Format.",
 "route_error_connection":"Keine Verbindung zum Online-Routendienst möglich.",
 "route_error_unexpected":"Beim Online-Routing ist ein unerwarteter Fehler aufgetreten.",
 "route_error_http":"Der Online-Routendienst hat eine ungültige Antwort zurückgegeben ({code}).",
 "route_error_timeout":"Zeitüberschreitung der Online-Routenantwort. Internetverbindung prüfen.",
 "route_error_offline_map_missing":"Installieren Sie vor dem Routing eine Offline-ABM-Karte.",
 "route_error_offline_generic":"Fehler beim Offline-Routing ABTINMAP: {error}",
 "route_error_offline_alternatives":"Erstellen der Offline-Alternativrouten ABTINMAP fehlgeschlagen: {error}",
 "route_error_online_failed_generic":"Online-Routing fehlgeschlagen.",
 "route_duration_minutes":"{value} Min.","route_duration_hours_minutes":"{hours} Std. {minutes} Min.",
 "route_no_destination":"Kein Ziel ausgewählt",
 "route_open_map_destination":"Halten Sie die Karte gedrückt, um ein Ziel auszuwählen.",
 "route_destination_ready":"Ziel ist zur Navigation bereit",
 "route_location_unavailable":"Aktueller Standort nicht verfügbar","route_location_ready":"Aktueller Standort bereit",
 "route_check_gps":"Standortberechtigung und GPS prüfen.",
 "route_accuracy":"Standortgenauigkeit: {value} m",
 "route_select_destination":"Ziel auswählen","route_change_destination":"Ziel ändern",
 "route_suggested_routes":"Vorgeschlagene Routen","route_calculation_failed":"Routenberechnung fehlgeschlagen: {error}",
 "route_download_offline_map":"Laden Sie die Regionskarte für Offline-Routing herunter.",
 "route_online_not_found_check_internet":"Online-Route nicht gefunden; Internetverbindung prüfen.",
 "route_set_location_destination_hint":"Legen Sie Standort und Ziel fest, um hier Routenoptionen zu sehen.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Ankunft","route_remaining":"Verbleibend",
 "route_time":"Zeit","route_preview_instruction":"Rechts abbiegen auf die Valiasr-Straße",
 "route_selected":"Ausgewählte Route","route_numbered":"Route {value}",
 "alert_speed_camera":"Blitzer","alert_speed_bump":"Bodenschwelle","alert_police":"Verkehrskontrolle",
 "alert_traffic_light":"Ampel","abtin_maps_user":"Abtin Maps-Benutzer","as_palette_title":"Farbpalette",
 "as_display_mode_subtitle":"Tages- oder Nachtmodus wählen",
 "as_weather_widget_subtitle":"Einstellungen für die Wetter-Widget-Anzeige auf der Karte",
}

T["el"] = {
 "ai_dashcam_title":"Έξυπνη κάμερα","ai_dashcam_desc":"Εγγγράφηση βίντεο και έξυπνος βοηθός οδήγησης",
 "dashcam_video_size":"Μέγεθος βίντεο","dashcam_video_size_unlimited":"∞ λεπτά",
 "dashcam_video_size_value":"{value} λεπτά ({size} GB)","dashcam_driver_assistance":"Έξυπνος βοηθός οδήγησης",
 "dashcam_fixed_camera_height":"Σταθερό ύψος κάμερας","dashcam_camera_height":"Ύψος κάμερας",
 "dashcam_vehicle_width":"Πλάτος οχήματος","dashcam_camera_lateral_displacement":"Πλευρική μετατόπιση κάμερας",
 "dashcam_forward_collision":"Μετωπική σύγκρουση","dashcam_dangerous_headway":"Επικίνδυνη απόσταση από το προπορευόμενο όχημα",
 "dashcam_stop_and_go":"Σταμάτα και ξεκίνα","dashcam_lane_departure_solid":"Αλλαγή λωρίδας (συνεχής γραμμή)",
 "dashcam_lane_departure_dashed":"Αλλαγή λωρίδας (διακεκομμένη γραμμή)","dashcam_traffic_sign_recognition":"Αναγνώριση πινακίδων κυκλοφορίας",
 "hud_title":"Head-up display (HUD)","hud_menu_desc":"Εμφάνιση πληροφοριών διαδρομής στο παρμπρίζ",
 "hud_enable":"Ενεργοποίηση HUD","hud_enable_desc":"Εμφάνιση πληροφοριών διαδρομής στο παρμπρίζ",
 "hud_brightness":"Φωτεινότητα οθόνης","hud_mirror":"Κατοπτρική εικόνα","hud_mirror_desc":"Για σωστή εμφάνιση στο τζάμι",
 "hud_scale":"Κλίμακα εμφάνισης","hud_position":"Θέση εμφάνισης στο τζάμι",
 "hud_position_desc":"Συνολική τοποθέτηση του HUD στο παρμπρίζ","hud_visible_info":"Εμφανίσιμες πληροφορίες",
 "hud_info_speed":"Ταχύτητα","hud_info_speed_limit":"Όριο ταχύτητας","hud_info_maneuver":"Διαδρομή και επόμενη στροφή",
 "hud_info_distance":"Απόσταση από τη στροφή","hud_info_heading":"Κατεύθυνση (πυξίδα)","hud_info_route_alerts":"Ειδοποιήσεις διαδρομής",
 "hud_info_ai_alerts":"Ειδοποιήσεις AI","hud_info_other":"Άλλες πληροφορίες","hud_preview":"Προεπισκόπηση",
 "hud_note":"Σημείωση: για καλύτερη ορατότητα, χρησιμοποιήστε το HUD σε περιβάλλον με χαμηλό φωτισμό.",
 "hud_launch":"Εκκίνηση HUD","hud_no_active_navigation":"Ξεκινήστε πλοήγηση για να χρησιμοποιήσετε το HUD","hud_arrived":"Φτάσατε στον προορισμό",
 "dashcam_level_off":"Απενεργοποίηση","dashcam_level_low":"Χαμηλό","dashcam_level_normal":"Κανονικό","dashcam_level_high":"Υψηλό",
 "dashcam_meters_short":"μ","delete_language_package_title":"Διαγραφή πακέτου γλώσσας",
 "delete_language_package_confirm":"Διαγραφή πακέτου «{name}»;","start_button":"Έναρξη",
 "route_road_prefix":"στη {road}","route_maneuver_depart":"Ξεκινήστε την οδήγηση{road}","route_maneuver_arrive":"Φτάσατε στον προορισμό",
 "route_maneuver_turn_left":"Στρίψτε αριστερά{road}","route_maneuver_turn_right":"Στρίψτε δεξιά{road}",
 "route_maneuver_slight_left":"Ελαφρά αριστερά{road}","route_maneuver_slight_right":"Ελαφρά δεξιά{road}",
 "route_maneuver_sharp_left":"Απότομα αριστερά{road}","route_maneuver_sharp_right":"Απότομα δεξιά{road}",
 "route_maneuver_uturn":"Κάντε αναστροφή{road}","route_maneuver_straight":"Συνεχίστε ευθεία{road}",
 "route_maneuver_continue":"Συνεχίστε{road}","route_maneuver_roundabout":"Μπείτε στον κυκλικό κόμβο{road}",
 "route_maneuver_roundabout_exit":"Βγείτε από τον κυκλικό κόμβο στην έξοδο {exit}{road}",
 "route_maneuver_merge":"Συγχωνευτείτε{road}","route_maneuver_on_ramp":"Μπείτε στη ράμπα εισόδου{road}",
 "route_maneuver_off_ramp":"Βγείτε από τη ράμπα εξόδου{road}",
 "route_error_no_route":"Δεν βρέθηκε διαδρομή μεταξύ αφετηρίας και προορισμού.",
 "route_error_no_segment":"Η αφετηρία ή ο προορισμός δεν είναι κοντά σε οδικό δίκτυο με δυνατότητα πλοήγησης.",
 "route_error_too_big":"Το αίτημα διαδρομής είναι πολύ μεγάλο.",
 "route_error_online_failed":"Η διαδικτυακή υπηρεσία διαδρομών δεν μπόρεσε να υπολογίσει τη διαδρομή.",
 "route_error_offline_unavailable":"Οι διαδικτυακές διαδρομές δεν είναι διαθέσιμες σε λειτουργία εκτός σύνδεσης.",
 "route_error_offline_not_found":"Δεν βρέθηκε διαδρομή στον χάρτη εκτός σύνδεσης.",
 "route_error_online_not_found":"Δεν βρέθηκε διαδρομή μεταξύ αφετηρίας και προορισμού.",
 "route_error_invalid_coordinates":"Οι συντεταγμένες της αφετηρίας ή του προορισμού είναι άκυρες.",
 "route_error_unreadable_response":"Η απάντηση της υπηρεσίας διαδρομών δεν μπορεί να διαβαστεί.",
 "route_error_invalid_geometry":"Η γεωμετρία της διαδικτυακής διαδρομής είναι ελλιπής ή άκυρη.",
 "route_error_invalid_response":"Η απάντηση διαδικτυακής διαδρομής έχει άκυρη μορφή.",
 "route_error_connection":"Δεν ήταν δυνατή η σύνδεση με τη διαδικτυακή υπηρεσία διαδρομών.",
 "route_error_unexpected":"Προέκυψε μη αναμενόμενο σφάλμα κατά τη διαδικτυακή πλοήγηση.",
 "route_error_http":"Η διαδικτυακή υπηρεσία διαδρομών επέστρεψε άκυρη απάντηση ({code}).",
 "route_error_timeout":"Λήξη χρόνου απάντησης διαδικτυακής διαδρομής. Ελέγξτε τη σύνδεσή σας στο διαδίκτυο.",
 "route_error_offline_map_missing":"Εγκαταστήστε έναν χάρτη ABM εκτός σύνδεσης πριν από την πλοήγηση.",
 "route_error_offline_generic":"Σφάλμα στην εκτός σύνδεσης πλοήγηση ABTINMAP: {error}",
 "route_error_offline_alternatives":"Αποτυχία δημιουργίας εναλλακτικών διαδρομών εκτός σύνδεσης ABTINMAP: {error}",
 "route_error_online_failed_generic":"Η διαδικτυακή πλοήγηση απέτυχε.",
 "route_duration_minutes":"{value} λεπτά","route_duration_hours_minutes":"{hours} ώ {minutes} λεπτά",
 "route_no_destination":"Δεν έχει επιλεγεί προορισμός",
 "route_open_map_destination":"Πατήστε παρατεταμένα τον χάρτη για να επιλέξετε προορισμό.",
 "route_destination_ready":"Ο προορισμός είναι έτοιμος για πλοήγηση",
 "route_location_unavailable":"Η τρέχουσα τοποθεσία δεν είναι διαθέσιμη","route_location_ready":"Η τρέχουσα τοποθεσία είναι έτοιμη",
 "route_check_gps":"Ελέγξτε την άδεια τοποθεσίας και το GPS.",
 "route_accuracy":"Ακρίβεια τοποθεσίας: {value} μ",
 "route_select_destination":"Επιλογή προορισμού","route_change_destination":"Αλλαγή προορισμού",
 "route_suggested_routes":"Προτεινόμενες διαδρομές","route_calculation_failed":"Αποτυχία υπολογισμού διαδρομής: {error}",
 "route_download_offline_map":"Κατεβάστε τον χάρτη της περιοχής για πλοήγηση εκτός σύνδεσης.",
 "route_online_not_found_check_internet":"Δεν βρέθηκε διαδικτυακή διαδρομή· ελέγξτε τη σύνδεσή σας.",
 "route_set_location_destination_hint":"Ορίστε τοποθεσία και προορισμό για να δείτε επιλογές διαδρομής εδώ.",
 "route_distance_km":"{value} χλμ","route_distance_m":"{value} μ","route_eta":"Άφιξη","route_remaining":"Απομένει",
 "route_time":"Χρόνος","route_preview_instruction":"Στρίψτε δεξιά στην οδό Valiasr",
 "route_selected":"Επιλεγμένη διαδρομή","route_numbered":"Διαδρομή {value}",
 "alert_speed_camera":"Κάμερα ταχύτητας","alert_speed_bump":"Σαμαράκι","alert_police":"Τροχονομικός έλεγχος",
 "alert_traffic_light":"Φανάρι","abtin_maps_user":"Χρήστης Abtin Maps","as_palette_title":"Χρωματική παλέτα",
 "as_display_mode_subtitle":"Επιλέξτε λειτουργία ημέρας ή νύχτας",
 "as_weather_widget_subtitle":"Ρυθμίσεις εμφάνισης widget καιρού στον χάρτη",
}

T["es"] = {
 "ai_dashcam_title":"Cámara inteligente","ai_dashcam_desc":"Grabación de video y asistente inteligente de conducción",
 "dashcam_video_size":"Tamaño de video","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Asistente inteligente de conducción",
 "dashcam_fixed_camera_height":"Altura fija de la cámara","dashcam_camera_height":"Altura de la cámara",
 "dashcam_vehicle_width":"Ancho del vehículo","dashcam_camera_lateral_displacement":"Desplazamiento lateral de la cámara",
 "dashcam_forward_collision":"Colisión frontal","dashcam_dangerous_headway":"Distancia peligrosa con el vehículo de adelante",
 "dashcam_stop_and_go":"Parar y arrancar","dashcam_lane_departure_solid":"Salida de carril (línea continua)",
 "dashcam_lane_departure_dashed":"Salida de carril (línea discontinua)","dashcam_traffic_sign_recognition":"Reconocimiento de señales de tráfico",
 "hud_title":"Pantalla de visualización frontal (HUD)","hud_menu_desc":"Mostrar información de la ruta en el parabrisas",
 "hud_enable":"Activar HUD","hud_enable_desc":"Mostrar información de la ruta en el parabrisas",
 "hud_brightness":"Brillo de la pantalla","hud_mirror":"Imagen en espejo","hud_mirror_desc":"Para una visualización correcta en el cristal",
 "hud_scale":"Escala de visualización","hud_position":"Posición en el cristal",
 "hud_position_desc":"Colocación general del HUD en el parabrisas","hud_visible_info":"Información visible",
 "hud_info_speed":"Velocidad","hud_info_speed_limit":"Límite de velocidad","hud_info_maneuver":"Ruta y próximo giro",
 "hud_info_distance":"Distancia al giro","hud_info_heading":"Dirección (brújula)","hud_info_route_alerts":"Alertas de ruta",
 "hud_info_ai_alerts":"Alertas de IA","hud_info_other":"Otra información","hud_preview":"Vista previa",
 "hud_note":"Nota: para una mejor visibilidad, use el HUD en un entorno con poca luz.",
 "hud_launch":"Iniciar HUD","hud_no_active_navigation":"Inicie la navegación para usar el HUD","hud_arrived":"Ha llegado a su destino",
 "dashcam_level_off":"Apagado","dashcam_level_low":"Bajo","dashcam_level_normal":"Normal","dashcam_level_high":"Alto",
 "dashcam_meters_short":"m","delete_language_package_title":"Eliminar paquete de idioma",
 "delete_language_package_confirm":"¿Eliminar el paquete «{name}»?","start_button":"Iniciar",
 "route_road_prefix":"hacia {road}","route_maneuver_depart":"Comience a conducir{road}","route_maneuver_arrive":"Ha llegado a su destino",
 "route_maneuver_turn_left":"Gire a la izquierda{road}","route_maneuver_turn_right":"Gire a la derecha{road}",
 "route_maneuver_slight_left":"Gire ligeramente a la izquierda{road}","route_maneuver_slight_right":"Gire ligeramente a la derecha{road}",
 "route_maneuver_sharp_left":"Gire bruscamente a la izquierda{road}","route_maneuver_sharp_right":"Gire bruscamente a la derecha{road}",
 "route_maneuver_uturn":"Dé la vuelta{road}","route_maneuver_straight":"Continúe recto{road}",
 "route_maneuver_continue":"Continúe{road}","route_maneuver_roundabout":"Entre en la rotonda{road}",
 "route_maneuver_roundabout_exit":"Salga de la rotonda por la salida {exit}{road}",
 "route_maneuver_merge":"Incorpórese{road}","route_maneuver_on_ramp":"Entre en la rampa de acceso{road}",
 "route_maneuver_off_ramp":"Salga por la rampa de salida{road}",
 "route_error_no_route":"No se encontró ninguna ruta entre el origen y el destino.",
 "route_error_no_segment":"El origen o el destino no está cerca de una red vial transitable.",
 "route_error_too_big":"La solicitud de ruta es demasiado grande.",
 "route_error_online_failed":"El servicio de rutas en línea no pudo calcular la ruta.",
 "route_error_offline_unavailable":"Las rutas en línea no están disponibles en modo sin conexión.",
 "route_error_offline_not_found":"No se encontró ninguna ruta en el mapa sin conexión.",
 "route_error_online_not_found":"No se encontró ninguna ruta entre el origen y el destino.",
 "route_error_invalid_coordinates":"Las coordenadas del origen o del destino no son válidas.",
 "route_error_unreadable_response":"No se puede leer la respuesta del servicio de rutas.",
 "route_error_invalid_geometry":"La geometría de la ruta en línea es incompleta o no válida.",
 "route_error_invalid_response":"La respuesta de rutas en línea tiene un formato no válido.",
 "route_error_connection":"No se pudo conectar con el servicio de rutas en línea.",
 "route_error_unexpected":"Se produjo un error inesperado durante el enrutamiento en línea.",
 "route_error_http":"El servicio de rutas en línea devolvió una respuesta no válida ({code}).",
 "route_error_timeout":"Se agotó el tiempo de respuesta de rutas en línea. Compruebe su conexión a internet.",
 "route_error_offline_map_missing":"Instale un mapa ABM sin conexión antes de enrutar.",
 "route_error_offline_generic":"Error en el enrutamiento sin conexión ABTINMAP: {error}",
 "route_error_offline_alternatives":"No se pudieron crear rutas alternativas sin conexión ABTINMAP: {error}",
 "route_error_online_failed_generic":"El enrutamiento en línea falló.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} h {minutes} min",
 "route_no_destination":"No se ha seleccionado ningún destino",
 "route_open_map_destination":"Mantenga pulsado el mapa para elegir un destino.",
 "route_destination_ready":"El destino está listo para la navegación",
 "route_location_unavailable":"La ubicación actual no está disponible","route_location_ready":"La ubicación actual está lista",
 "route_check_gps":"Compruebe el permiso de ubicación y el GPS.",
 "route_accuracy":"Precisión de ubicación: {value} m",
 "route_select_destination":"Seleccionar destino","route_change_destination":"Cambiar destino",
 "route_suggested_routes":"Rutas sugeridas","route_calculation_failed":"El cálculo de la ruta falló: {error}",
 "route_download_offline_map":"Descargue el mapa de la región para enrutar sin conexión.",
 "route_online_not_found_check_internet":"No se encontró ruta en línea; compruebe su conexión a internet.",
 "route_set_location_destination_hint":"Establezca su ubicación y destino para ver las opciones de ruta aquí.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Llegada","route_remaining":"Restante",
 "route_time":"Tiempo","route_preview_instruction":"Gire a la derecha hacia la calle Valiasr",
 "route_selected":"Ruta seleccionada","route_numbered":"Ruta {value}",
 "alert_speed_camera":"Radar de velocidad","alert_speed_bump":"Reductor de velocidad","alert_police":"Control de tráfico",
 "alert_traffic_light":"Semáforo","abtin_maps_user":"Usuario de Abtin Maps","as_palette_title":"Paleta de colores",
 "as_display_mode_subtitle":"Elija el modo diurno o nocturno",
 "as_weather_widget_subtitle":"Configuración de la visualización del widget del clima en el mapa",
}

T["fi"] = {
 "ai_dashcam_title":"Älykäs kamera","ai_dashcam_desc":"Videotallennus ja älykäs ajoneuvon avustaja",
 "dashcam_video_size":"Videon koko","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} Gt)","dashcam_driver_assistance":"Älykäs ajoneuvon avustaja",
 "dashcam_fixed_camera_height":"Kiinteä kameran korkeus","dashcam_camera_height":"Kameran korkeus",
 "dashcam_vehicle_width":"Ajoneuvon leveys","dashcam_camera_lateral_displacement":"Kameran sivuttaissiirtymä",
 "dashcam_forward_collision":"Etutörmäys","dashcam_dangerous_headway":"Vaarallinen etäisyys edellä olevaan ajoneuvoon",
 "dashcam_stop_and_go":"Pysäytä ja jatka","dashcam_lane_departure_solid":"Kaistalta poistuminen (yhtäyinen viiva)",
 "dashcam_lane_departure_dashed":"Kaistalta poistuminen (katkoviiva)","dashcam_traffic_sign_recognition":"Liikennemerkkien tunnistus",
 "hud_title":"Head-up-näyttö (HUD)","hud_menu_desc":"Näytä reittitiedot tuulilasissa",
 "hud_enable":"Ota HUD käyttöön","hud_enable_desc":"Näytä reittitiedot tuulilasissa",
 "hud_brightness":"Näytön kirkkaus","hud_mirror":"Peilikkuva","hud_mirror_desc":"Oikeaa näyttöä varten lasissa",
 "hud_scale":"Näytön mittakaava","hud_position":"Näytön sijainti lasissa",
 "hud_position_desc":"HUD:n kokonaissijoittelu tuulilasissa","hud_visible_info":"Näytettävät tiedot",
 "hud_info_speed":"Nopeus","hud_info_speed_limit":"Nopeusrajoitus","hud_info_maneuver":"Reitti ja seuraava käännös",
 "hud_info_distance":"Etäisyys käännökseen","hud_info_heading":"Suunta (kompassi)","hud_info_route_alerts":"Reittihälytykset",
 "hud_info_ai_alerts":"AI-hälytykset","hud_info_other":"Muut tiedot","hud_preview":"Esikatselu",
 "hud_note":"Huomautus: käytä HUD:ia hämärässä ympäristössä parhaan näkyvyyden saavuttamiseksi.",
 "hud_launch":"Käynnistä HUD","hud_no_active_navigation":"Käynnistä navigointi HUD:in käyttäminen","hud_arrived":"Olet saapunut määränpäähän",
 "dashcam_level_off":"Pois","dashcam_level_low":"Matala","dashcam_level_normal":"Normaali","dashcam_level_high":"Korkea",
 "dashcam_meters_short":"m","delete_language_package_title":"Poista kielipaketti",
 "delete_language_package_confirm":"Poistetaanko paketti \"{name}\"?","start_button":"Aloita",
 "route_road_prefix":"kohteeseen {road}","route_maneuver_depart":"Aloita ajaminen{road}","route_maneuver_arrive":"Olet saapunut määränpäähän",
 "route_maneuver_turn_left":"Käänny vasemmalle{road}","route_maneuver_turn_right":"Käänny oikealle{road}",
 "route_maneuver_slight_left":"Käänny hieman vasemmalle{road}","route_maneuver_slight_right":"Käänny hieman oikealle{road}",
 "route_maneuver_sharp_left":"Käänny jyrkästi vasemmalle{road}","route_maneuver_sharp_right":"Käänny jyrkästi oikealle{road}",
 "route_maneuver_uturn":"Käänny ympäri{road}","route_maneuver_straight":"Jatka suoraan{road}",
 "route_maneuver_continue":"Jatka{road}","route_maneuver_roundabout":"Aja liikenneympyrään{road}",
 "route_maneuver_roundabout_exit":"Poistu liikenneympyrästä uloskäynnistä {exit}{road}",
 "route_maneuver_merge":"Liity liikenteeseen{road}","route_maneuver_on_ramp":"Aja sisääntulorampille{road}",
 "route_maneuver_off_ramp":"Poistu uloskäyntirampista{road}",
 "route_error_no_route":"Lähtöpaikan ja määränpään välillä ei löytynyt reittiä.",
 "route_error_no_segment":"Lähtöpaikka tai määränpää ei ole lähellä ajettavaa tieverkkoa.",
 "route_error_too_big":"Reittipyyntö on liian suuri.",
 "route_error_online_failed":"Verkkoreittipalvelu ei pystynyt laskemaan reittiä.",
 "route_error_offline_unavailable":"Verkkoreitit eivät ole käytettävissä offline-tilassa.",
 "route_error_offline_not_found":"Offline-karttasta ei löytynyt reittiä.",
 "route_error_online_not_found":"Lähtöpaikan ja määränpään välillä ei löytynyt reittiä.",
 "route_error_invalid_coordinates":"Lähtöpaikan tai määränpään koordinaatit ovat virheelliset.",
 "route_error_unreadable_response":"Reittipalvelun vastaustta ei voida lukea.",
 "route_error_invalid_geometry":"Verkkoreitin geometria on puutteellinen tai virheellinen.",
 "route_error_invalid_response":"Verkkoreittivastauksessa on virheellinen muoto.",
 "route_error_connection":"Yhteyttä verkkoreittipalveluun ei saatu.",
 "route_error_unexpected":"Verkkoreitityksessä tapahtui odottamaton virhe.",
 "route_error_http":"Verkkoreittipalvelu palautti virheellisen vastauksen ({code}).",
 "route_error_timeout":"Verkkoreittivastauksen aikakatkaisu. Tarkista internetyhteytesi.",
 "route_error_offline_map_missing":"Asenna ABM-offlinekartta ennen reititystä.",
 "route_error_offline_generic":"Virhe ABTINMAP-offlinereitityksessä: {error}",
 "route_error_offline_alternatives":"ABTINMAP:n offline-vaihtoehtoisreittien luonti epäonnistui: {error}",
 "route_error_online_failed_generic":"Verkkoreititys epäonnistui.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} t {minutes} min",
 "route_no_destination":"Määränpäätä ei ole valittu",
 "route_open_map_destination":"Pidä karttaa painettuna valitaksesi määränpään.",
 "route_destination_ready":"Määränpää on valmis navigointiin",
 "route_location_unavailable":"Nykyinen sijainti ei ole käytettävissä","route_location_ready":"Nykyinen sijainti on valmis",
 "route_check_gps":"Tarkista sijainnin käyttöoikeus ja GPS.",
 "route_accuracy":"Sijainnin tarkkuus: {value} m",
 "route_select_destination":"Valitse määränpää","route_change_destination":"Vaihda määränpää",
 "route_suggested_routes":"Ehdotetut reitit","route_calculation_failed":"Reitin laskenta epäonnistui: {error}",
 "route_download_offline_map":"Lataa alueen kartta offline-reititystä varten.",
 "route_online_not_found_check_internet":"Verkkoreittiä ei löytynyt; tarkista internetyhteytesi.",
 "route_set_location_destination_hint":"Aseta sijainti ja määränpää nähdäksesi reittivaihtoehdot tässä.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Saapuminen","route_remaining":"Jäljellä",
 "route_time":"Aika","route_preview_instruction":"Käänny oikealle Valiasr-kadulle",
 "route_selected":"Valittu reitti","route_numbered":"Reitti {value}",
 "alert_speed_camera":"Nopeituskamera","alert_speed_bump":"Töötti","alert_police":"Liikennevalvonta",
 "alert_traffic_light":"Liikennevalo","abtin_maps_user":"Abtin Maps -käyttäjä","as_palette_title":"Väripaletti",
 "as_display_mode_subtitle":"Valitse päivä- tai yötila",
 "as_weather_widget_subtitle":"Sääwidgetin näyttöasetukset kartalla",
}

T["fr"] = {
 "ai_dashcam_title":"Caméra intelligente","ai_dashcam_desc":"Enregistrement vidéo et assistant de conduite intelligent",
 "dashcam_video_size":"Taille de la vidéo","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} Go)","dashcam_driver_assistance":"Assistant de conduite intelligent",
 "dashcam_fixed_camera_height":"Hauteur de caméra fixe","dashcam_camera_height":"Hauteur de la caméra",
 "dashcam_vehicle_width":"Largeur du véhicule","dashcam_camera_lateral_displacement":"Déplacement latéral de la caméra",
 "dashcam_forward_collision":"Collision frontale","dashcam_dangerous_headway":"Distance dangereuse avec le véhicule précédant",
 "dashcam_stop_and_go":"Stop and go","dashcam_lane_departure_solid":"Franchissement de ligne (ligne continue)",
 "dashcam_lane_departure_dashed":"Franchissement de ligne (ligne discontinue)","dashcam_traffic_sign_recognition":"Reconnaissance des panneaux de signalisation",
 "hud_title":"Affichage tête haute (HUD)","hud_menu_desc":"Afficher les informations d'itinéraire sur le pare-brise",
 "hud_enable":"Activer le HUD","hud_enable_desc":"Afficher les informations d'itinéraire sur le pare-brise",
 "hud_brightness":"Luminosité de l'écran","hud_mirror":"Image miroir","hud_mirror_desc":"Pour un affichage correct sur la vitre",
 "hud_scale":"Échelle d'affichage","hud_position":"Position sur la vitre",
 "hud_position_desc":"Placement global du HUD sur le pare-brise","hud_visible_info":"Informations affichables",
 "hud_info_speed":"Vitesse","hud_info_speed_limit":"Limite de vitesse","hud_info_maneuver":"Itinéraire et prochain virage",
 "hud_info_distance":"Distance au virage","hud_info_heading":"Cap (boussole)","hud_info_route_alerts":"Alertes d'itinéraire",
 "hud_info_ai_alerts":"Alertes IA","hud_info_other":"Autres informations","hud_preview":"Aperçu",
 "hud_note":"Remarque : pour une meilleure visibilité, utilisez le HUD dans un environnement peu éclairé.",
 "hud_launch":"Lancer le HUD","hud_no_active_navigation":"Démarrez la navigation pour utiliser le HUD","hud_arrived":"Vous êtes arrivé à destination",
 "dashcam_level_off":"Désactivé","dashcam_level_low":"Faible","dashcam_level_normal":"Normal","dashcam_level_high":"Élevé",
 "dashcam_meters_short":"m","delete_language_package_title":"Supprimer le pack de langue",
 "delete_language_package_confirm":"Supprimer le pack « {name} » ?","start_button":"Démarrer",
 "route_road_prefix":"vers {road}","route_maneuver_depart":"Commencez à rouler{road}","route_maneuver_arrive":"Vous êtes arrivé à destination",
 "route_maneuver_turn_left":"Tournez à gauche{road}","route_maneuver_turn_right":"Tournez à droite{road}",
 "route_maneuver_slight_left":"Tournez légèrement à gauche{road}","route_maneuver_slight_right":"Tournez légèrement à droite{road}",
 "route_maneuver_sharp_left":"Tournez franchement à gauche{road}","route_maneuver_sharp_right":"Tournez franchement à droite{road}",
 "route_maneuver_uturn":"Faites demi-tour{road}","route_maneuver_straight":"Continuez tout droit{road}",
 "route_maneuver_continue":"Continuez{road}","route_maneuver_roundabout":"Engagez le rond-point{road}",
 "route_maneuver_roundabout_exit":"Sortez du rond-point à la sortie {exit}{road}",
 "route_maneuver_merge":"Insérez-vous{road}","route_maneuver_on_ramp":"Prenez la bretelle d'accès{road}",
 "route_maneuver_off_ramp":"Prenez la bretelle de sortie{road}",
 "route_error_no_route":"Aucun itinéraire trouvé entre le départ et la destination.",
 "route_error_no_segment":"Le départ ou la destination n'est pas proche d'un réseau routier praticable.",
 "route_error_too_big":"La demande d'itinéraire est trop grande.",
 "route_error_online_failed":"Le service d'itinéraire en ligne n'a pas pu calculer l'itinéraire.",
 "route_error_offline_unavailable":"Les itinéraires en ligne ne sont pas disponibles hors connexion.",
 "route_error_offline_not_found":"Aucun itinéraire trouvé sur la carte hors ligne.",
 "route_error_online_not_found":"Aucun itinéraire trouvé entre le départ et la destination.",
 "route_error_invalid_coordinates":"Les coordonnées du départ ou de la destination sont invalides.",
 "route_error_unreadable_response":"La réponse du service d'itinéraire est illisible.",
 "route_error_invalid_geometry":"La géométrie de l'itinéraire en ligne est incomplète ou invalide.",
 "route_error_invalid_response":"La réponse d'itinéraire en ligne a un format invalide.",
 "route_error_connection":"Impossible de se connecter au service d'itinéraire en ligne.",
 "route_error_unexpected":"Une erreur inattendue est survenue lors du calcul en ligne.",
 "route_error_http":"Le service d'itinéraire en ligne a renvoyé une réponse invalide ({code}).",
 "route_error_timeout":"Délai de réponse de l'itinéraire en ligne dépassé. Vérifiez votre connexion internet.",
 "route_error_offline_map_missing":"Installez une carte ABM hors ligne avant de calculer un itinéraire.",
 "route_error_offline_generic":"Erreur de calcul hors ligne ABTINMAP : {error}",
 "route_error_offline_alternatives":"Échec de la création d'itinéraires alternatifs hors ligne ABTINMAP : {error}",
 "route_error_online_failed_generic":"Le calcul d'itinéraire en ligne a échoué.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} h {minutes} min",
 "route_no_destination":"Aucune destination sélectionnée",
 "route_open_map_destination":"Appuyez longuement sur la carte pour choisir une destination.",
 "route_destination_ready":"La destination est prête pour la navigation",
 "route_location_unavailable":"Position actuelle indisponible","route_location_ready":"Position actuelle prête",
 "route_check_gps":"Vérifiez l'autorisation de localisation et le GPS.",
 "route_accuracy":"Précision de la position : {value} m",
 "route_select_destination":"Sélectionner la destination","route_change_destination":"Changer la destination",
 "route_suggested_routes":"Itinéraires suggérés","route_calculation_failed":"Échec du calcul de l'itinéraire : {error}",
 "route_download_offline_map":"Téléchargez la carte de la région pour le calcul hors ligne.",
 "route_online_not_found_check_internet":"Aucun itinéraire en ligne trouvé ; vérifiez votre connexion internet.",
 "route_set_location_destination_hint":"Définissez votre position et destination pour voir les options d'itinéraire ici.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Arrivée","route_remaining":"Restant",
 "route_time":"Temps","route_preview_instruction":"Tournez à droite sur la rue Valiasr",
 "route_selected":"Itinéraire sélectionné","route_numbered":"Itinéraire {value}",
 "alert_speed_camera":"Radar de vitesse","alert_speed_bump":"Ralentisseur","alert_police":"Contrôle de police",
 "alert_traffic_light":"Feu de circulation","abtin_maps_user":"Utilisateur Abtin Maps","as_palette_title":"Palette de couleurs",
 "as_display_mode_subtitle":"Choisissez le mode jour ou nuit",
 "as_weather_widget_subtitle":"Paramètres d'affichage du widget météo sur la carte",
}

T["he"] = {
 "ai_dashcam_title":"מצלמה חכמה","ai_dashcam_desc":"הקלטת וידאו ועוזר נהיגה חכם",
 "dashcam_video_size":"גודל וידאו","dashcam_video_size_unlimited":"∞ דקות",
 "dashcam_video_size_value":"{value} דקות ({size} גיגה-בייט)","dashcam_driver_assistance":"עוזר נהיגה חכם",
 "dashcam_fixed_camera_height":"גובה מצלמה קבוע","dashcam_camera_height":"גובה המצלמה",
 "dashcam_vehicle_width":"רוחב הרכב","dashcam_camera_lateral_displacement":"הסטה צידית של המצלמה",
 "dashcam_forward_collision":"התנגשות חזיתית","dashcam_dangerous_headway":"מרחק מסוכן מהרכב שלפניך",
 "dashcam_stop_and_go":"עצור וסע","dashcam_lane_departure_solid":"סטייה מנת (קו רציף)",
 "dashcam_lane_departure_dashed":"סטייה מנת (קו מקווקו)","dashcam_traffic_sign_recognition":"זיהוי תמרורים",
 "hud_title":"תצוגה עילית (HUD)","hud_menu_desc":"הצגת מידע על המסלול על השמשה הקדמית",
 "hud_enable":"הפעלת HUD","hud_enable_desc":"הצגת מידע על המסלול על השמשה הקדמית",
 "hud_brightness":"בהירות מסך","hud_mirror":"תמונת ראי","hud_mirror_desc":"לתצוגה נכונה על הזכוכית",
 "hud_scale":"קנה מידה לתצוגה","hud_position":"מיקום התצוגה על הזכוכית",
 "hud_position_desc":"מיקום כללי של ה-HUD על השמשה הקדמית","hud_visible_info":"מידע שניתן להציג",
 "hud_info_speed":"מהירות","hud_info_speed_limit":"מהירות מותרת","hud_info_maneuver":"המסלול והפנייה הבאה",
 "hud_info_distance":"מרחק לפנייה","hud_info_heading":"כיוון (מצפן)","hud_info_route_alerts":"התראות מסלול",
 "hud_info_ai_alerts":"התראות AI","hud_info_other":"מידע אחר","hud_preview":"תצ preview",
 "hud_note":"הערה: לנראות מיטבית, השתמשו ב-HUD בסביבה מוארת חלשה.",
 "hud_launch":"הפעלת HUD","hud_no_active_navigation":"התכו ניווט כדי להשתמש ב-HUD","hud_arrived":"הגעתם ליעד",
 "dashcam_level_off":"כבוי","dashcam_level_low":"נמוך","dashcam_level_normal":"רגיל","dashcam_level_high":"גבוה",
 "dashcam_meters_short":"מ'","delete_language_package_title":"מחיקת חבילת שפה",
 "delete_language_package_confirm":"למחוך את החבילה \"{name}\"?","start_button":"התחל",
 "route_road_prefix":"ל-{road}","route_maneuver_depart":"התחילו לנסוע{road}","route_maneuver_arrive":"הגעתם ליעד",
 "route_maneuver_turn_left":"פנו שמאלה{road}","route_maneuver_turn_right":"פנו ימינה{road}",
 "route_maneuver_slight_left":"פנו מעט שמאלה{road}","route_maneuver_slight_right":"פנו מעט ימינה{road}",
 "route_maneuver_sharp_left":"פנו בחדות שמאלה{road}","route_maneuver_sharp_right":"פנו בחדות ימינה{road}",
 "route_maneuver_uturn":"בצעו פניית פרסה{road}","route_maneuver_straight":"המשיכו ישר{road}",
 "route_maneuver_continue":"המשיכו{road}","route_maneuver_roundabout":"היכנסו לכיכר{road}",
 "route_maneuver_roundabout_exit":"צאו מהכיכר ביציאה {exit}{road}",
 "route_maneuver_merge":"השתלבו{road}","route_maneuver_on_ramp":"היכנסו לרמפת עלייה{road}",
 "route_maneuver_off_ramp":"צאו ברמפת ירידה{road}",
 "route_error_no_route":"לא נמצא מסלול בין המוצא ליעד.",
 "route_error_no_segment":"המוצא או היעד אינו קרוב לרשת כבישים ניתנת לניווט.",
 "route_error_too_big":"בקשת המסלול גדולה מדי.",
 "route_error_online_failed":"שירות המסלולים המקוון לא הצליח לחשב את המסלול.",
 "route_error_offline_unavailable":"מסלולים מקוונים אינם זמינים במצב לא מקוון.",
 "route_error_offline_not_found":"לא נמצא מסלול במפה הלא מקוונת.",
 "route_error_online_not_found":"לא נמצא מסלול בין המוצא ליעד.",
 "route_error_invalid_coordinates":"קואורדינטות המוצא או היעד אינן תקינות.",
 "route_error_unreadable_response":"לא ניתן לקרוא את תגובת שירות המסלולים.",
 "route_error_invalid_geometry":"הגיאומטריה של המסלול המקוון חסרה או לא תקינה.",
 "route_error_invalid_response":"לתגובת המסלול המקוון יש פורמט לא תקין.",
 "route_error_connection":"לא ניתן היה להתחבר לשירות המסלולים המקוון.",
 "route_error_unexpected":"אירעה שגיאה בלתי צפויה בניווט המקוון.",
 "route_error_http":"שירות המסלולים המקוון החזיר תגובה לא תקינה ({code}).",
 "route_error_timeout":"פג תוקף תגובת המסלול המקוון. בדקו את חיבור האינטרנט.",
 "route_error_offline_map_missing":"התקינו מפת ABM לא מקוונת לפני ניווט.",
 "route_error_offline_generic":"שגיאה בניווט לא מקוון ABTINMAP: {error}",
 "route_error_offline_alternatives":"נכשל יצירת מסלולים חלופיים לא מקוונים ABTINMAP: {error}",
 "route_error_online_failed_generic":"הניווט המקוון נכשל.",
 "route_duration_minutes":"{value} דקות","route_duration_hours_minutes":"{hours} שע' {minutes} דקות",
 "route_no_destination":"לא נבחר יעד",
 "route_open_map_destination":"לחצו והחזיקו על המפה כדי לבחור יעד.",
 "route_destination_ready":"היעד מוכן לניווט",
 "route_location_unavailable":"המיקום הנוכחי אינו זמין","route_location_ready":"המיקום הנוכחי מוכן",
 "route_check_gps":"בדקו הרשאת מיקום ו-GPS.",
 "route_accuracy":"דיוק מיקום: {value} מ'",
 "route_select_destination":"בחירת יעד","route_change_destination":"שינוי יעד",
 "route_suggested_routes":"מסלולים מוצעים","route_calculation_failed":"חישוב המסלול נכשל: {error}",
 "route_download_offline_map":"הורידו את מפת האזור לניווט לא מקוון.",
 "route_online_not_found_check_internet":"לא נמצא מסלול מקוון; בדקו את חיבור האינטרנט.",
 "route_set_location_destination_hint":"הגדירו מיקום ויעד כדי לראות אפשרויות מסלול כאן.",
 "route_distance_km":"{value} ק\"מ","route_distance_m":"{value} מ'","route_eta":"הגעה","route_remaining":"נותר",
 "route_time":"זמן","route_preview_instruction":"פנו ימינה לרחוב ואליאסר",
 "route_selected":"המסלול שנבחר","route_numbered":"מסלול {value}",
 "alert_speed_camera":"מצלמת מהירות","alert_speed_bump":"מהמורת מהירות","alert_police":"מחסום משטרה",
 "alert_traffic_light":"רמזור","abtin_maps_user":"משתמש Abtin Maps","as_palette_title":"פלטת צבעים",
 "as_display_mode_subtitle":"בחרו מצב יום או לילה",
 "as_weather_widget_subtitle":"הגדרות תצוגת ווידג'ט מזג האוויר על המפה",
}
