# -*- coding: utf-8 -*-
# Translations of the 116 new keys — group B: hi, hu, id, it, ja, ko, nl, no, pl, pt
T = {}

T["hi"] = {
 "ai_dashcam_title":"स्मार्ट कैमरा","ai_dashcam_desc":"वीडियो रिकॉर्डिंग और स्मार्ट ड्राइविंग सहायक",
 "dashcam_video_size":"वीडियो आकार","dashcam_video_size_unlimited":"∞ मिनट",
 "dashcam_video_size_value":"{value} मिनट ({size} GB)","dashcam_driver_assistance":"स्मार्ट ड्राइविंग सहायक",
 "dashcam_fixed_camera_height":"स्थिर कैमरा ऊँचाई","dashcam_camera_height":"कैमरा ऊँचाई",
 "dashcam_vehicle_width":"वाहन की चौड़ाई","dashcam_camera_lateral_displacement":"कैमरा पार्श्व विस्थापन",
 "dashcam_forward_collision":"सामने से टक्कर","dashcam_dangerous_headway":"सामने वाले वाहन से खतरनाक दूरी",
 "dashcam_stop_and_go":"रुकना और चलना","dashcam_lane_departure_solid":"लेन से बाहर (ठोस रेखा)",
 "dashcam_lane_departure_dashed":"लेन से बाहर (धराशायी रेखा)","dashcam_traffic_sign_recognition":"यातायात संकेत पहचान",
 "hud_title":"हेड-अप डिस्प्ले (HUD)","hud_menu_desc":"विंडशील्ड पर मार्ग जानकारी दिखाएँ",
 "hud_enable":"HUD सक्षम करें","hud_enable_desc":"विंडशील्ड पर मार्ग जानकारी दिखाएँ",
 "hud_brightness":"डिस्प्ले चमक","hud_mirror":"दर्पण छवि","hud_mirror_desc":"कांच पर सही प्रदर्शन के लिए",
 "hud_scale":"डिस्प्ले स्केल","hud_position":"कांच पर डिस्प्ले स्थिति",
 "hud_position_desc":"विंडशील्ड पर HUD की समग्र स्थिति","hud_visible_info":"प्रदर्शित होने योग्य जानकारी",
 "hud_info_speed":"गति","hud_info_speed_limit":"गति सीमा","hud_info_maneuver":"मार्ग और अगला मोड़",
 "hud_info_distance":"मोड़ तक दूरी","hud_info_heading":"दिशा (कम्पास)","hud_info_route_alerts":"मार्ग अलर्ट",
 "hud_info_ai_alerts":"AI अलर्ट","hud_info_other":"अन्य जानकारी","hud_preview":"पूर्वावलोकन",
 "hud_note":"नोट: सर्वोत्तम दृश्यता के लिए, कम रोशनी वाले वातावरण में HUD का उपयोग करें।",
 "hud_launch":"HUD लॉन्च करें","hud_no_active_navigation":"HUD उपयोग के लिए नेविगेशन शुरू करें","hud_arrived":"आप गंतव्य पर पहुँच गए",
 "dashcam_level_off":"बंद","dashcam_level_low":"कम","dashcam_level_normal":"सामान्य","dashcam_level_high":"उच्च",
 "dashcam_meters_short":"मी","delete_language_package_title":"भाषा पैकेज हटाएँ",
 "delete_language_package_confirm":"पैकेज \"{name}\" हटाएँ?","start_button":"प्रारंभ",
 "route_road_prefix":"पर {road}","route_maneuver_depart":"गाड़ी चलाना शुरू करें{road}","route_maneuver_arrive":"आप गंतव्य पर पहुँच गए",
 "route_maneuver_turn_left":"बाएँ मुड़ें{road}","route_maneuver_turn_right":"दाएँ मुड़ें{road}",
 "route_maneuver_slight_left":"हल्का बाएँ{road}","route_maneuver_slight_right":"हल्का दाएँ{road}",
 "route_maneuver_sharp_left":"तीखा बाएँ{road}","route_maneuver_sharp_right":"तीखा दाएँ{road}",
 "route_maneuver_uturn":"यू-टर्न लें{road}","route_maneuver_straight":"सीधे चलते रहें{road}",
 "route_maneuver_continue":"जारी रखें{road}","route_maneuver_roundabout":"गोल चक्कर में प्रवेश करें{road}",
 "route_maneuver_roundabout_exit":"गोल चक्कर से निकास {exit} लें{road}",
 "route_maneuver_merge":"विलय करें{road}","route_maneuver_on_ramp":"प्रवेश रैंप पर जाएँ{road}",
 "route_maneuver_off_ramp":"निकास रैंप से बाहर जाएँ{road}",
 "route_error_no_route":"प्रारंभ और गंतव्य के बीच कोई मार्ग नहीं मिला।",
 "route_error_no_segment":"प्रारंभ या गंतव्य किसी नौगम्य सड़क नेटवर्क के पास नहीं है।",
 "route_error_too_big":"मार्ग अनुरोध बहुत बड़ा है।",
 "route_error_online_failed":"ऑनलाइन मार्ग सेवा मार्ग की गणना नहीं कर सकी।",
 "route_error_offline_unavailable":"ऑफ़लाइन मोड में ऑनलाइन मार्ग उपलब्ध नहीं हैं।",
 "route_error_offline_not_found":"ऑफ़लाइन मानचित्र पर कोई मार्ग नहीं मिला।",
 "route_error_online_not_found":"प्रारंभ और गंतव्य के बीच कोई मार्ग नहीं मिला।",
 "route_error_invalid_coordinates":"प्रारंभ या गंतव्य के निर्देशांक अमान्य हैं।",
 "route_error_unreadable_response":"मार्ग सेवा का उत्तर पढ़ा नहीं जा सकता।",
 "route_error_invalid_geometry":"ऑनलाइन मार्ग की ज्यामिति अधूरी या अमान्य है।",
 "route_error_invalid_response":"ऑनलाइन मार्ग उत्तर का प्रारूप अमान्य है।",
 "route_error_connection":"ऑनलाइन मार्ग सेवा से कनेक्ट नहीं हो सका।",
 "route_error_unexpected":"ऑनलाइन मार्ग-निर्धारण में अप्रत्याशित त्रुटि हुई।",
 "route_error_http":"ऑनलाइन मार्ग सेवा ने अमान्य उत्तर दिया ({code})।",
 "route_error_timeout":"ऑनलाइन मार्ग उत्तर का समय समाप्त हुआ। अपना इंटरनेट कनेक्शन जाँचें।",
 "route_error_offline_map_missing":"मार्ग-निर्धारण से पहले एक ऑफ़लाइन ABM मानचित्र स्थापित करें।",
 "route_error_offline_generic":"ABTINMAP ऑफ़लाइन मार्ग-निर्धारण में त्रुटि: {error}",
 "route_error_offline_alternatives":"ABTINMAP ऑफ़लाइन वैकल्पिक मार्ग बनाने में विफल: {error}",
 "route_error_online_failed_generic":"ऑनलाइन मार्ग-निर्धारण विफल हुआ।",
 "route_duration_minutes":"{value} मिनट","route_duration_hours_minutes":"{hours} घं {minutes} मिनट",
 "route_no_destination":"कोई गंतव्य चयनित नहीं है",
 "route_open_map_destination":"गंतव्य चुनने के लिए मानचित्र को देर तक दबाएँ।",
 "route_destination_ready":"गंतव्य नेविगेशन के लिए तैयार है",
 "route_location_unavailable":"वर्तमान स्थान उपलब्ध नहीं है","route_location_ready":"वर्तमान स्थान तैयार है",
 "route_check_gps":"स्थान अनुमति और GPS जाँचें।",
 "route_accuracy":"स्थान सटीकता: {value} मी",
 "route_select_destination":"गंतव्य चुनें","route_change_destination":"गंतव्य बदलें",
 "route_suggested_routes":"सुझाए गए मार्ग","route_calculation_failed":"मार्ग गणना विफल: {error}",
 "route_download_offline_map":"ऑफ़लाइन मार्ग के लिए क्षेत्र का मानचित्र डाउनलोड करें।",
 "route_online_not_found_check_internet":"ऑनलाइन मार्ग नहीं मिला; अपना इंटरनेट कनेक्शन जाँचें।",
 "route_set_location_destination_hint":"यहाँ मार्ग विकल्प देखने के लिए स्थान और गंतव्य निर्धारित करें।",
 "route_distance_km":"{value} किमी","route_distance_m":"{value} मी","route_eta":"आगमन","route_remaining":"शेष",
 "route_time":"समय","route_preview_instruction":"वलियसर सड़क पर दाएँ मुड़ें",
 "route_selected":"चयनित मार्ग","route_numbered":"मार्ग {value}",
 "alert_speed_camera":"स्पीड कैमरा","alert_speed_bump":"स्पीड ब्रेकर","alert_police":"यातायात पुलिस",
 "alert_traffic_light":"यातायात बत्ती","abtin_maps_user":"Abtin Maps उपयोगकर्ता","as_palette_title":"रंग पैलेट",
 "as_display_mode_subtitle":"दिन या रात मोड चुनें",
 "as_weather_widget_subtitle":"मानचित्र पर मौसम विजेट प्रदर्शन सेटिंग्स",
}

T["hu"] = {
 "ai_dashcam_title":"Okos kamera","ai_dashcam_desc":"Videofelvétel és intelligens vezetési asszisztens",
 "dashcam_video_size":"Videó mérete","dashcam_video_size_unlimited":"∞ perc",
 "dashcam_video_size_value":"{value} perc ({size} GB)","dashcam_driver_assistance":"Intelligens vezetési asszisztens",
 "dashcam_fixed_camera_height":"Rögzített kameramagasság","dashcam_camera_height":"Kameramagasság",
 "dashcam_vehicle_width":"Járműszélesség","dashcam_camera_lateral_displacement":"Kamera oldalirányú elmozdulása",
 "dashcam_forward_collision":"Frontális ütközés","dashcam_dangerous_headway":"Veszélyes követési távolság az előttünk haladó járműtől",
 "dashcam_stop_and_go":"Stop and go","dashcam_lane_departure_solid":"Sávelhagyás (folytonos vonal)",
 "dashcam_lane_departure_dashed":"Sávelhagyás (szaggatott vonal)","dashcam_traffic_sign_recognition":"Közlekedési táblák felismerése",
 "hud_title":"Head-up kijelző (HUD)","hud_menu_desc":"Útvonalinformációk megjelenítése a szélvédőn",
 "hud_enable":"HUD engedélyezése","hud_enable_desc":"Útvonalinformációk megjelenítése a szélvédőn",
 "hud_brightness":"Kijelző fényereje","hud_mirror":"Tükörkép","hud_mirror_desc":"A helyes megjelenítéshez az üvegen",
 "hud_scale":"Megjelenítési méretarány","hud_position":"Megjelenítési pozíció az üvegen",
 "hud_position_desc":"A HUD általános elhelyezése a szélvédőn","hud_visible_info":"Megjeleníthető információk",
 "hud_info_speed":"Sebesség","hud_info_speed_limit":"Sebességkorlát","hud_info_maneuver":"Útvonal és következő kanyar",
 "hud_info_distance":"Távolság a kanyarig","hud_info_heading":"Irány (iránytű)","hud_info_route_alerts":"Útvonal-riasztások",
 "hud_info_ai_alerts":"AI-riasztások","hud_info_other":"Egyéb információk","hud_preview":"Előnézet",
 "hud_note":"Megjegyzés: a legjobb láthatóság érdekében gyenge fényviszonyok között használja a HUD-ot.",
 "hud_launch":"HUD indítása","hud_no_active_navigation":"A HUD használatához indítsa a navigációt","hud_arrived":"Megérkezett a célponthoz",
 "dashcam_level_off":"Ki","dashcam_level_low":"Alacsony","dashcam_level_normal":"Normál","dashcam_level_high":"Magas",
 "dashcam_meters_short":"m","delete_language_package_title":"Nyelvi csomag törlése",
 "delete_language_package_confirm":"Töröljük a(z) „{name}” csomagot?","start_button":"Indítás",
 "route_road_prefix":"a(z) {road} felé","route_maneuver_depart":"Kezdje el a vezetést{road}","route_maneuver_arrive":"Megérkezett a célponthoz",
 "route_maneuver_turn_left":"Forduljon balra{road}","route_maneuver_turn_right":"Forduljon jobbra{road}",
 "route_maneuver_slight_left":"Enyhén balra{road}","route_maneuver_slight_right":"Enyhén jobbra{road}",
 "route_maneuver_sharp_left":"Élesen balra{road}","route_maneuver_sharp_right":"Élesen jobbra{road}",
 "route_maneuver_uturn":"Forduljon meg{road}","route_maneuver_straight":"Haladjon egyenesen{road}",
 "route_maneuver_continue":"Folytassa{road}","route_maneuver_roundabout":"Hajtson be a körforgalomba{road}",
 "route_maneuver_roundabout_exit":"Hagyja el a körforgalmat a {exit}. kijáratnál{road}",
 "route_maneuver_merge":"Soroljon be{road}","route_maneuver_on_ramp":"Hajtson fel a felhajtóra{road}",
 "route_maneuver_off_ramp":"Hajtson le a lehajtón{road}",
 "route_error_no_route":"Nem található útvonal a kiindulópont és a cél között.",
 "route_error_no_segment":"A kiindulópont vagy a cél nincs a navigálható úthálózat közelében.",
 "route_error_too_big":"Az útvonalkérés túl nagy.",
 "route_error_online_failed":"Az online útvonalszolgáltatás nem tudta kiszámítani az útvonalat.",
 "route_error_offline_unavailable":"Az online útvonalak offline módban nem érhetők el.",
 "route_error_offline_not_found":"Nem található útvonal az offline térképen.",
 "route_error_online_not_found":"Nem található útvonal a kiindulópont és a cél között.",
 "route_error_invalid_coordinates":"A kiindulópont vagy a cél koordinátái érvénytelenek.",
 "route_error_unreadable_response":"Az útvonalszolgáltatás válasza nem olvasható.",
 "route_error_invalid_geometry":"Az online útvonal geometriája hiányos vagy érvénytelen.",
 "route_error_invalid_response":"Az online útvonalválasz formátuma érvénytelen.",
 "route_error_connection":"Nem sikerült csatlakozni az online útvonalszolgáltatáshoz.",
 "route_error_unexpected":"Váratlan hiba történt az online útvonaltervezés során.",
 "route_error_http":"Az online útvonalszolgáltatás érvénytelen választ adott ({code}).",
 "route_error_timeout":"Az online útvonalválasz időtúllépés. Ellenőrizze az internetkapcsolatot.",
 "route_error_offline_map_missing":"Telepítsen egy offline ABM térképet az útvonaltervezés előtt.",
 "route_error_offline_generic":"Hiba az ABTINMAP offline útvonaltervezésben: {error}",
 "route_error_offline_alternatives":"Az ABTINMAP offline alternatív útvonalak létrehozása sikertelen: {error}",
 "route_error_online_failed_generic":"Az online útvonaltervezés sikertelen.",
 "route_duration_minutes":"{value} perc","route_duration_hours_minutes":"{hours} ó {minutes} perc",
 "route_no_destination":"Nincs célpont kiválasztva",
 "route_open_map_destination":"A célpont kiválasztásához tartsa lenyomva a térképet.",
 "route_destination_ready":"A célpont készen áll a navigációra",
 "route_location_unavailable":"Az aktuális helyzet nem érhető el","route_location_ready":"Az aktuális helyzet kész",
 "route_check_gps":"Ellenőrizze a helymeghatározási engedélyt és a GPS-t.",
 "route_accuracy":"Helymeghatározás pontossága: {value} m",
 "route_select_destination":"Célpont kiválasztása","route_change_destination":"Célpont módosítása",
 "route_suggested_routes":"Javasolt útvonalak","route_calculation_failed":"Az útvonalszámítás sikertelen: {error}",
 "route_download_offline_map":"Töltse le a régió térképét az offline útvonaltervezéshez.",
 "route_online_not_found_check_internet":"Online útvonal nem található; ellenőrizze az internetkapcsolatot.",
 "route_set_location_destination_hint":"Adja meg a helyzetet és a célt, hogy itt lássa az útvonalopciókat.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Érkezés","route_remaining":"Hátralévő",
 "route_time":"Idő","route_preview_instruction":"Forduljon jobbra a Valiasr utcára",
 "route_selected":"Kiválasztott útvonal","route_numbered":"Útvonal {value}",
 "alert_speed_camera":"Sebességmérő kamera","alert_speed_bump":"Sebességcsökkentő","alert_police":"Rendőri ellenőrzés",
 "alert_traffic_light":"Közlekedési lámpa","abtin_maps_user":"Abtin Maps felhasználó","as_palette_title":"Színpaletta",
 "as_display_mode_subtitle":"Válasszon nappali vagy éjszakai módot",
 "as_weather_widget_subtitle":"Időjárás-widget megjelenítési beállításai a térképen",
}

T["id"] = {
 "ai_dashcam_title":"Kamera Pintar","ai_dashcam_desc":"Rekaman video dan asisten mengemudi cerdas",
 "dashcam_video_size":"Ukuran video","dashcam_video_size_unlimited":"∞ menit",
 "dashcam_video_size_value":"{value} menit ({size} GB)","dashcam_driver_assistance":"Asisten mengemudi cerdas",
 "dashcam_fixed_camera_height":"Tinggi kamera tetap","dashcam_camera_height":"Tinggi kamera",
 "dashcam_vehicle_width":"Lebar kendaraan","dashcam_camera_lateral_displacement":"Perpindahan lateral kamera",
 "dashcam_forward_collision":"Tabrakan depan","dashcam_dangerous_headway":"Jarak berbahaya dengan kendaraan di depan",
 "dashcam_stop_and_go":"Berhenti dan jalan","dashcam_lane_departure_solid":"Keluar jalur (garis lurus)",
 "dashcam_lane_departure_dashed":"Keluar jalur (garis putus-putus)","dashcam_traffic_sign_recognition":"Pengenalan rambu lalu lintas",
 "hud_title":"Head-up display (HUD)","hud_menu_desc":"Tampilkan info rute di kaca depan",
 "hud_enable":"Aktifkan HUD","hud_enable_desc":"Tampilkan info rute di kaca depan",
 "hud_brightness":"Kecerahan layar","hud_mirror":"Gambar cermin","hud_mirror_desc":"Untuk tampilan yang benar di kaca",
 "hud_scale":"Skala tampilan","hud_position":"Posisi tampilan di kaca",
 "hud_position_desc":"Penempatan keseluruhan HUD di kaca depan","hud_visible_info":"Informasi yang dapat ditampilkan",
 "hud_info_speed":"Kecepatan","hud_info_speed_limit":"Batas kecepatan","hud_info_maneuver":"Rute dan belokan berikutnya",
 "hud_info_distance":"Jarak ke belokan","hud_info_heading":"Arah (kompas)","hud_info_route_alerts":"Peringatan rute",
 "hud_info_ai_alerts":"Peringatan AI","hud_info_other":"Informasi lain","hud_preview":"Pratinjau",
 "hud_note":"Catatan: untuk visibilitas terbaik, gunakan HUD di lingkungan dengan cahaya redup.",
 "hud_launch":"Luncurkan HUD","hud_no_active_navigation":"Mulai navigasi untuk menggunakan HUD","hud_arrived":"Anda telah tiba di tujuan",
 "dashcam_level_off":"Mati","dashcam_level_low":"Rendah","dashcam_level_normal":"Normal","dashcam_level_high":"Tinggi",
 "dashcam_meters_short":"m","delete_language_package_title":"Hapus paket bahasa",
 "delete_language_package_confirm":"Hapus paket \"{name}\"?","start_button":"Mulai",
 "route_road_prefix":"menuju {road}","route_maneuver_depart":"Mulai berkendara{road}","route_maneuver_arrive":"Anda telah tiba di tujuan",
 "route_maneuver_turn_left":"Belok kiri{road}","route_maneuver_turn_right":"Belok kanan{road}",
 "route_maneuver_slight_left":"Belok sedikit ke kiri{road}","route_maneuver_slight_right":"Belok sedikit ke kanan{road}",
 "route_maneuver_sharp_left":"Belok tajam ke kiri{road}","route_maneuver_sharp_right":"Belok tajam ke kanan{road}",
 "route_maneuver_uturn":"Putar balik{road}","route_maneuver_straight":"Terus lurus{road}",
 "route_maneuver_continue":"Lanjutkan{road}","route_maneuver_roundabout":"Masuk ke bundaran{road}",
 "route_maneuver_roundabout_exit":"Keluar dari bundaran di pintu keluar {exit}{road}",
 "route_maneuver_merge":"Gabung{road}","route_maneuver_on_ramp":"Masuk ke ramp{road}",
 "route_maneuver_off_ramp":"Keluar dari ramp{road}",
 "route_error_no_route":"Tidak ditemukan rute antara titik awal dan tujuan.",
 "route_error_no_segment":"Titik awal atau tujuan tidak dekat dengan jaringan jalan yang dapat dilalui.",
 "route_error_too_big":"Permintaan rute terlalu besar.",
 "route_error_online_failed":"Layanan rute online tidak dapat menghitung rute.",
 "route_error_offline_unavailable":"Rute online tidak tersedia dalam mode offline.",
 "route_error_offline_not_found":"Tidak ditemukan rute di peta offline.",
 "route_error_online_not_found":"Tidak ditemukan rute antara titik awal dan tujuan.",
 "route_error_invalid_coordinates":"Koordinat titik awal atau tujuan tidak valid.",
 "route_error_unreadable_response":"Respons layanan rute tidak dapat dibaca.",
 "route_error_invalid_geometry":"Geometri rute online tidak lengkap atau tidak valid.",
 "route_error_invalid_response":"Respons rute online memiliki format yang tidak valid.",
 "route_error_connection":"Tidak dapat terhubung ke layanan rute online.",
 "route_error_unexpected":"Terjadi kesalahan tak terduga dalam perutean online.",
 "route_error_http":"Layanan rute online mengembalikan respons tidak valid ({code}).",
 "route_error_timeout":"Waktu respons rute online habis. Periksa koneksi internet Anda.",
 "route_error_offline_map_missing":"Pasang peta ABM offline sebelum melakukan perutean.",
 "route_error_offline_generic":"Kesalahan perutean offline ABTINMAP: {error}",
 "route_error_offline_alternatives":"Gagal membuat rute alternatif offline ABTINMAP: {error}",
 "route_error_online_failed_generic":"Perutean online gagal.",
 "route_duration_minutes":"{value} menit","route_duration_hours_minutes":"{hours} jam {minutes} menit",
 "route_no_destination":"Belum ada tujuan yang dipilih",
 "route_open_map_destination":"Tekan lama peta untuk memilih tujuan.",
 "route_destination_ready":"Tujuan siap untuk navigasi",
 "route_location_unavailable":"Lokasi saat ini tidak tersedia","route_location_ready":"Lokasi saat ini siap",
 "route_check_gps":"Periksa izin lokasi dan GPS.",
 "route_accuracy":"Akurasi lokasi: {value} m",
 "route_select_destination":"Pilih tujuan","route_change_destination":"Ubah tujuan",
 "route_suggested_routes":"Rute yang disarankan","route_calculation_failed":"Perhitungan rute gagal: {error}",
 "route_download_offline_map":"Unduh peta wilayah untuk perutean offline.",
 "route_online_not_found_check_internet":"Rute online tidak ditemukan; periksa koneksi internet Anda.",
 "route_set_location_destination_hint":"Atur lokasi dan tujuan untuk melihat opsi rute di sini.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Tiba","route_remaining":"Sisa",
 "route_time":"Waktu","route_preview_instruction":"Belok kanan ke Jalan Valiasr",
 "route_selected":"Rute terpilih","route_numbered":"Rute {value}",
 "alert_speed_camera":"Kamera kecepatan","alert_speed_bump":"Polisi tidur","alert_police":"Pos polisi lalu lintas",
 "alert_traffic_light":"Lampu lalu lintas","abtin_maps_user":"Pengguna Abtin Maps","as_palette_title":"Palet warna",
 "as_display_mode_subtitle":"Pilih mode siang atau malam",
 "as_weather_widget_subtitle":"Pengaturan tampilan widget cuaca di peta",
}

T["it"] = {
 "ai_dashcam_title":"Telecamera intelligente","ai_dashcam_desc":"Registrazione video e assistente di guida intelligente",
 "dashcam_video_size":"Dimensione video","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Assistente di guida intelligente",
 "dashcam_fixed_camera_height":"Altezza telecamera fissa","dashcam_camera_height":"Altezza telecamera",
 "dashcam_vehicle_width":"Larghezza veicolo","dashcam_camera_lateral_displacement":"Spostamento laterale della telecamera",
 "dashcam_forward_collision":"Collisione frontale","dashcam_dangerous_headway":"Distanza pericolosa dal veicolo che precede",
 "dashcam_stop_and_go":"Stop and go","dashcam_lane_departure_solid":"Uscita di corsia (linea continua)",
 "dashcam_lane_departure_dashed":"Uscita di corsia (linea tratteggiata)","dashcam_traffic_sign_recognition":"Riconoscimento dei segnali stradali",
 "hud_title":"Head-up display (HUD)","hud_menu_desc":"Mostra le informazioni sul percorso sul parabrezza",
 "hud_enable":"Attiva HUD","hud_enable_desc":"Mostra le informazioni sul percorso sul parabrezza",
 "hud_brightness":"Luminosità del display","hud_mirror":"Immagine speculare","hud_mirror_desc":"Per una visualizzazione corretta sul vetro",
 "hud_scale":"Scala di visualizzazione","hud_position":"Posizione sul vetro",
 "hud_position_desc":"Posizionamento complessivo dell'HUD sul parabrezza","hud_visible_info":"Informazioni visualizzabili",
 "hud_info_speed":"Velocità","hud_info_speed_limit":"Limite di velocità","hud_info_maneuver":"Percorso e prossima svolta",
 "hud_info_distance":"Distanza alla svolta","hud_info_heading":"Direzione (bussola)","hud_info_route_alerts":"Avvisi di percorso",
 "hud_info_ai_alerts":"Avvisi AI","hud_info_other":"Altre informazioni","hud_preview":"Anteprima",
 "hud_note":"Nota: per una migliore visibilità, usa l'HUD in un ambiente con poca luce.",
 "hud_launch":"Avvia HUD","hud_no_active_navigation":"Avvia la navigazione per usare l'HUD","hud_arrived":"Sei arrivato a destinazione",
 "dashcam_level_off":"Spento","dashcam_level_low":"Basso","dashcam_level_normal":"Normale","dashcam_level_high":"Alto",
 "dashcam_meters_short":"m","delete_language_package_title":"Elimina pacchetto lingua",
 "delete_language_package_confirm":"Eliminare il pacchetto «{name}»?","start_button":"Avvia",
 "route_road_prefix":"su {road}","route_maneuver_depart":"Inizia a guidare{road}","route_maneuver_arrive":"Sei arrivato a destinazione",
 "route_maneuver_turn_left":"Svolta a sinistra{road}","route_maneuver_turn_right":"Svolta a destra{road}",
 "route_maneuver_slight_left":"Leggera a sinistra{road}","route_maneuver_slight_right":"Leggera a destra{road}",
 "route_maneuver_sharp_left":"Forte a sinistra{road}","route_maneuver_sharp_right":"Forte a destra{road}",
 "route_maneuver_uturn":"Fai inversione a U{road}","route_maneuver_straight":"Continua dritto{road}",
 "route_maneuver_continue":"Continua{road}","route_maneuver_roundabout":"Entra nella rotonda{road}",
 "route_maneuver_roundabout_exit":"Esci dalla rotonda all'uscita {exit}{road}",
 "route_maneuver_merge":"Immettiti{road}","route_maneuver_on_ramp":"Entra nella rampa{road}",
 "route_maneuver_off_ramp":"Esci dalla rampa{road}",
 "route_error_no_route":"Nessun percorso trovato tra origine e destinazione.",
 "route_error_no_segment":"L'origine o la destinazione non è vicina a una rete stradale percorribile.",
 "route_error_too_big":"La richiesta di percorso è troppo grande.",
 "route_error_online_failed":"Il servizio di percorso online non ha potuto calcolare il percorso.",
 "route_error_offline_unavailable":"I percorsi online non sono disponibili in modalità offline.",
 "route_error_offline_not_found":"Nessun percorso trovato sulla mappa offline.",
 "route_error_online_not_found":"Nessun percorso trovato tra origine e destinazione.",
 "route_error_invalid_coordinates":"Le coordinate di origine o destinazione non sono valide.",
 "route_error_unreadable_response":"La risposta del servizio di percorso non è leggibile.",
 "route_error_invalid_geometry":"La geometria del percorso online è incompleta o non valida.",
 "route_error_invalid_response":"La risposta del percorso online ha un formato non valido.",
 "route_error_connection":"Impossibile connettersi al servizio di percorso online.",
 "route_error_unexpected":"Si è verificato un errore imprevisto durante il percorso online.",
 "route_error_http":"Il servizio di percorso online ha restituito una risposta non valida ({code}).",
 "route_error_timeout":"Timeout della risposta del percorso online. Controlla la connessione internet.",
 "route_error_offline_map_missing":"Installa una mappa ABM offline prima del percorso.",
 "route_error_offline_generic":"Errore nel percorso offline ABTINMAP: {error}",
 "route_error_offline_alternatives":"Creazione dei percorsi alternativi offline ABTINMAP non riuscita: {error}",
 "route_error_online_failed_generic":"Il percorso online non è riuscito.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} h {minutes} min",
 "route_no_destination":"Nessuna destinazione selezionata",
 "route_open_map_destination":"Premi a lungo la mappa per scegliere una destinazione.",
 "route_destination_ready":"La destinazione è pronta per la navigazione",
 "route_location_unavailable":"Posizione attuale non disponibile","route_location_ready":"Posizione attuale pronta",
 "route_check_gps":"Controlla il permesso di posizione e il GPS.",
 "route_accuracy":"Precisione della posizione: {value} m",
 "route_select_destination":"Seleziona destinazione","route_change_destination":"Cambia destinazione",
 "route_suggested_routes":"Percorsi suggeriti","route_calculation_failed":"Calcolo del percorso non riuscito: {error}",
 "route_download_offline_map":"Scarica la mappa della regione per il percorso offline.",
 "route_online_not_found_check_internet":"Percorso online non trovato; controlla la connessione internet.",
 "route_set_location_destination_hint":"Imposta posizione e destinazione per vedere le opzioni di percorso qui.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Arrivo","route_remaining":"Rimanente",
 "route_time":"Tempo","route_preview_instruction":"Svolta a destra su Via Valiasr",
 "route_selected":"Percorso selezionato","route_numbered":"Percorso {value}",
 "alert_speed_camera":"Autovelox","alert_speed_bump":"Dosso di rallentamento","alert_police":"Posto di blocco",
 "alert_traffic_light":"Semaforo","abtin_maps_user":"Utente Abtin Maps","as_palette_title":"Palette colori",
 "as_display_mode_subtitle":"Scegli la modalità giorno o notte",
 "as_weather_widget_subtitle":"Impostazioni di visualizzazione del widget meteo sulla mappa",
}

T["ja"] = {
 "ai_dashcam_title":"スマートカメラ","ai_dashcam_desc":"ビデオ録画とスマート運転アシスト",
 "dashcam_video_size":"動画サイズ","dashcam_video_size_unlimited":"∞分",
 "dashcam_video_size_value":"{value}分（{size}GB）","dashcam_driver_assistance":"スマート運転アシスト",
 "dashcam_fixed_camera_height":"カメラ固定高さ","dashcam_camera_height":"カメラの高さ",
 "dashcam_vehicle_width":"車両幅","dashcam_camera_lateral_displacement":"カメラの横方向オフセット",
 "dashcam_forward_collision":"前方衝突","dashcam_dangerous_headway":"前方車両との危険な車間距離",
 "dashcam_stop_and_go":"ストップアンドゴー","dashcam_lane_departure_solid":"車線逸脱（実線）",
 "dashcam_lane_departure_dashed":"車線逸脱（破線）","dashcam_traffic_sign_recognition":"交通標識認識",
 "hud_title":"ヘッドアップディスプレイ（HUD）","hud_menu_desc":"フロントガラスに経路情報を表示",
 "hud_enable":"HUDを有効化","hud_enable_desc":"フロントガラスに経路情報を表示",
 "hud_brightness":"画面の明るさ","hud_mirror":"鏡像","hud_mirror_desc":"ガラスに正しく表示するため",
 "hud_scale":"表示スケール","hud_position":"ガラス上の表示位置",
 "hud_position_desc":"フロントガラス上のHUDの全体的な配置","hud_visible_info":"表示可能な情報",
 "hud_info_speed":"速度","hud_info_speed_limit":"制限速度","hud_info_maneuver":"経路と次の曲がり角",
 "hud_info_distance":"曲がり角までの距離","hud_info_heading":"方位（コンパス）","hud_info_route_alerts":"経路アラート",
 "hud_info_ai_alerts":"AIアラート","hud_info_other":"その他の情報","hud_preview":"プレビュー",
 "hud_note":"注：視認性を高めるため、暗い環境でHUDを使用してください。",
 "hud_launch":"HUDを起動","hud_no_active_navigation":"HUDを使用するにはナビゲーションを開始してください","hud_arrived":"目的地に到着しました",
 "dashcam_level_off":"オフ","dashcam_level_low":"低","dashcam_level_normal":"標準","dashcam_level_high":"高",
 "dashcam_meters_short":"m","delete_language_package_title":"言語パックを削除",
 "delete_language_package_confirm":"パック「{name}」を削除しますか？","start_button":"開始",
 "route_road_prefix":"{road}へ","route_maneuver_depart":"走行を開始{road}","route_maneuver_arrive":"目的地に到着しました",
 "route_maneuver_turn_left":"左折{road}","route_maneuver_turn_right":"右折{road}",
 "route_maneuver_slight_left":"左へわずかに{road}","route_maneuver_slight_right":"右へわずかに{road}",
 "route_maneuver_sharp_left":"左へ急に{road}","route_maneuver_sharp_right":"右へ急に{road}",
 "route_maneuver_uturn":"Uターン{road}","route_maneuver_straight":"直進{road}",
 "route_maneuver_continue":"続行{road}","route_maneuver_roundabout":"ラウンドアバウトに入る{road}",
 "route_maneuver_roundabout_exit":"ラウンドアバウトを{exit}番出口で出る{road}",
 "route_maneuver_merge":"合流{road}","route_maneuver_on_ramp":"入口ランプへ{road}",
 "route_maneuver_off_ramp":"出口ランプから出る{road}",
 "route_error_no_route":"出発地と目的地の間の経路が見つかりませんでした。",
 "route_error_no_segment":"出発地または目的地が通行可能な道路網の近くにありません。",
 "route_error_too_big":"経路リクエストが大きすぎます。",
 "route_error_online_failed":"オンライン経路サービスが経路を計算できませんでした。",
 "route_error_offline_unavailable":"オフラインモードではオンライン経路は利用できません。",
 "route_error_offline_not_found":"オフラインマップに経路が見つかりませんでした。",
 "route_error_online_not_found":"出発地と目的地の間の経路が見つかりませんでした。",
 "route_error_invalid_coordinates":"出発地または目的地の座標が無効です。",
 "route_error_unreadable_response":"経路サービスの応答を読み取れません。",
 "route_error_invalid_geometry":"オンライン経路のジオメトリが不完全または無効です。",
 "route_error_invalid_response":"オンライン経路の応答形式が無効です。",
 "route_error_connection":"オンライン経路サービスに接続できませんでした。",
 "route_error_unexpected":"オンライン経路計算中に予期しないエラーが発生しました。",
 "route_error_http":"オンライン経路サービスが無効な応答を返しました（{code}）。",
 "route_error_timeout":"オンライン経路の応答がタイムアウトしました。インターネット接続を確認してください。",
 "route_error_offline_map_missing":"経路計算の前にオフラインABMマップをインストールしてください。",
 "route_error_offline_generic":"ABTINMAPオフライン経路計算エラー：{error}",
 "route_error_offline_alternatives":"ABTINMAPオフライン代替経路の作成に失敗：{error}",
 "route_error_online_failed_generic":"オンライン経路計算に失敗しました。",
 "route_duration_minutes":"{value}分","route_duration_hours_minutes":"{hours}時間{minutes}分",
 "route_no_destination":"目的地が選択されていません",
 "route_open_map_destination":"目的地を選ぶにはマップを長押ししてください。",
 "route_destination_ready":"目的地はナビゲーションの準備ができています",
 "route_location_unavailable":"現在地を取得できません","route_location_ready":"現在地の準備ができました",
 "route_check_gps":"位置情報の許可とGPSを確認してください。",
 "route_accuracy":"位置精度：{value}m",
 "route_select_destination":"目的地を選択","route_change_destination":"目的地を変更",
 "route_suggested_routes":"推奨経路","route_calculation_failed":"経路計算に失敗しました：{error}",
 "route_download_offline_map":"オフライン経路のために地域マップをダウンロードしてください。",
 "route_online_not_found_check_internet":"オンライン経路が見つかりません。インターネット接続を確認してください。",
 "route_set_location_destination_hint":"位置と目的地を設定すると、ここに経路オプションが表示されます。",
 "route_distance_km":"{value}km","route_distance_m":"{value}m","route_eta":"到着","route_remaining":"残り",
 "route_time":"時間","route_preview_instruction":"右折してヴァリアスル通りへ",
 "route_selected":"選択した経路","route_numbered":"経路{value}",
 "alert_speed_camera":"速度取締カメラ","alert_speed_bump":"段差","alert_police":"交通警察",
 "alert_traffic_light":"信号機","abtin_maps_user":"Abtin Mapsユーザー","as_palette_title":"カラーパレット",
 "as_display_mode_subtitle":"昼モードまたは夜モードを選択",
 "as_weather_widget_subtitle":"マップ上の天気ウィジェット表示設定",
}

T["ko"] = {
 "ai_dashcam_title":"스마트 카메라","ai_dashcam_desc":"비디오 녹화 및 스마트 운전 보조",
 "dashcam_video_size":"비디오 크기","dashcam_video_size_unlimited":"∞분",
 "dashcam_video_size_value":"{value}분 ({size}GB)","dashcam_driver_assistance":"스마트 운전 보조",
 "dashcam_fixed_camera_height":"고정 카메라 높이","dashcam_camera_height":"카메라 높이",
 "dashcam_vehicle_width":"차량 폭","dashcam_camera_lateral_displacement":"카메라 측면 변위",
 "dashcam_forward_collision":"정면 충돌","dashcam_dangerous_headway":"전방 차량과의 위험한 거리",
 "dashcam_stop_and_go":"정차 후 출발","dashcam_lane_departure_solid":"차선 이탈(실선)",
 "dashcam_lane_departure_dashed":"차선 이탈(점선)","dashcam_traffic_sign_recognition":"교통 표지판 인식",
 "hud_title":"헤드업 디스플레이(HUD)","hud_menu_desc":"앞유리에 경로 정보 표시",
 "hud_enable":"HUD 활성화","hud_enable_desc":"앞유리에 경로 정보 표시",
 "hud_brightness":"디스플레이 밝기","hud_mirror":"거울 이미지","hud_mirror_desc":"유리에 올바르게 표시하기 위해",
 "hud_scale":"표시 배율","hud_position":"유리 위 표시 위치",
 "hud_position_desc":"앞유리 위 HUD의 전체 배치","hud_visible_info":"표시 가능한 정보",
 "hud_info_speed":"속도","hud_info_speed_limit":"속도 제한","hud_info_maneuver":"경로 및 다음 회전",
 "hud_info_distance":"회전까지 거리","hud_info_heading":"방향(나침반)","hud_info_route_alerts":"경로 알림",
 "hud_info_ai_alerts":"AI 알림","hud_info_other":"기타 정보","hud_preview":"미리보기",
 "hud_note":"참고: 최상의 시인성을 위해 어두운 환경에서 HUD를 사용하세요.",
 "hud_launch":"HUD 실행","hud_no_active_navigation":"HUD를 사용하려면 내비게이션을 시작하세요","hud_arrived":"목적지에 도착했습니다",
 "dashcam_level_off":"끔","dashcam_level_low":"낮음","dashcam_level_normal":"보통","dashcam_level_high":"높음",
 "dashcam_meters_short":"m","delete_language_package_title":"언어 팩 삭제",
 "delete_language_package_confirm":"\"{name}\" 팩을 삭제할까요?","start_button":"시작",
 "route_road_prefix":"{road} 방면","route_maneuver_depart":"주행을 시작하세요{road}","route_maneuver_arrive":"목적지에 도착했습니다",
 "route_maneuver_turn_left":"좌회전{road}","route_maneuver_turn_right":"우회전{road}",
 "route_maneuver_slight_left":"약간 좌회전{road}","route_maneuver_slight_right":"약간 우회전{road}",
 "route_maneuver_sharp_left":"급좌회전{road}","route_maneuver_sharp_right":"급우회전{road}",
 "route_maneuver_uturn":"유턴{road}","route_maneuver_straight":"직진{road}",
 "route_maneuver_continue":"계속 진행{road}","route_maneuver_roundabout":"회전교차로 진입{road}",
 "route_maneuver_roundabout_exit":"회전교차로 {exit}번 출구로 나가기{road}",
 "route_maneuver_merge":"합류{road}","route_maneuver_on_ramp":"진입 램프로{road}",
 "route_maneuver_off_ramp":"출구 램프로 나가기{road}",
 "route_error_no_route":"출발지와 목적지 사이의 경로를 찾을 수 없습니다.",
 "route_error_no_segment":"출발지 또는 목적지가 주행 가능한 도로망 근처에 없습니다.",
 "route_error_too_big":"경로 요청이 너무 큽니다.",
 "route_error_online_failed":"온라인 경로 서비스가 경로를 계산하지 못했습니다.",
 "route_error_offline_unavailable":"오프라인 모드에서는 온라인 경로를 사용할 수 없습니다.",
 "route_error_offline_not_found":"오프라인 지도에서 경로를 찾을 수 없습니다.",
 "route_error_online_not_found":"출발지와 목적지 사이의 경로를 찾을 수 없습니다.",
 "route_error_invalid_coordinates":"출발지 또는 목적지 좌표가 유효하지 않습니다.",
 "route_error_unreadable_response":"경로 서비스 응답을 읽을 수 없습니다.",
 "route_error_invalid_geometry":"온라인 경로의 지오메트리가 불완전하거나 유효하지 않습니다.",
 "route_error_invalid_response":"온라인 경로 응답 형식이 유효하지 않습니다.",
 "route_error_connection":"온라인 경로 서비스에 연결할 수 없습니다.",
 "route_error_unexpected":"온라인 경로 계산 중 예기치 않은 오류가 발생했습니다.",
 "route_error_http":"온라인 경로 서비스가 유효하지 않은 응답을 반환했습니다({code}).",
 "route_error_timeout":"온라인 경로 응답 시간이 초과되었습니다. 인터넷 연결을 확인하세요.",
 "route_error_offline_map_missing":"경로 계산 전에 오프라인 ABM 지도를 설치하세요.",
 "route_error_offline_generic":"ABTINMAP 오프라인 경로 계산 오류: {error}",
 "route_error_offline_alternatives":"ABTINMAP 오프라인 대체 경로 생성 실패: {error}",
 "route_error_online_failed_generic":"온라인 경로 계산에 실패했습니다.",
 "route_duration_minutes":"{value}분","route_duration_hours_minutes":"{hours}시간 {minutes}분",
 "route_no_destination":"선택된 목적지가 없습니다",
 "route_open_map_destination":"목적지를 선택하려면 지도를 길게 누르세요.",
 "route_destination_ready":"목적지가 내비게이션 준비가 되었습니다",
 "route_location_unavailable":"현재 위치를 사용할 수 없습니다","route_location_ready":"현재 위치가 준비되었습니다",
 "route_check_gps":"위치 권한과 GPS를 확인하세요.",
 "route_accuracy":"위치 정확도: {value}m",
 "route_select_destination":"목적지 선택","route_change_destination":"목적지 변경",
 "route_suggested_routes":"추천 경로","route_calculation_failed":"경로 계산 실패: {error}",
 "route_download_offline_map":"오프라인 경로를 위해 지역 지도를 다운로드하세요.",
 "route_online_not_found_check_internet":"온라인 경로를 찾을 수 없습니다. 인터넷 연결을 확인하세요.",
 "route_set_location_destination_hint":"위치와 목적지를 설정하면 여기에 경로 옵션이 표시됩니다.",
 "route_distance_km":"{value}km","route_distance_m":"{value}m","route_eta":"도착","route_remaining":"남은 거리",
 "route_time":"시간","route_preview_instruction":"우회전하여 발리아스르 거리로",
 "route_selected":"선택된 경로","route_numbered":"경로 {value}",
 "alert_speed_camera":"과속 카메라","alert_speed_bump":"과속 방지턱","alert_police":"교통 경찰",
 "alert_traffic_light":"신호등","abtin_maps_user":"Abtin Maps 사용자","as_palette_title":"색상 팔레트",
 "as_display_mode_subtitle":"주간 또는 야간 모드 선택",
 "as_weather_widget_subtitle":"지도 위 날씨 위젯 표시 설정",
}

T["nl"] = {
 "ai_dashcam_title":"Slimme camera","ai_dashcam_desc":"Video-opname en slimme rijassistent",
 "dashcam_video_size":"Videogrootte","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Slimme rijassistent",
 "dashcam_fixed_camera_height":"Vaste camerah hoogte","dashcam_camera_height":"Camerahoogte",
 "dashcam_vehicle_width":"Voertuigbreedte","dashcam_camera_lateral_displacement":"Laterale verplaatsing van de camera",
 "dashcam_forward_collision":"Frontale botsing","dashcam_dangerous_headway":"Gevaarlijke afstand tot het voertuig voor u",
 "dashcam_stop_and_go":"Stop-and-go","dashcam_lane_departure_solid":"Rijstrookverlating (doorgetrokken lijn)",
 "dashcam_lane_departure_dashed":"Rijstrookverlating (onderbroken lijn)","dashcam_traffic_sign_recognition":"Herkenning van verkeersborden",
 "hud_title":"Head-up display (HUD)","hud_menu_desc":"Route-informatie weergeven op de voorruit",
 "hud_enable":"HUD inschakelen","hud_enable_desc":"Route-informatie weergeven op de voorruit",
 "hud_brightness":"Helderheid van het display","hud_mirror":"Spiegelbeeld","hud_mirror_desc":"Voor correcte weergave op het glas",
 "hud_scale":"Weergaveschaal","hud_position":"Positie op het glas",
 "hud_position_desc":"Algehele plaatsing van de HUD op de voorruit","hud_visible_info":"Weer te geven informatie",
 "hud_info_speed":"Snelheid","hud_info_speed_limit":"Snelheidslimiet","hud_info_maneuver":"Route en volgende bocht",
 "hud_info_distance":"Afstand tot bocht","hud_info_heading":"Richting (kompas)","hud_info_route_alerts":"Routewaarschuwingen",
 "hud_info_ai_alerts":"AI-waarschuwingen","hud_info_other":"Overige informatie","hud_preview":"Voorbeeld",
 "hud_note":"Opmerking: gebruik de HUD in een omgeving met weinig licht voor de beste zichtbaarheid.",
 "hud_launch":"HUD starten","hud_no_active_navigation":"Start navigatie om de HUD te gebruiken","hud_arrived":"U bent aangekomen",
 "dashcam_level_off":"Uit","dashcam_level_low":"Laag","dashcam_level_normal":"Normaal","dashcam_level_high":"Hoog",
 "dashcam_meters_short":"m","delete_language_package_title":"Taalpakket verwijderen",
 "delete_language_package_confirm":"Pakket \"{name}\" verwijderen?","start_button":"Start",
 "route_road_prefix":"naar {road}","route_maneuver_depart":"Begin met rijden{road}","route_maneuver_arrive":"U bent aangekomen",
 "route_maneuver_turn_left":"Sla linksaf{road}","route_maneuver_turn_right":"Sla rechtsaf{road}",
 "route_maneuver_slight_left":"Enigszins links{road}","route_maneuver_slight_right":"Enigszins rechts{road}",
 "route_maneuver_sharp_left":"Scherp links{road}","route_maneuver_sharp_right":"Scherp rechts{road}",
 "route_maneuver_uturn":"Keer om{road}","route_maneuver_straight":"Ga rechtdoor{road}",
 "route_maneuver_continue":"Ga verder{road}","route_maneuver_roundabout":"Rij de rotonde op{road}",
 "route_maneuver_roundabout_exit":"Verlaat de rotonde bij afslag {exit}{road}",
 "route_maneuver_merge":"Voeg in{road}","route_maneuver_on_ramp":"Rij de oprit op{road}",
 "route_maneuver_off_ramp":"Rij de afrit af{road}",
 "route_error_no_route":"Geen route gevonden tussen vertrekpunt en bestemming.",
 "route_error_no_segment":"Het vertrekpunt of de bestemming ligt niet nabij een berijdbaar wegennet.",
 "route_error_too_big":"Het routeverzoek is te groot.",
 "route_error_online_failed":"De online routedienst kon de route niet berekenen.",
 "route_error_offline_unavailable":"Online routes zijn niet beschikbaar in offline modus.",
 "route_error_offline_not_found":"Geen route gevonden op de offline kaart.",
 "route_error_online_not_found":"Geen route gevonden tussen vertrekpunt en bestemming.",
 "route_error_invalid_coordinates":"De coördinaten van vertrekpunt of bestemming zijn ongeldig.",
 "route_error_unreadable_response":"De reactie van de routedienst kan niet worden gelezen.",
 "route_error_invalid_geometry":"De geometrie van de online route is onvolledig of ongeldig.",
 "route_error_invalid_response":"De online routerespons heeft een ongeldig formaat.",
 "route_error_connection":"Kan geen verbinding maken met de online routedienst.",
 "route_error_unexpected":"Er is een onverwachte fout opgetreden tijdens online routering.",
 "route_error_http":"De online routedienst gaf een ongeldige reactie ({code}).",
 "route_error_timeout":"De online routerespons is verlopen. Controleer uw internetverbinding.",
 "route_error_offline_map_missing":"Installeer eerst een offline ABM-kaart voor routering.",
 "route_error_offline_generic":"Fout bij offline routering ABTINMAP: {error}",
 "route_error_offline_alternatives":"Aanmaken van offline alternatieve routes ABTINMAP mislukt: {error}",
 "route_error_online_failed_generic":"Online routering is mislukt.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} u {minutes} min",
 "route_no_destination":"Geen bestemming geselecteerd",
 "route_open_map_destination":"Houd de kaart ingedrukt om een bestemming te kiezen.",
 "route_destination_ready":"Bestemming is klaar voor navigatie",
 "route_location_unavailable":"Huidige locatie niet beschikbaar","route_location_ready":"Huidige locatie is klaar",
 "route_check_gps":"Controleer de locatiemachtiging en GPS.",
 "route_accuracy":"Locatienauwkeurigheid: {value} m",
 "route_select_destination":"Bestemming selecteren","route_change_destination":"Bestemming wijzigen",
 "route_suggested_routes":"Voorgestelde routes","route_calculation_failed":"Routeberekening mislukt: {error}",
 "route_download_offline_map":"Download de kaart van de regio voor offline routering.",
 "route_online_not_found_check_internet":"Online route niet gevonden; controleer uw internetverbinding.",
 "route_set_location_destination_hint":"Stel locatie en bestemming in om hier routeopties te zien.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Aankomst","route_remaining":"Resterend",
 "route_time":"Tijd","route_preview_instruction":"Sla rechtsaf de Valiasr-straat in",
 "route_selected":"Geselecteerde route","route_numbered":"Route {value}",
 "alert_speed_camera":"Snelheidscamera","alert_speed_bump":"Snelheidsdrempel","alert_police":"Verkeerscontrole",
 "alert_traffic_light":"Verkeerslicht","abtin_maps_user":"Abtin Maps-gebruiker","as_palette_title":"Kleurenpalet",
 "as_display_mode_subtitle":"Kies dag- of nachtmodus",
 "as_weather_widget_subtitle":"Weergave-instellingen van de weerwidget op de kaart",
}

T["no"] = {
 "ai_dashcam_title":"Smartkamera","ai_dashcam_desc":"Videoopptak og smart kjøreassistent",
 "dashcam_video_size":"Videostørrelse","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Smart kjøreassistent",
 "dashcam_fixed_camera_height":"Fast kamerahøyde","dashcam_camera_height":"Kamerahøyde",
 "dashcam_vehicle_width":"Kjøretøyets bredde","dashcam_camera_lateral_displacement":"Kameraets sideforskyvning",
 "dashcam_forward_collision":"Frontkollisjon","dashcam_dangerous_headway":"Farlig avstand til kjøretøyet foran",
 "dashcam_stop_and_go":"Stopp og kjør","dashcam_lane_departure_solid":"Filskifte (heltrukket linje)",
 "dashcam_lane_departure_dashed":"Filskifte (stiplet linje)","dashcam_traffic_sign_recognition":"Gjenkjenning av trafikkskilt",
 "hud_title":"Head-up-display (HUD)","hud_menu_desc":"Vis ruteinformasjon på frontruten",
 "hud_enable":"Aktiver HUD","hud_enable_desc":"Vis ruteinformasjon på frontruten",
 "hud_brightness":"Skjermlysstyrke","hud_mirror":"Speilbilde","hud_mirror_desc":"For riktig visning på glasset",
 "hud_scale":"Visningsskala","hud_position":"Plassering på glasset",
 "hud_position_desc":"Samlet plassering av HUD på frontruten","hud_visible_info":"Visbar informasjon",
 "hud_info_speed":"Fart","hud_info_speed_limit":"Fartsgrense","hud_info_maneuver":"Rute og neste sving",
 "hud_info_distance":"Avstand til sving","hud_info_heading":"Retning (kompass)","hud_info_route_alerts":"Rutevarsler",
 "hud_info_ai_alerts":"AI-varsler","hud_info_other":"Annen informasjon","hud_preview":"Forhåndsvisning",
 "hud_note":"Merk: Bruk HUD i omgivelser med lite lys for best synlighet.",
 "hud_launch":"Start HUD","hud_no_active_navigation":"Start navigasjon for å bruke HUD","hud_arrived":"Du har ankommet",
 "dashcam_level_off":"Av","dashcam_level_low":"Lav","dashcam_level_normal":"Normal","dashcam_level_high":"Høy",
 "dashcam_meters_short":"m","delete_language_package_title":"Slett språkpakke",
 "delete_language_package_confirm":"Slette pakken \"{name}\"?","start_button":"Start",
 "route_road_prefix":"til {road}","route_maneuver_depart":"Begynn å kjøre{road}","route_maneuver_arrive":"Du har ankommet",
 "route_maneuver_turn_left":"Sving til venstre{road}","route_maneuver_turn_right":"Sving til høyre{road}",
 "route_maneuver_slight_left":"Sving litt til venstre{road}","route_maneuver_slight_right":"Sving litt til høyre{road}",
 "route_maneuver_sharp_left":"Sving skarpt til venstre{road}","route_maneuver_sharp_right":"Sving skarpt til høyre{road}",
 "route_maneuver_uturn":"Snu{road}","route_maneuver_straight":"Fortsett rett frem{road}",
 "route_maneuver_continue":"Fortsett{road}","route_maneuver_roundabout":"Kjør inn i rundkjøringen{road}",
 "route_maneuver_roundabout_exit":"Forlat rundkjøringen ved avkjøring {exit}{road}",
 "route_maneuver_merge":"Flett inn{road}","route_maneuver_on_ramp":"Kjør inn på påkjøringsrampen{road}",
 "route_maneuver_off_ramp":"Kjør ut av avkjøringsrampen{road}",
 "route_error_no_route":"Fant ingen rute mellom start og destinasjon.",
 "route_error_no_segment":"Start eller destinasjon er ikke nær et kjørbart veinett.",
 "route_error_too_big":"Ruteforespørselen er for stor.",
 "route_error_online_failed":"Den elektroniske rutetjenesten kunne ikke beregne ruten.",
 "route_error_offline_unavailable":"Elektroniske ruter er ikke tilgjengelige i frakoblet modus.",
 "route_error_offline_not_found":"Fant ingen rute på frakoblet kart.",
 "route_error_online_not_found":"Fant ingen rute mellom start og destinasjon.",
 "route_error_invalid_coordinates":"Koordinatene for start eller destinasjon er ugyldige.",
 "route_error_unreadable_response":"Svaret fra rutetjenesten kan ikke leses.",
 "route_error_invalid_geometry":"Geometrien til den elektroniske ruten er ufullstendig eller ugyldig.",
 "route_error_invalid_response":"Svaret fra elektronisk rute har et ugyldig format.",
 "route_error_connection":"Kunne ikke koble til den elektroniske rutetjenesten.",
 "route_error_unexpected":"Det oppstod en uventet feil under elektronisk ruting.",
 "route_error_http":"Den elektroniske rutetjenesten returnerte et ugyldig svar ({code}).",
 "route_error_timeout":"Tidsavbrudd for elektronisk rutesvar. Sjekk internettforbindelsen.",
 "route_error_offline_map_missing":"Installer et frakoblet ABM-kart før ruting.",
 "route_error_offline_generic":"Feil i frakoblet ruting ABTINMAP: {error}",
 "route_error_offline_alternatives":"Kunne ikke opprette frakoblede alternative ruter ABTINMAP: {error}",
 "route_error_online_failed_generic":"Elektronisk ruting mislyktes.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} t {minutes} min",
 "route_no_destination":"Ingen destinasjon valgt",
 "route_open_map_destination":"Hold kartet inne for å velge en destinasjon.",
 "route_destination_ready":"Destinasjonen er klar for navigasjon",
 "route_location_unavailable":"Gjeldende posisjon er ikke tilgjengelig","route_location_ready":"Gjeldende posisjon er klar",
 "route_check_gps":"Sjekk posisjonstillatelse og GPS.",
 "route_accuracy":"Posisjonsnøyaktighet: {value} m",
 "route_select_destination":"Velg destinasjon","route_change_destination":"Endre destinasjon",
 "route_suggested_routes":"Foreslåtte ruter","route_calculation_failed":"Ruteberegning mislyktes: {error}",
 "route_download_offline_map":"Last ned kartet over regionen for frakoblet ruting.",
 "route_online_not_found_check_internet":"Elektronisk rute ikke funnet; sjekk internettforbindelsen.",
 "route_set_location_destination_hint":"Angi posisjon og destinasjon for å se rutealternativer her.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Ankomst","route_remaining":"Gjenstår",
 "route_time":"Tid","route_preview_instruction":"Sving til høyre inn på Valiasr-gaten",
 "route_selected":"Valgt rute","route_numbered":"Rute {value}",
 "alert_speed_camera":"Fartskamera","alert_speed_bump":"Fartsdump","alert_police":"Trafikkontroll",
 "alert_traffic_light":"Trafikklys","abtin_maps_user":"Abtin Maps-bruker","as_palette_title":"Fargepalett",
 "as_display_mode_subtitle":"Velg dag- eller nattmodus",
 "as_weather_widget_subtitle":"Visningsinnstillinger for værwidget på kartet",
}

T["pl"] = {
 "ai_dashcam_title":"Inteligentna kamera","ai_dashcam_desc":"Nagrywanie wideo i inteligentny asystent jazdy",
 "dashcam_video_size":"Rozmiar wideo","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Inteligentny asystent jazdy",
 "dashcam_fixed_camera_height":"Stała wysokość kamery","dashcam_camera_height":"Wysokość kamery",
 "dashcam_vehicle_width":"Szerokość pojazdu","dashcam_camera_lateral_displacement":"Boczne przesunięcie kamery",
 "dashcam_forward_collision":"Kolizja czołowa","dashcam_dangerous_headway":"Niebezpieczny odstęp od pojazdu z przodu",
 "dashcam_stop_and_go":"Stop and go","dashcam_lane_departure_solid":"Zjechanie z pasa (linia ciągła)",
 "dashcam_lane_departure_dashed":"Zjechanie z pasa (linia przerywana)","dashcam_traffic_sign_recognition":"Rozpoznawanie znaków drogowych",
 "hud_title":"Wyświetlacz przezierny (HUD)","hud_menu_desc":"Wyświetlaj informacje o trasie na przedniej szybie",
 "hud_enable":"Włącz HUD","hud_enable_desc":"Wyświetlaj informacje o trasie na przedniej szybie",
 "hud_brightness":"Jasność ekranu","hud_mirror":"Obraz lustrzany","hud_mirror_desc":"Dla prawidłowego wyświetlania na szybie",
 "hud_scale":"Skala wyświetlania","hud_position":"Pozycja na szybie",
 "hud_position_desc":"Ogólne rozmieszczenie HUD na przedniej szybie","hud_visible_info":"Informacje do wyświetlenia",
 "hud_info_speed":"Prędkość","hud_info_speed_limit":"Limit prędkości","hud_info_maneuver":"Trasa i następny zakręt",
 "hud_info_distance":"Odległość do zakrętu","hud_info_heading":"Kierunek (kompas)","hud_info_route_alerts":"Alerty trasy",
 "hud_info_ai_alerts":"Alerty AI","hud_info_other":"Inne informacje","hud_preview":"Podgląd",
 "hud_note":"Uwaga: dla najlepszej widoczności używaj HUD w środowisku o słabym oświetleniu.",
 "hud_launch":"Uruchom HUD","hud_no_active_navigation":"Uruchom nawigację, aby korzystać z HUD","hud_arrived":"Dotarłeś do celu",
 "dashcam_level_off":"Wył.","dashcam_level_low":"Niski","dashcam_level_normal":"Normalny","dashcam_level_high":"Wysoki",
 "dashcam_meters_short":"m","delete_language_package_title":"Usuń pakiet językowy",
 "delete_language_package_confirm":"Usunąć pakiet „{name}”?","start_button":"Start",
 "route_road_prefix":"na {road}","route_maneuver_depart":"Rozpocznij jazdę{road}","route_maneuver_arrive":"Dotarłeś do celu",
 "route_maneuver_turn_left":"Skręć w lewo{road}","route_maneuver_turn_right":"Skręć w prawo{road}",
 "route_maneuver_slight_left":"Łagodnie w lewo{road}","route_maneuver_slight_right":"Łagodnie w prawo{road}",
 "route_maneuver_sharp_left":"Ostro w lewo{road}","route_maneuver_sharp_right":"Ostro w prawo{road}",
 "route_maneuver_uturn":"Zawróć{road}","route_maneuver_straight":"Jedź prosto{road}",
 "route_maneuver_continue":"Kontynuuj{road}","route_maneuver_roundabout":"Wjedź na rondo{road}",
 "route_maneuver_roundabout_exit":"Zjedź z ronda zjazdem {exit}{road}",
 "route_maneuver_merge":"Włącz się do ruchu{road}","route_maneuver_on_ramp":"Wjedź na rampę wjazdową{road}",
 "route_maneuver_off_ramp":"Zjedź rampą zjazdową{road}",
 "route_error_no_route":"Nie znaleziono trasy między punktem początkowym a celem.",
 "route_error_no_segment":"Punkt początkowy lub cel nie znajduje się w pobliżu przejezdnej sieci drogowej.",
 "route_error_too_big":"Żądanie trasy jest zbyt duże.",
 "route_error_online_failed":"Internetowa usługa tras nie mogła obliczyć trasy.",
 "route_error_offline_unavailable":"Trasy online nie są dostępne w trybie offline.",
 "route_error_offline_not_found":"Nie znaleziono trasy na mapie offline.",
 "route_error_online_not_found":"Nie znaleziono trasy między punktem początkowym a celem.",
 "route_error_invalid_coordinates":"Współrzędne punktu początkowego lub celu są nieprawidłowe.",
 "route_error_unreadable_response":"Odpowiedź usługi tras jest nieczytelna.",
 "route_error_invalid_geometry":"Geometria trasy online jest niekompletna lub nieprawidłowa.",
 "route_error_invalid_response":"Odpowiedź trasy online ma nieprawidłowy format.",
 "route_error_connection":"Nie można połączyć się z internetową usługą tras.",
 "route_error_unexpected":"Wystąpił nieoczekiwany błąd podczas wyznaczania trasy online.",
 "route_error_http":"Internetowa usługa tras zwróciła nieprawidłową odpowiedź ({code}).",
 "route_error_timeout":"Przekroczono czas odpowiedzi trasy online. Sprawdź połączenie internetowe.",
 "route_error_offline_map_missing":"Zainstaluj mapę ABM offline przed wyznaczaniem trasy.",
 "route_error_offline_generic":"Błąd wyznaczania trasy offline ABTINMAP: {error}",
 "route_error_offline_alternatives":"Nie udało się utworzyć alternatywnych tras offline ABTINMAP: {error}",
 "route_error_online_failed_generic":"Wyznaczanie trasy online nie powiodło się.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} godz {minutes} min",
 "route_no_destination":"Nie wybrano celu",
 "route_open_map_destination":"Przytrzymaj mapę, aby wybrać cel.",
 "route_destination_ready":"Cel jest gotowy do nawigacji",
 "route_location_unavailable":"Bieżąca lokalizacja jest niedostępna","route_location_ready":"Bieżąca lokalizacja jest gotowa",
 "route_check_gps":"Sprawdź uprawnienia do lokalizacji i GPS.",
 "route_accuracy":"Dokładność lokalizacji: {value} m",
 "route_select_destination":"Wybierz cel","route_change_destination":"Zmień cel",
 "route_suggested_routes":"Sugerowane trasy","route_calculation_failed":"Obliczanie trasy nie powiodło się: {error}",
 "route_download_offline_map":"Pobierz mapę regionu do wyznaczania tras offline.",
 "route_online_not_found_check_internet":"Nie znaleziono trasy online; sprawdź połączenie internetowe.",
 "route_set_location_destination_hint":"Ustaw lokalizację i cel, aby zobaczyć opcje trasy tutaj.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Przyjazd","route_remaining":"Pozostało",
 "route_time":"Czas","route_preview_instruction":"Skręć w prawo w ulicę Valiasr",
 "route_selected":"Wybrana trasa","route_numbered":"Trasa {value}",
 "alert_speed_camera":"Fotoradar","alert_speed_bump":"Próg zwalniający","alert_police":"Kontrola drogowa",
 "alert_traffic_light":"Sygnalizacja świetlna","abtin_maps_user":"Użytkownik Abtin Maps","as_palette_title":"Paleta kolorów",
 "as_display_mode_subtitle":"Wybierz tryb dzienny lub nocny",
 "as_weather_widget_subtitle":"Ustawienia wyświetlania widgetu pogody na mapie",
}

T["pt"] = {
 "ai_dashcam_title":"Câmera inteligente","ai_dashcam_desc":"Gravação de vídeo e assistente inteligente de direção",
 "dashcam_video_size":"Tamanho do vídeo","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Assistente inteligente de direção",
 "dashcam_fixed_camera_height":"Altura fixa da câmera","dashcam_camera_height":"Altura da câmera",
 "dashcam_vehicle_width":"Largura do veículo","dashcam_camera_lateral_displacement":"Deslocamento lateral da câmera",
 "dashcam_forward_collision":"Colisão frontal","dashcam_dangerous_headway":"Distância perigosa do veículo à frente",
 "dashcam_stop_and_go":"Pare e siga","dashcam_lane_departure_solid":"Saída de faixa (linha contínua)",
 "dashcam_lane_departure_dashed":"Saída de faixa (linha tracejada)","dashcam_traffic_sign_recognition":"Reconhecimento de placas de trânsito",
 "hud_title":"Display head-up (HUD)","hud_menu_desc":"Mostrar informações da rota no para-brisa",
 "hud_enable":"Ativar HUD","hud_enable_desc":"Mostrar informações da rota no para-brisa",
 "hud_brightness":"Brilho da tela","hud_mirror":"Imagem espelhada","hud_mirror_desc":"Para exibição correta no vidro",
 "hud_scale":"Escala de exibição","hud_position":"Posição no vidro",
 "hud_position_desc":"Posicionamento geral do HUD no para-brisa","hud_visible_info":"Informações exibíveis",
 "hud_info_speed":"Velocidade","hud_info_speed_limit":"Limite de velocidade","hud_info_maneuver":"Rota e próxima curva",
 "hud_info_distance":"Distância até a curva","hud_info_heading":"Direção (bússola)","hud_info_route_alerts":"Alertas de rota",
 "hud_info_ai_alerts":"Alertas de IA","hud_info_other":"Outras informações","hud_preview":"Pré-visualização",
 "hud_note":"Nota: para melhor visibilidade, use o HUD em ambiente com pouca luz.",
 "hud_launch":"Iniciar HUD","hud_no_active_navigation":"Inicie a navegação para usar o HUD","hud_arrived":"Você chegou ao destino",
 "dashcam_level_off":"Desligado","dashcam_level_low":"Baixo","dashcam_level_normal":"Normal","dashcam_level_high":"Alto",
 "dashcam_meters_short":"m","delete_language_package_title":"Excluir pacote de idioma",
 "delete_language_package_confirm":"Excluir o pacote \"{name}\"?","start_button":"Iniciar",
 "route_road_prefix":"em {road}","route_maneuver_depart":"Comece a dirigir{road}","route_maneuver_arrive":"Você chegou ao destino",
 "route_maneuver_turn_left":"Vire à esquerda{road}","route_maneuver_turn_right":"Vire à direita{road}",
 "route_maneuver_slight_left":"Vire levemente à esquerda{road}","route_maneuver_slight_right":"Vire levemente à direita{road}",
 "route_maneuver_sharp_left":"Vire acentuadamente à esquerda{road}","route_maneuver_sharp_right":"Vire acentuadamente à direita{road}",
 "route_maneuver_uturn":"Faça retorno{road}","route_maneuver_straight":"Siga em frente{road}",
 "route_maneuver_continue":"Continue{road}","route_maneuver_roundabout":"Entre na rotatória{road}",
 "route_maneuver_roundabout_exit":"Saia da rotatória na saída {exit}{road}",
 "route_maneuver_merge":"Entre no fluxo{road}","route_maneuver_on_ramp":"Entre na rampa de acesso{road}",
 "route_maneuver_off_ramp":"Saia pela rampa de saída{road}",
 "route_error_no_route":"Nenhuma rota encontrada entre a origem e o destino.",
 "route_error_no_segment":"A origem ou o destino não está perto de uma rede viária navegável.",
 "route_error_too_big":"A solicitação de rota é muito grande.",
 "route_error_online_failed":"O serviço de rota online não conseguiu calcular a rota.",
 "route_error_offline_unavailable":"Rotas online não estão disponíveis no modo offline.",
 "route_error_offline_not_found":"Nenhuma rota encontrada no mapa offline.",
 "route_error_online_not_found":"Nenhuma rota encontrada entre a origem e o destino.",
 "route_error_invalid_coordinates":"As coordenadas da origem ou do destino são inválidas.",
 "route_error_unreadable_response":"A resposta do serviço de rota não pode ser lida.",
 "route_error_invalid_geometry":"A geometria da rota online está incompleta ou inválida.",
 "route_error_invalid_response":"A resposta da rota online tem formato inválido.",
 "route_error_connection":"Não foi possível conectar ao serviço de rota online.",
 "route_error_unexpected":"Ocorreu um erro inesperado durante o roteamento online.",
 "route_error_http":"O serviço de rota online retornou uma resposta inválida ({code}).",
 "route_error_timeout":"Tempo esgotado na resposta da rota online. Verifique sua conexão com a internet.",
 "route_error_offline_map_missing":"Instale um mapa ABM offline antes de rotear.",
 "route_error_offline_generic":"Erro no roteamento offline ABTINMAP: {error}",
 "route_error_offline_alternatives":"Falha ao criar rotas alternativas offline ABTINMAP: {error}",
 "route_error_online_failed_generic":"O roteamento online falhou.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} h {minutes} min",
 "route_no_destination":"Nenhum destino selecionado",
 "route_open_map_destination":"Mantenha pressionado o mapa para escolher um destino.",
 "route_destination_ready":"O destino está pronto para navegação",
 "route_location_unavailable":"Localização atual indisponível","route_location_ready":"Localização atual pronta",
 "route_check_gps":"Verifique a permissão de localização e o GPS.",
 "route_accuracy":"Precisão da localização: {value} m",
 "route_select_destination":"Selecionar destino","route_change_destination":"Alterar destino",
 "route_suggested_routes":"Rotas sugeridas","route_calculation_failed":"Falha no cálculo da rota: {error}",
 "route_download_offline_map":"Baixe o mapa da região para roteamento offline.",
 "route_online_not_found_check_internet":"Rota online não encontrada; verifique sua conexão com a internet.",
 "route_set_location_destination_hint":"Defina localização e destino para ver as opções de rota aqui.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Chegada","route_remaining":"Restante",
 "route_time":"Tempo","route_preview_instruction":"Vire à direita na rua Valiasr",
 "route_selected":"Rota selecionada","route_numbered":"Rota {value}",
 "alert_speed_camera":"Radar de velocidade","alert_speed_bump":"Lombada","alert_police":"Blitz de trânsito",
 "alert_traffic_light":"Semáforo","abtin_maps_user":"Usuário do Abtin Maps","as_palette_title":"Paleta de cores",
 "as_display_mode_subtitle":"Escolha o modo diurno ou noturno",
 "as_weather_widget_subtitle":"Configurações de exibição do widget de clima no mapa",
}
