# -*- coding: utf-8 -*-
# Translations of the 116 new keys — group C: ro, ru, sv, th, tr, uk, ur, vi, zh
T = {}

T["ro"] = {
 "ai_dashcam_title":"Cameră inteligentă","ai_dashcam_desc":"Înregistrare video și asistent inteligent de conducere",
 "dashcam_video_size":"Dimensiune video","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Asistent inteligent de conducere",
 "dashcam_fixed_camera_height":"Înălțime fixă a camerei","dashcam_camera_height":"Înălțimea camerei",
 "dashcam_vehicle_width":"Lățimea vehiculului","dashcam_camera_lateral_displacement":"Deplasarea laterală a camerei",
 "dashcam_forward_collision":"Coliziune frontală","dashcam_dangerous_headway":"Distanță periculoasă față de vehiculul din față",
 "dashcam_stop_and_go":"Oprește și pornește","dashcam_lane_departure_solid":"Ieșire din bandă (linie continuă)",
 "dashcam_lane_departure_dashed":"Ieșire din bandă (linie discontinuă)","dashcam_traffic_sign_recognition":"Recunoașterea indicatoarelor rutiere",
 "hud_title":"Display head-up (HUD)","hud_menu_desc":"Afișează informațiile rutei pe parbriz",
 "hud_enable":"Activează HUD","hud_enable_desc":"Afișează informațiile rutei pe parbriz",
 "hud_brightness":"Luminozitatea ecranului","hud_mirror":"Imagine în oglindă","hud_mirror_desc":"Pentru afișarea corectă pe sticlă",
 "hud_scale":"Scala de afișare","hud_position":"Poziția pe sticlă",
 "hud_position_desc":"Amplasarea generală a HUD pe parbriz","hud_visible_info":"Informații afișabile",
 "hud_info_speed":"Viteză","hud_info_speed_limit":"Limită de viteză","hud_info_maneuver":"Ruta și următoarea curbă",
 "hud_info_distance":"Distanța până la curbă","hud_info_heading":"Direcție (busolă)","hud_info_route_alerts":"Alerte de rută",
 "hud_info_ai_alerts":"Alerte AI","hud_info_other":"Alte informații","hud_preview":"Previzualizare",
 "hud_note":"Notă: pentru vizibilitate optimă, folosiți HUD într-un mediu cu lumină scăzută.",
 "hud_launch":"Lansează HUD","hud_no_active_navigation":"Porniți navigația pentru a folosi HUD","hud_arrived":"Ați ajuns la destinație",
 "dashcam_level_off":"Oprit","dashcam_level_low":"Scăzut","dashcam_level_normal":"Normal","dashcam_level_high":"Ridicat",
 "dashcam_meters_short":"m","delete_language_package_title":"Șterge pachetul de limbă",
 "delete_language_package_confirm":"Ștergem pachetul „{name}”?","start_button":"Start",
 "route_road_prefix":"spre {road}","route_maneuver_depart":"Începeți să conduceți{road}","route_maneuver_arrive":"Ați ajuns la destinație",
 "route_maneuver_turn_left":"Virați la stânga{road}","route_maneuver_turn_right":"Virați la dreapta{road}",
 "route_maneuver_slight_left":"Virați ușor la stânga{road}","route_maneuver_slight_right":"Virați ușor la dreapta{road}",
 "route_maneuver_sharp_left":"Virați brusc la stânga{road}","route_maneuver_sharp_right":"Virați brusc la dreapta{road}",
 "route_maneuver_uturn":"Întoarceți-vă{road}","route_maneuver_straight":"Continuați drept{road}",
 "route_maneuver_continue":"Continuați{road}","route_maneuver_roundabout":"Intrați în sensul giratoriu{road}",
 "route_maneuver_roundabout_exit":"Ieșiți din sensul giratoriu la ieșirea {exit}{road}",
 "route_maneuver_merge":"Integrați-vă{road}","route_maneuver_on_ramp":"Intrați pe rampa de acces{road}",
 "route_maneuver_off_ramp":"Ieșiți pe rampa de ieșire{road}",
 "route_error_no_route":"Nu a fost găsită nicio rută între punctul de plecare și destinație.",
 "route_error_no_segment":"Punctul de plecare sau destinația nu este aproape de o rețea rutieră navigabilă.",
 "route_error_too_big":"Solicitarea de rută este prea mare.",
 "route_error_online_failed":"Serviciul de rute online nu a putut calcula ruta.",
 "route_error_offline_unavailable":"Rutele online nu sunt disponibile în modul offline.",
 "route_error_offline_not_found":"Nu a fost găsită nicio rută pe harta offline.",
 "route_error_online_not_found":"Nu a fost găsită nicio rută între punctul de plecare și destinație.",
 "route_error_invalid_coordinates":"Coordonatele punctului de plecare sau ale destinației sunt invalide.",
 "route_error_unreadable_response":"Răspunsul serviciului de rute nu poate fi citit.",
 "route_error_invalid_geometry":"Geometria rutei online este incompletă sau invalidă.",
 "route_error_invalid_response":"Răspunsul rutei online are un format invalid.",
 "route_error_connection":"Nu s-a putut conecta la serviciul de rute online.",
 "route_error_unexpected":"A apărut o eroare neașteptată în timpul rutării online.",
 "route_error_http":"Serviciul de rute online a returnat un răspuns invalid ({code}).",
 "route_error_timeout":"Răspunsul rutei online a expirat. Verificați conexiunea la internet.",
 "route_error_offline_map_missing":"Instalați o hartă ABM offline înainte de rutare.",
 "route_error_offline_generic":"Eroare la rutarea offline ABTINMAP: {error}",
 "route_error_offline_alternatives":"Crearea rutelor alternative offline ABTINMAP a eșuat: {error}",
 "route_error_online_failed_generic":"Rutarea online a eșuat.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} h {minutes} min",
 "route_no_destination":"Nicio destinație selectată",
 "route_open_map_destination":"Apăsați lung pe hartă pentru a alege o destinație.",
 "route_destination_ready":"Destinația este pregătită pentru navigare",
 "route_location_unavailable":"Locația curentă nu este disponibilă","route_location_ready":"Locația curentă este pregătită",
 "route_check_gps":"Verificați permisiunea de locație și GPS-ul.",
 "route_accuracy":"Precizia locației: {value} m",
 "route_select_destination":"Selectați destinația","route_change_destination":"Schimbați destinația",
 "route_suggested_routes":"Rute sugerate","route_calculation_failed":"Calculul rutei a eșuat: {error}",
 "route_download_offline_map":"Descărcați harta regiunii pentru rutare offline.",
 "route_online_not_found_check_internet":"Ruta online nu a fost găsită; verificați conexiunea la internet.",
 "route_set_location_destination_hint":"Setați locația și destinația pentru a vedea opțiunile de rută aici.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Sosire","route_remaining":"Rămas",
 "route_time":"Timp","route_preview_instruction":"Virați la dreapta pe strada Valiasr",
 "route_selected":"Ruta selectată","route_numbered":"Ruta {value}",
 "alert_speed_camera":"Radar de viteză","alert_speed_bump":"Limitator de viteză","alert_police":"Control de trafic",
 "alert_traffic_light":"Semafor","abtin_maps_user":"Utilizator Abtin Maps","as_palette_title":"Paletă de culori",
 "as_display_mode_subtitle":"Alegeți modul zi sau noapte",
 "as_weather_widget_subtitle":"Setări de afișare a widgetului meteo pe hartă",
}

T["ru"] = {
 "ai_dashcam_title":"Умная камера","ai_dashcam_desc":"Запись видео и интеллектуальный помощник водителя",
 "dashcam_video_size":"Размер видео","dashcam_video_size_unlimited":"∞ мин",
 "dashcam_video_size_value":"{value} мин ({size} ГБ)","dashcam_driver_assistance":"Интеллектуальный помощник водителя",
 "dashcam_fixed_camera_height":"Фиксированная высота камеры","dashcam_camera_height":"Высота камеры",
 "dashcam_vehicle_width":"Ширина автомобиля","dashcam_camera_lateral_displacement":"Боковое смещение камеры",
 "dashcam_forward_collision":"Лобовое столкновение","dashcam_dangerous_headway":"Опасная дистанция до впереди идущего автомобиля",
 "dashcam_stop_and_go":"Стоп-энд-гоу","dashcam_lane_departure_solid":"Съезд с полосы (сплошная линия)",
 "dashcam_lane_departure_dashed":"Съезд с полосы (прерывистая линия)","dashcam_traffic_sign_recognition":"Распознавание дорожных знаков",
 "hud_title":"Проекционный дисплей (HUD)","hud_menu_desc":"Показывать информацию о маршруте на лобовом стекле",
 "hud_enable":"Включить HUD","hud_enable_desc":"Показывать информацию о маршруте на лобовом стекле",
 "hud_brightness":"Яркость дисплея","hud_mirror":"Зеркальное изображение","hud_mirror_desc":"Для корректного отображения на стекле",
 "hud_scale":"Масштаб отображения","hud_position":"Положение на стекле",
 "hud_position_desc":"Общее размещение HUD на лобовом стекле","hud_visible_info":"Отображаемая информация",
 "hud_info_speed":"Скорость","hud_info_speed_limit":"Ограничение скорости","hud_info_maneuver":"Маршрут и следующий поворот",
 "hud_info_distance":"Расстояние до поворота","hud_info_heading":"Направление (компас)","hud_info_route_alerts":"Предупреждения маршрута",
 "hud_info_ai_alerts":"Предупреждения ИИ","hud_info_other":"Прочая информация","hud_preview":"Предпросмотр",
 "hud_note":"Примечание: для лучшей видимости используйте HUD в условиях низкой освещенности.",
 "hud_launch":"Запустить HUD","hud_no_active_navigation":"Запустите навигацию, чтобы использовать HUD","hud_arrived":"Вы прибыли в пункт назначения",
 "dashcam_level_off":"Выкл.","dashcam_level_low":"Низкий","dashcam_level_normal":"Обычный","dashcam_level_high":"Высокий",
 "dashcam_meters_short":"м","delete_language_package_title":"Удалить языковой пакет",
 "delete_language_package_confirm":"Удалить пакет «{name}»?","start_button":"Начать",
 "route_road_prefix":"на {road}","route_maneuver_depart":"Начните движение{road}","route_maneuver_arrive":"Вы прибыли в пункт назначения",
 "route_maneuver_turn_left":"Поверните налево{road}","route_maneuver_turn_right":"Поверните направо{road}",
 "route_maneuver_slight_left":"Слегка налево{road}","route_maneuver_slight_right":"Слегка направо{road}",
 "route_maneuver_sharp_left":"Резко налево{road}","route_maneuver_sharp_right":"Резко направо{road}",
 "route_maneuver_uturn":"Развернитесь{road}","route_maneuver_straight":"Продолжайте прямо{road}",
 "route_maneuver_continue":"Продолжайте{road}","route_maneuver_roundabout":"Въезжайте на круговое движение{road}",
 "route_maneuver_roundabout_exit":"Покиньте круг на съезде {exit}{road}",
 "route_maneuver_merge":"Вливайтесь в поток{road}","route_maneuver_on_ramp":"Въезжайте на въездную рампу{road}",
 "route_maneuver_off_ramp":"Съезжайте по выездной рампе{road}",
 "route_error_no_route":"Маршрут между начальной точкой и пунктом назначения не найден.",
 "route_error_no_segment":"Начальная точка или пункт назначения не находятся рядом с проезжей дорожной сетью.",
 "route_error_too_big":"Запрос маршрута слишком большой.",
 "route_error_online_failed":"Онлайн-сервис маршрутов не смог рассчитать маршрут.",
 "route_error_offline_unavailable":"Онлайн-маршруты недоступны в автономном режиме.",
 "route_error_offline_not_found":"На автономной карте маршрут не найден.",
 "route_error_online_not_found":"Маршрут между начальной точкой и пунктом назначения не найден.",
 "route_error_invalid_coordinates":"Координаты начальной точки или пункта назначения недействительны.",
 "route_error_unreadable_response":"Ответ сервиса маршрутов невозможно прочитать.",
 "route_error_invalid_geometry":"Геометрия онлайн-маршрута неполная или недействительна.",
 "route_error_invalid_response":"Ответ онлайн-маршрута имеет недействительный формат.",
 "route_error_connection":"Не удалось подключиться к онлайн-сервису маршрутов.",
 "route_error_unexpected":"Произошла непредвиденная ошибка при онлайн-маршрутизации.",
 "route_error_http":"Онлайн-сервис маршрутов вернул недействительный ответ ({code}).",
 "route_error_timeout":"Истекло время ответа онлайн-маршрута. Проверьте подключение к интернету.",
 "route_error_offline_map_missing":"Установите автономную карту ABM перед маршрутизацией.",
 "route_error_offline_generic":"Ошибка автономной маршрутизации ABTINMAP: {error}",
 "route_error_offline_alternatives":"Не удалось создать автономные альтернативные маршруты ABTINMAP: {error}",
 "route_error_online_failed_generic":"Онлайн-маршрутизация не удалась.",
 "route_duration_minutes":"{value} мин","route_duration_hours_minutes":"{hours} ч {minutes} мин",
 "route_no_destination":"Пункт назначения не выбран",
 "route_open_map_destination":"Удерживайте карту, чтобы выбрать пункт назначения.",
 "route_destination_ready":"Пункт назначения готов к навигации",
 "route_location_unavailable":"Текущее местоположение недоступно","route_location_ready":"Текущее местоположение готово",
 "route_check_gps":"Проверьте разрешение на определение местоположения и GPS.",
 "route_accuracy":"Точность местоположения: {value} м",
 "route_select_destination":"Выбрать пункт назначения","route_change_destination":"Изменить пункт назначения",
 "route_suggested_routes":"Предлагаемые маршруты","route_calculation_failed":"Расчет маршрута не удался: {error}",
 "route_download_offline_map":"Скачайте карту региона для автономной маршрутизации.",
 "route_online_not_found_check_internet":"Онлайн-маршрут не найден; проверьте подключение к интернету.",
 "route_set_location_destination_hint":"Укажите местоположение и пункт назначения, чтобы увидеть варианты маршрута здесь.",
 "route_distance_km":"{value} км","route_distance_m":"{value} м","route_eta":"Прибытие","route_remaining":"Осталось",
 "route_time":"Время","route_preview_instruction":"Поверните направо на улицу Валиаср",
 "route_selected":"Выбранный маршрут","route_numbered":"Маршрут {value}",
 "alert_speed_camera":"Камера скорости","alert_speed_bump":"Лежачий полицейский","alert_police":"Пост ДПС",
 "alert_traffic_light":"Светофор","abtin_maps_user":"Пользователь Abtin Maps","as_palette_title":"Цветовая палитра",
 "as_display_mode_subtitle":"Выберите дневной или ночной режим",
 "as_weather_widget_subtitle":"Настройки отображения виджета погоды на карте",
}

T["sv"] = {
 "ai_dashcam_title":"Smart kamera","ai_dashcam_desc":"Videoinspelning och smart körassistent",
 "dashcam_video_size":"Videostorlek","dashcam_video_size_unlimited":"∞ min",
 "dashcam_video_size_value":"{value} min ({size} GB)","dashcam_driver_assistance":"Smart körassistent",
 "dashcam_fixed_camera_height":"Fast kamerahöjd","dashcam_camera_height":"Kamerahöjd",
 "dashcam_vehicle_width":"Fordonsbredd","dashcam_camera_lateral_displacement":"Kamerans laterala förskjutning",
 "dashcam_forward_collision":"Frontalkollision","dashcam_dangerous_headway":"Farligt avstånd till fordonet framför",
 "dashcam_stop_and_go":"Stanna och kör","dashcam_lane_departure_solid":"Körfältsavvikelse (heldragen linje)",
 "dashcam_lane_departure_dashed":"Körfältsavvikelse (streckad linje)","dashcam_traffic_sign_recognition":"Igenkänning av vägmärken",
 "hud_title":"Head-up-display (HUD)","hud_menu_desc":"Visa ruttinformation på vindrutan",
 "hud_enable":"Aktivera HUD","hud_enable_desc":"Visa ruttinformation på vindrutan",
 "hud_brightness":"Skärmljusstyrka","hud_mirror":"Spegelbild","hud_mirror_desc":"För korrekt visning på glaset",
 "hud_scale":"Visningsskala","hud_position":"Position på glaset",
 "hud_position_desc":"Övergripande placering av HUD på vindrutan","hud_visible_info":"Visbar information",
 "hud_info_speed":"Hastighet","hud_info_speed_limit":"Hastighetsgräns","hud_info_maneuver":"Rutt och nästa sväng",
 "hud_info_distance":"Avstånd till sväng","hud_info_heading":"Riktning (kompass)","hud_info_route_alerts":"Ruttvarningar",
 "hud_info_ai_alerts":"AI-varningar","hud_info_other":"Övrig information","hud_preview":"Förhandsvisning",
 "hud_note":"Obs: För bästa sikt, använd HUD i en miljö med svag belysning.",
 "hud_launch":"Starta HUD","hud_no_active_navigation":"Starta navigering för att använda HUD","hud_arrived":"Du har anlänt",
 "dashcam_level_off":"Av","dashcam_level_low":"Låg","dashcam_level_normal":"Normal","dashcam_level_high":"Hög",
 "dashcam_meters_short":"m","delete_language_package_title":"Ta bort språkpaket",
 "delete_language_package_confirm":"Ta bort paketet \"{name}\"?","start_button":"Starta",
 "route_road_prefix":"till {road}","route_maneuver_depart":"Börja köra{road}","route_maneuver_arrive":"Du har anlänt",
 "route_maneuver_turn_left":"Sväng vänster{road}","route_maneuver_turn_right":"Sväng höger{road}",
 "route_maneuver_slight_left":"Sväng lätt vänster{road}","route_maneuver_slight_right":"Sväng lätt höger{road}",
 "route_maneuver_sharp_left":"Sväng skarpt vänster{road}","route_maneuver_sharp_right":"Sväng skarpt höger{road}",
 "route_maneuver_uturn":"Gör en U-sväng{road}","route_maneuver_straight":"Fortsätt rakt fram{road}",
 "route_maneuver_continue":"Fortsätt{road}","route_maneuver_roundabout":"Kör in i rondellen{road}",
 "route_maneuver_roundabout_exit":"Lämna rondellen vid avfart {exit}{road}",
 "route_maneuver_merge":"Foga in i trafiken{road}","route_maneuver_on_ramp":"Kör in på påfarten{road}",
 "route_maneuver_off_ramp":"Kör av via avfarten{road}",
 "route_error_no_route":"Ingen rutt hittades mellan start och destination.",
 "route_error_no_segment":"Start eller destination ligger inte nära ett framkomligt vägnät.",
 "route_error_too_big":"Ruttförfrågan är för stor.",
 "route_error_online_failed":"Onlinerutttjänsten kunde inte beräkna rutten.",
 "route_error_offline_unavailable":"Onlinerutter är inte tillgängliga i offlineläge.",
 "route_error_offline_not_found":"Ingen rutt hittades på offlinekartan.",
 "route_error_online_not_found":"Ingen rutt hittades mellan start och destination.",
 "route_error_invalid_coordinates":"Koordinaterna för start eller destination är ogiltiga.",
 "route_error_unreadable_response":"Rutttjänstens svar kan inte läsas.",
 "route_error_invalid_geometry":"Geometrin för onlinerutten är ofullständig eller ogiltig.",
 "route_error_invalid_response":"Onlineruttsvaret har ett ogiltigt format.",
 "route_error_connection":"Kunde inte ansluta till onlinerutttjänsten.",
 "route_error_unexpected":"Ett oväntat fel inträffade vid onlineruttning.",
 "route_error_http":"Onlinerutttjänsten returnerade ett ogiltigt svar ({code}).",
 "route_error_timeout":"Tidsgränsen för onlineruttsvaret överskreds. Kontrollera internetanslutningen.",
 "route_error_offline_map_missing":"Installera en offline-ABM-karta innan ruttning.",
 "route_error_offline_generic":"Fel vid offline-ruttning ABTINMAP: {error}",
 "route_error_offline_alternatives":"Det gick inte att skapa offline-alternativa rutter ABTINMAP: {error}",
 "route_error_online_failed_generic":"Onlineruttning misslyckades.",
 "route_duration_minutes":"{value} min","route_duration_hours_minutes":"{hours} t {minutes} min",
 "route_no_destination":"Ingen destination vald",
 "route_open_map_destination":"Håll ned kartan för att välja en destination.",
 "route_destination_ready":"Destinationen är redo för navigering",
 "route_location_unavailable":"Aktuell plats är inte tillgänglig","route_location_ready":"Aktuell plats är redo",
 "route_check_gps":"Kontrollera platstillstånd och GPS.",
 "route_accuracy":"Platsnoggrannhet: {value} m",
 "route_select_destination":"Välj destination","route_change_destination":"Ändra destination",
 "route_suggested_routes":"Föreslagna rutter","route_calculation_failed":"Ruttberäkning misslyckades: {error}",
 "route_download_offline_map":"Ladda ner regionkartan för offline-ruttning.",
 "route_online_not_found_check_internet":"Onlinerutt hittades inte; kontrollera internetanslutningen.",
 "route_set_location_destination_hint":"Ange plats och destination för att se ruttalternativ här.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Ankomst","route_remaining":"Återstår",
 "route_time":"Tid","route_preview_instruction":"Sväng höger in på Valiasr-gatan",
 "route_selected":"Vald rutt","route_numbered":"Rutt {value}",
 "alert_speed_camera":"Hastighetskamera","alert_speed_bump":"Fartgupp","alert_police":"Trafikkontroll",
 "alert_traffic_light":"Trafikljus","abtin_maps_user":"Abtin Maps-användare","as_palette_title":"Färgpalett",
 "as_display_mode_subtitle":"Välj dag- eller nattläge",
 "as_weather_widget_subtitle":"Visningsinställningar för väderwidgeten på kartan",
}

T["th"] = {
 "ai_dashcam_title":"กล้องอัจฉริยะ","ai_dashcam_desc":"บันทึกวิดีโอและผู้ช่วยขับขี่อัจฉริยะ",
 "dashcam_video_size":"ขนาดวิดีโอ","dashcam_video_size_unlimited":"∞ นาที",
 "dashcam_video_size_value":"{value} นาที ({size} GB)","dashcam_driver_assistance":"ผู้ช่วยขับขี่อัจฉริยะ",
 "dashcam_fixed_camera_height":"ความสูงกล้องคงที่","dashcam_camera_height":"ความสูงกล้อง",
 "dashcam_vehicle_width":"ความกว้างรถ","dashcam_camera_lateral_displacement":"การเลื่อนด้านข้างของกล้อง",
 "dashcam_forward_collision":"การชนด้านหน้า","dashcam_dangerous_headway":"ระยะห่างอันตรายจากรถคันหน้า",
 "dashcam_stop_and_go":"หยุดแล้วไป","dashcam_lane_departure_solid":"ออกนอกเลน (เส้นทึบ)",
 "dashcam_lane_departure_dashed":"ออกนอกเลน (เส้นประ)","dashcam_traffic_sign_recognition":"การรู้จำป้ายจราจร",
 "hud_title":"จอแสดงผลแบบ Head-up (HUD)","hud_menu_desc":"แสดงข้อมูลเส้นทางบนกระจกหน้า",
 "hud_enable":"เปิดใช้ HUD","hud_enable_desc":"แสดงข้อมูลเส้นทางบนกระจกหน้า",
 "hud_brightness":"ความสว่างหน้าจอ","hud_mirror":"ภาพสะท้อน","hud_mirror_desc":"เพื่อแสดงผลบนกระจกอย่างถูกต้อง",
 "hud_scale":"สเกลการแสดงผล","hud_position":"ตำแหน่งบนกระจก",
 "hud_position_desc":"การวางตำแหน่งโดยรวมของ HUD บนกระจกหน้า","hud_visible_info":"ข้อมูลที่แสดงได้",
 "hud_info_speed":"ความเร็ว","hud_info_speed_limit":"จำกัดความเร็ว","hud_info_maneuver":"เส้นทางและทางเลี้ยวถัดไป",
 "hud_info_distance":"ระยะทางถึงทางเลี้ยว","hud_info_heading":"ทิศทาง (เข็มทิศ)","hud_info_route_alerts":"การแจ้งเตือนเส้นทาง",
 "hud_info_ai_alerts":"การแจ้งเตือน AI","hud_info_other":"ข้อมูลอื่นๆ","hud_preview":"ตัวอย่าง",
 "hud_note":"หมายเหตุ: เพื่อการมองเห็นที่ดีที่สุด ให้ใช้ HUD ในสภาพแวดล้อมที่มีแสงน้อย",
 "hud_launch":"เปิด HUD","hud_no_active_navigation":"เริ่มการนำทางเพื่อใช้ HUD","hud_arrived":"คุณถึงจุดหมายแล้ว",
 "dashcam_level_off":"ปิด","dashcam_level_low":"ต่ำ","dashcam_level_normal":"ปกติ","dashcam_level_high":"สูง",
 "dashcam_meters_short":"ม.","delete_language_package_title":"ลบแพ็กภาษา",
 "delete_language_package_confirm":"ลบแพ็ก \"{name}\" หรือไม่?","start_button":"เริ่ม",
 "route_road_prefix":"ไปยัง {road}","route_maneuver_depart":"เริ่มขับรถ{road}","route_maneuver_arrive":"คุณถึงจุดหมายแล้ว",
 "route_maneuver_turn_left":"เลี้ยวซ้าย{road}","route_maneuver_turn_right":"เลี้ยวขวา{road}",
 "route_maneuver_slight_left":"เลี้ยวซ้ายเล็กน้อย{road}","route_maneuver_slight_right":"เลี้ยวขวาเล็กน้อย{road}",
 "route_maneuver_sharp_left":"เลี้ยวซ้ายหักศอก{road}","route_maneuver_sharp_right":"เลี้ยวขวาหักศอก{road}",
 "route_maneuver_uturn":"กลับรถ{road}","route_maneuver_straight":"ตรงไป{road}",
 "route_maneuver_continue":"ต่อไป{road}","route_maneuver_roundabout":"เข้าเกาะกลางถนน{road}",
 "route_maneuver_roundabout_exit":"ออกจากเกาะกลางถนนทางออกที่ {exit}{road}",
 "route_maneuver_merge":"รวมเข้าด้วยกัน{road}","route_maneuver_on_ramp":"เข้าทางลาดขึ้น{road}",
 "route_maneuver_off_ramp":"ออกทางลาดลง{road}",
 "route_error_no_route":"ไม่พบเส้นทางระหว่างจุดเริ่มต้นและจุดหมาย",
 "route_error_no_segment":"จุดเริ่มต้นหรือจุดหมายไม่อยู่ใกล้เครือข่ายถนนที่ใช้ได้",
 "route_error_too_big":"คำขอเส้นทางใหญ่เกินไป",
 "route_error_online_failed":"บริการเส้นทางออนไลน์ไม่สามารถคำนวณเส้นทางได้",
 "route_error_offline_unavailable":"เส้นทางออนไลน์ไม่พร้อมใช้งานในโหมดออฟไลน์",
 "route_error_offline_not_found":"ไม่พบเส้นทางบนแผนที่ออฟไลน์",
 "route_error_online_not_found":"ไม่พบเส้นทางระหว่างจุดเริ่มต้นและจุดหมาย",
 "route_error_invalid_coordinates":"พิกัดจุดเริ่มต้นหรือจุดหมายไม่ถูกต้อง",
 "route_error_unreadable_response":"ไม่สามารถอ่านคำตอบจากบริการเส้นทางได้",
 "route_error_invalid_geometry":"รูปเรขาคณิตของเส้นทางออนไลน์ไม่สมบูรณ์หรือไม่ถูกต้อง",
 "route_error_invalid_response":"คำตอบเส้นทางออนไลน์มีรูปแบบไม่ถูกต้อง",
 "route_error_connection":"ไม่สามารถเชื่อมต่อกับบริการเส้นทางออนไลน์ได้",
 "route_error_unexpected":"เกิดข้อผิดพลาดที่ไม่คาดคิดระหว่างการนำทางออนไลน์",
 "route_error_http":"บริการเส้นทางออนไลน์ส่งคำตอบที่ไม่ถูกต้อง ({code})",
 "route_error_timeout":"หมดเวลารอคำตอบเส้นทางออนไลน์ โปรดตรวจสอบการเชื่อมต่ออินเทอร์เน็ต",
 "route_error_offline_map_missing":"ติดตั้งแผนที่ ABM แบบออฟไลน์ก่อนการนำทาง",
 "route_error_offline_generic":"ข้อผิดพลาดในการนำทางออฟไลน์ ABTINMAP: {error}",
 "route_error_offline_alternatives":"สร้างเส้นทางสำรองออฟไลน์ ABTINMAP ไม่สำเร็จ: {error}",
 "route_error_online_failed_generic":"การนำทางออนไลน์ล้มเหลว",
 "route_duration_minutes":"{value} นาที","route_duration_hours_minutes":"{hours} ชม. {minutes} นาที",
 "route_no_destination":"ยังไม่ได้เลือกจุดหมาย",
 "route_open_map_destination":"กดค้างบนแผนที่เพื่อเลือกจุดหมาย",
 "route_destination_ready":"จุดหมายพร้อมสำหรับการนำทาง",
 "route_location_unavailable":"ตำแหน่งปัจจุบันไม่พร้อมใช้งาน","route_location_ready":"ตำแหน่งปัจจุบันพร้อม",
 "route_check_gps":"ตรวจสอบสิทธิ์ตำแหน่งและ GPS",
 "route_accuracy":"ความแม่นยำของตำแหน่ง: {value} ม.",
 "route_select_destination":"เลือกจุดหมาย","route_change_destination":"เปลี่ยนจุดหมาย",
 "route_suggested_routes":"เส้นทางที่แนะนำ","route_calculation_failed":"การคำนวณเส้นทางล้มเหลว: {error}",
 "route_download_offline_map":"ดาวน์โหลดแผนภูมิภาคสำหรับการนำทางออฟไลน์",
 "route_online_not_found_check_internet":"ไม่พบเส้นทางออนไลน์ โปรดตรวจสอบการเชื่อมต่ออินเทอร์เน็ต",
 "route_set_location_destination_hint":"ตั้งค่าตำแหน่งและจุดหมายเพื่อดูตัวเลือกเส้นทางที่นี่",
 "route_distance_km":"{value} กม.","route_distance_m":"{value} ม.","route_eta":"ถึง","route_remaining":"เหลือ",
 "route_time":"เวลา","route_preview_instruction":"เลี้ยวขวาเข้าถนนวาเลียสร์",
 "route_selected":"เส้นทางที่เลือก","route_numbered":"เส้นทาง {value}",
 "alert_speed_camera":"กล้องตรวจจับความเร็ว","alert_speed_bump":"เนินชะลอความเร็ว","alert_police":"ด่านตำรวจจราจร",
 "alert_traffic_light":"ไฟจราจร","abtin_maps_user":"ผู้ใช้ Abtin Maps","as_palette_title":"จานสี",
 "as_display_mode_subtitle":"เลือกโหมดกลางวันหรือกลางคืน",
 "as_weather_widget_subtitle":"การตั้งค่าการแสดงวิดเจ็ตสภาพอากาศบนแผนที่",
}

T["tr"] = {
 "ai_dashcam_title":"Akıllı Kamera","ai_dashcam_desc":"Video kaydı ve akıllı sürüş asistanı",
 "dashcam_video_size":"Video boyutu","dashcam_video_size_unlimited":"∞ dk",
 "dashcam_video_size_value":"{value} dk ({size} GB)","dashcam_driver_assistance":"Akıllı sürüş asistanı",
 "dashcam_fixed_camera_height":"Sabit kamera yüksekliği","dashcam_camera_height":"Kamera yüksekliği",
 "dashcam_vehicle_width":"Araç genişliği","dashcam_camera_lateral_displacement":"Kamera yanal yer değiştirmesi",
 "dashcam_forward_collision":"Önden çarpışma","dashcam_dangerous_headway":"Öndeki araçla tehlikeli mesafe",
 "dashcam_stop_and_go":"Dur ve kalk","dashcam_lane_departure_solid":"Şeritten çıkma (kesintisiz çizgi)",
 "dashcam_lane_departure_dashed":"Şeritten çıkma (kesikli çizgi)","dash_camera_traffic_sign_recognition":"Trafik işareti tanıma",
 "hud_title":"Baş üstü ekran (HUD)","hud_menu_desc":"Rota bilgilerini ön camda göster",
 "hud_enable":"HUD'u etkinleştir","hud_enable_desc":"Rota bilgilerini ön camda göster",
 "hud_brightness":"Ekran parlaklığı","hud_mirror":"Ayna görüntüsü","hud_mirror_desc":"Camda doğru görüntü için",
 "hud_scale":"Görüntü ölçeği","hud_position":"Camdaki konum",
 "hud_position_desc":"HUD'un ön camdaki genel yerleşimi","hud_visible_info":"Gösterilebilir bilgiler",
 "hud_info_speed":"Hız","hud_info_speed_limit":"Hız limiti","hud_info_maneuver":"Rota ve sonraki dönüş",
 "hud_info_distance":"Dönüşe mesafe","hud_info_heading":"Yön (pusula)","hud_info_route_alerts":"Rota uyarıları",
 "hud_info_ai_alerts":"Yapay zeka uyarıları","hud_info_other":"Diğer bilgiler","hud_preview":"Önizleme",
 "hud_note":"Not: En iyi görünürlük için HUD'u düşük ışıklı ortamda kullanın.",
 "hud_launch":"HUD'u başlat","hud_no_active_navigation":"HUD'u kullanmak için navigasyonu başlatın","hud_arrived":"Hedefe ulaştınız",
 "dashcam_level_off":"Kapalı","dashcam_level_low":"Düşük","dashcam_level_normal":"Normal","dashcam_level_high":"Yüksek",
 "dashcam_meters_short":"m","delete_language_package_title":"Dil paketini sil",
 "delete_language_package_confirm":"\"{name}\" paketi silinsin mi?","start_button":"Başlat",
 "route_road_prefix":"{road} yönünde","route_maneuver_depart":"Sürüşe başlayın{road}","route_maneuver_arrive":"Hedefe ulaştınız",
 "route_maneuver_turn_left":"Sola dönün{road}","route_maneuver_turn_right":"Sağa dönün{road}",
 "route_maneuver_slight_left":"Hafif sola{road}","route_maneuver_slight_right":"Hafif sağa{road}",
 "route_maneuver_sharp_left":"Keskin sola{road}","route_maneuver_sharp_right":"Keskin sağa{road}",
 "route_maneuver_uturn":"U dönüşü yapın{road}","route_maneuver_straight":"Düz devam edin{road}",
 "route_maneuver_continue":"Devam edin{road}","route_maneuver_roundabout":"Dönel kavşağa girin{road}",
 "route_maneuver_roundabout_exit":"Dönel kavşaktan {exit}. çıkıştan çıkın{road}",
 "route_maneuver_merge":"Şeride katılın{road}","route_maneuver_on_ramp":"Giriş rampasına girin{road}",
 "route_maneuver_off_ramp":"Çıkış rampasından çıkın{road}",
 "route_error_no_route":"Başlangıç ve hedef arasında rota bulunamadı.",
 "route_error_no_segment":"Başlangıç veya hedef, sürülebilir bir yol ağının yakınında değil.",
 "route_error_too_big":"Rota isteği çok büyük.",
 "route_error_online_failed":"Çevrimiçi rota servisi rotayı hesaplayamadı.",
 "route_error_offline_unavailable":"Çevrimdışı modda çevrimiçi rotalar kullanılamaz.",
 "route_error_offline_not_found":"Çevrimdışı haritada rota bulunamadı.",
 "route_error_online_not_found":"Başlangıç ve hedef arasında rota bulunamadı.",
 "route_error_invalid_coordinates":"Başlangıç veya hedef koordinatları geçersiz.",
 "route_error_unreadable_response":"Rota servisinin yanıtı okunamıyor.",
 "route_error_invalid_geometry":"Çevrimiçi rotanın geometrisi eksik veya geçersiz.",
 "route_error_invalid_response":"Çevrimiçi rota yanıtının biçimi geçersiz.",
 "route_error_connection":"Çevrimiçi rota servisine bağlanılamadı.",
 " "route_error_unexpected":"Çevrimiçi rota hesaplama sırasında beklenmeyen bir hata oluştu.",
 "route_error_http":"Çevrimiçi rota servisi geçersiz bir yanıt döndürdü ({code}).",
 "route_error_timeout":"Çevrimiçi rota yanıtı zaman aşımına uğradı. İnternet bağlantınızı kontrol edin.",
 " "route_error_offline_map_missing":"Rota heplamadan önce çevrimdışı bir ABM haritası kurun.",
 "route_error_offline_generic":"ABTINMAP çevrimdışı rota hatası: {error}",
 "route_error_offline_alternatives":"ABTINMAP çevrimdışı alternatif rotalar oluşturulamadı: {error}",
 " "route_error_online_failed_generic":"Çevrimiçi rota hesaplama başarısız oldu.",
 "route_duration_minutes":"{value} dk","route_duration_hours_minutes":"{hours} sa {minutes} dk",
 "route_no_destination":"Hedef seçilmedi",
 " "route_open_map_destination":"Hedef seçmek için haritaya uzun basın.",
 "route_destination_ready":"Hedef navigasyona hazır",
 "route_location_unavailable":"Geçerli konum kullanılamıyor","route_location_ready":"Geçerli konum hazır",
 "route_check_gps":"Konum izni ve GPS'i kontrol edin.",
 "route_accuracy":"Konum doğruluğu: {value} m",
 "route_select_destination":"Hedef seç"," "route_change_destination":"Hedef değiştir",
 "route_suggested_routes":"Önerilen rotalar"," "route_calculation_failed":"Rota hesaplama başarısız oldu: {error}",
 "route_download_offline_map":"Çevrimdışı rota için bölge haritasını indirin.",
 "route_online_not_found_check_internet":"Çevrimiçi rota bulunamadı; internet balantınızı kontrol edin.",
 " "route_set_location_destination_hint":"Burada rota seçeneklerini görmek için konum ve hedefi ayarlayın.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Varış","route_remaining":"Kalan",
 "route_time":"Süre","route_preview_instruction":"Sağa dönüp Valiasr Caddesi'ne girin",
 "route_selected":"Seçilen rota","route_numbered":"Rota {value}",
 "alert_speed_camera":"Hız kamerası","alert_speed_bump":"Hız tümseği","alert_police":"Trafik polisi",
 "alert_traffic_light":"Trafik ışığı","abtin_maps_user":"Abtin Maps kullanıcısı","as_palette_title":"Renk paleti",
 "as_display_mode_subtitle":"Gündüz veya gece modunu seçin",
 "as_weather_widget_subtitle":"Haritadaki hava durumu widget görüntüleme ayarları",
}

T["uk"] = {
 "ai_dashcam_title":"Розумна камера","ai_dashcam_desc":"Запис відео та інтелектуальний помічник водія",
 "dashcam_video_size":"Розмір відео","dashcam_video_size_unlimited":"∞ хв",
 "dashcam_video_size_value":"{value} хв ({size} ГБ)","dashcam_driver_assistance":"Інтелектуальний помічник водія",
 "dashcam_fixed_camera_height":"Фіксована висота камери","dashcam_camera_height":"Висота камери",
 "dashcam_vehicle_width":"Ширина автомобіля","dashcam_camera_lateral_displacement":"Бічне зміщення камери",
 "dashcam_forward_collision":"Лобове зіткнення","dashcam_dangerous_headway":"Небезпечна дистанція до автомобіля попереду",
 "dashcam_stop_and_go":"Стоп-енд-гоу","dashcam_lane_departure_solid":"З'їзд зі смуги (суцільна лінія)",
 "dashcam_lane_departure_dashed":"З'їзд зі смуги (переривчаста лінія)","dashcam_traffic_sign_recognition":"Розпізнавання дорожніх знаків",
 "hud_title":"Проєкційний дисплей (HUD)","hud_menu_desc":"Показувати інформацію про маршрут на лобовому склі",
 "hud_enable":"Увімкнути HUD","hud_enable_desc":"Показувати інформацію про маршрут на лобовому склі",
 "hud_brightness":"Яскравість дисплея","hud_mirror":"Дзеркальне зображення","hud_mirror_desc":"Для коректного відображення на склі",
 " "hud_scale":"Масштаб відображення","hud_position":"Положення на склі",
 "hud_position_desc":"Загальне розміщення HUD на лобовому склі","hud_visible_info":"Відображувана інформація",
 "hud_info_speed":"Швидкість","hhud_info_speed_limit":"Обмеження швидкості","hud_info_maneuver":"Маршрут і наступний поворот",
 "hud_info_distance":"Відстань до повороту","hud_info_heading":"Напрямок (компас)","hud_info_route_alerts":"Попередження маршруту",
 "hud_info_ai_alerts":"Попередження ШІ","hud_info_other":"Інша інформація","hud_preview":"Попередній перегляд",
 "hud_note":"Примітка: для найкращої видимості використовуйте HUD в умовах низького освітлення.",
 "hud_launch":"Запустити HUD","hud_no_active_navigtion":"Запустть навігацію, щоб використовувати HUD","hud_hud_arrived":"Ви прибули до пункту призначення",
 "dashcam_level_off":"Вимк.","ddashcam_level_low":"Низький","dashcam_level_normal":"Звичайний","dashcam_level_high":"Високий",
 "dashcam_meters_short":"м","delete_language_package_title":"Видалити мовний пакет",
 "delete_language_package_confirm":"Видалити пакет «{name}»?","start_button":"Почати",
 "route_road_prefix":"на {road}","route_maneuver_depart":"Почніть рух{road}","route_maneuver_arrive":"Ви прибули до пункту призначення",
 "route_maneuver_turn_left":"Поверніть ліворуч{road}","route_maneuver_turn_right":"Поверніть праворуч{road}",
 "route_maneuver_slight_left":"Злегка ліворуч{road}","route_maneuver_slight_right":"Злегка праворуч{road}",
 "route_maneuver_sharp_left":"Різко ліворуч{road}","route_maneuver_sharp_right":"Різко праворуч{road}",
 "route_maneueuver_uturn":"Розверніться{road}","route_maneuver_straight":"Продовжуйте прямо{road}",
 "route_maneuver_continue":"Продовжуйте{road}","route_maneuver_roundabout":"В'їжджайте на круговий рух{road}",
 "route_maneuver_roundabout_exit":"Покиньте коло на з'їзді {exit}{road}",
 "route_maneuver_merge":"Вливайтеся в потік{road}","route_maneuver_on_ramp":"В'їжджайте на в'їзну рампу{road}",
 "route_maneuver_off_ramp":"З'їжджайте по виїзній рампі{road}",
 "route_error_no_route":"Маршрут між початковою точкою та пунктом призначення не знайдено.",
 "route_error_no_segment":"Початкова точка або пункт призначення не знаходяться поблизу проїзної дорожньої мережі.",
 "route_error_too_big":"Запит маршруту занадто великий.",
 "route_error_online_failed":"Онлайн-сервіс маршрутів не зміг розрахувати маршрут.",
 "route_error_offlineine_unavailable":"Онлайн-маршрути недоступні в автономному режимі.",
 "route_error_offline_not_found":"На автономній карті маршрут не знайдено.",
 "route_error_online_not_found":"Маршрут між початковою точкою та пунктом призначення не знайдено.",
 "route_error_invalid_coordinates":"Координати початкової точки або пункту призначення недійсні.",
 "route_error_unreadable_response":"Відповідь сервісу маршрутів неможливо прочитати.",
 "route_error_invalid_geometry":"Геометрія онлайн-маршруту неповна або недійсна.",
 "route_error_invalid_response":"Відповідь онлайн-маршруту має недійсний формат.",
 "route_error_connection":"Не вдалося підключитися до онлайн-сервісу маршшрутів.",
 "route_error_unexpected":"Сталася непередбачувана помиллка під час онлайн-маршрутизації.",
 "route_error_http":"Онлайн-сервіс маршрутів повернув недійсну відповідь ({code}).",
 " "route_error_timeout":"Час відповіді онлайн-маршруту вичерпано. Перевірте підключення до інтернету.",
 "route_error_offline_map_missing":"Установіть автононну карту ABM перед маршрутизацією.",
 "route_error_offline_generic":"Помилка автономної маршрутизації ABTINMAP: {error}",
 "route_error_offline_alternatives":"Не вдалося створити автономні альтернативні маршрути ABTINMAP: {error}",
 "route_error_online_failed_generic":"Онлайн-маршрутизація не вдалася.",
 "route_duration_minutes":"{value} хв","route_duration_hours_minutes":"{hours} год {minutes} хв",
 "route_no_destination":"Пункт призначення не вибрано",
 " "route_open_map_destination":"Утримуйте карту, щоб вибрати пункт призначення.",
 "route_destination_ready":"Пункт призначення готовий до навігації",
 "route_location_unavailable":"Поточне місцезнаходження недоступне","route_location_ready":"Поточне місцезнаходження готове",
 " "route_check_gps":"Перевірте дозвіл на визначення місцезнаходження та GPS.",
 "route_accuracy":"Тчність місцезнаходження: {value} м",
 "route_select_destination":"Вибрати пункт призначення"," "route_change_destination":"Змінити пункт призначення",
 "route_suggested_routes":"Запроповані маршрути","route_calculation_failed":"Розрахунок маршруту не вдався: {error}",
 "route_download_offline_map":"Завантажте карту регіону для автономної маршрутизації.",
 "route_online_not_found_check_internet":"Онлайн-маршрут не знайдено; перевірте підключення до інтернету.",
 "route_set_location_destination_hint":"Укажіть місцезнаходження та пункт призначення, щоб побачити варіанти маршруту тут.",
 "route_distance_km":"{value} км","route_distance_m":"{value} м","route_eta":"Прибуття","route_remaining":"Залишилося",
 "route_time":"Час","route_preview_instruction":"Поверніть праворуч на вулицю Валіаср",
 "route_selected":"Вибраний маршрут","route_numbered":"Маршрут {value}",
 "alert_speed_camera":"Камера швидкості","alert_speed_bump":"Лежачий поліцейський","alert_police":"Пост ДПС",
 " "alert_trafik_light":"Світлофор","abtin_maps_user":"Користувач Abtin Maps","as_palette_title":"Кольорова палітра",
 "as_display_mode_subtitle":"Виберіть денний або нічний режим",
 "as_weather_widget_subtitle":"Налаштування відображення віджета погди на карті",
}

T["ur"] = {
 "ai_dashcam_title":"سمارٹ کیمرہ","ai_dashcam_desc":"ویڈیو ریکارڈنگ اور سمارٹ ڈرائیونگ اسسٹنٹ",
 "dashcam_video_size":"ویڈیو کا حجم","dashcam_video_size_unlimited":"∞ منٹ",
 "dashcam_video_size_value":"{value} منٹ ({size} GB)","dashcam_driver_assistance":"سمارٹ ڈرائیونگ اسسٹنٹ",
 "dashcam_fixed_camera_height":"مقررہ کیمرہ اونچائی","dashcam_camera_height":"کیمرہ اونچائی",
 "dashcam_vehicle_width":"گاڑی کی چوڑائی","dashcam_camera_lateral_displacement":"کیمرے کا پس منظر نقل مکانی",
 "dashcam_forward_collision":"سامنے سے تصادم","dashcam_dangerous_headway":"سامنے والی گاڑی سے خطرناک فاصلہ",
 "dashcam_stop_and_go":"رکو اور چلو","dashcam_lane_departure_solid":"لین سے باہر (مسلسل لائن)",
 "dashcam_lane_departure_dashed":"لین سے باہر (ٹوٹی لائن)","dashcam_traffic_sign_recognition":"ٹریفک علامات کی شناخت",
 "hud_title":"ہیڈ اپ ڈسپلے (HUD)","hud_menu_desc":"ونڈشیلڈ پر راستے کی معلومات دکھائیں",
 "hud_enable":"HUD فعال کریں","hud_enable_desc":"ونڈشیلڈ پر راستے کی معلومات دکھائیں",
 "hud_brightness":"ڈسپلے کی چمک"," "hud_mirror":"آئینہ تصویر","hud_mirror_desc":"شیشے پر صحیح ڈسپلے کے لیے",
 "hud_scale":"ڈسپلے اسکیل","hud_position":"شیشے پر ڈسپلے پوزیشن",
 "hud_position_desc":"ونڈشیلڈ پر HUD کی مجموعی جگہ","hud_visible_info":"قابلِ ڈسپلے معلومات",
 "hud_info_speed":"رفتار","hud_info_speed_limit":"رفتار کی حد","hud_info_maneuver":"راستہ اور اگلا موڑ",
 "hud_info_distance":"موڑ تک فاصلہ","hud_info_heading":"سمت (کمپاس)","hud_info_route_alerts":"راستے کے الرٹس",
 " "hud_info_ai_alerts":"AI الرٹس","hud_info_other":"دیگر معلومات","hhud_preview":"پیش نظارہ",
 " "hud_note":"نوٹ: بہترین مرئیت کے لیے، کم روشنی والے ماحول میں HUD استعمال کریں۔",
 "hud_launch":"HUD لانچ کریں","hud_no_active_navigation":"HUD استعمال کرنے کے لیے نیویگیشن شروع کریں","hud_arrived":"آپ منزل پر پہنچ گئے",
 "dashcam_level_off":"بند","dashcam_level_low":"کم","dashcam_level_normal":"معمول","dashcam_level_high":"زیادہ",
 "dashcam_meters_short":"م","delete_language_package_title":"زبان پیکج حذف کریں",
 "delete_language_package_confirm":"پیکج \"{name}\" حذف کریں؟","start_button":"شروع",
 "route_road_prefix":"کی طرف {road}","route_maneuver_depart":"گاڑی چلانا شروع کریں{road}","route_maneuver_arrive":"آپ منزل پر پہنچ گئے",
 "route_maneuver_turn_left":"بائیں مڑیں{road}","route_maneuver_turn_right":"دائیں مڑیں{road}",
 "route_maneuver_slight_left":"ہلکا بائیں{road}","route_maneuver_slight_right":"ہلکا دائیں{road}",
 "route_maneuver_sharp_left":"تیز بائیں{road}","route_maneuver_sharp_right":"تیز دائیں{road}",
 "route_maneuver_uturn":"یو ٹرن لیں{road}","route_maneuver_straight":"سیدھے جاری رہیں{road}",
 "route_maneuver_continue":"جاری رکھیں{road}","route_maneuver_roundabout":"گول چکر میں داخل ہوں{road}",
 "route_maneuver_roundabout_exit":"گول چکر سے باہر نکلیں {exit}{road}",
 "route_maneuver_merge":"ضم ہوں{road}","route_maneuver_on_ramp":"داخلے کی ریمپ پر جائیں{road}",
 "route_maneuver_off_ramp":"خروجی ریمپ سے باہر جائیں{road}",
 "route_error_no_route":"شروع اور منزل کے درمیان کوئی راستہ نہیں ملا۔",
 "route_error_no_segment":"شروع یا منزل کسی قابلِ گزر سڑک نیٹ ورک کے قریب نہیں ہے۔",
 "route_error_too_big":"راستے کی درخواست بہت بڑی ہے۔",
 "route_error_online_failed":"آن لائن راستہ سروس راستہ حساب نہیں کر سکی۔",
 "route_error_offline_unavailable":"آف لائن موڈ میں آن لائن راستے دستیاب نہیں ہیں۔",
 "route_error_offline_not_found":"آف لائن نقشے پر کوئی راستہ نہیں ملا۔",
 "route_error_online_not_found":"شروع اور منزل کے درمیان کوئی راستہ نہیں ملا۔",
 "route_error_invalid_coordinates":"شروع یا منزل کے نقاط غلط ہیں۔",
 "route_error_unreadable_response":"راستہ سروس کا جواب پڑھا نہیں جا سکتا۔",
 "route_error_invalid_geometry":"آن لائن راستے کی جیومیٹری نامکمل یا غلط ہے۔",
 "route_error_invalid_response":"آن لائن راستے کے جواب کی شکل غلط ہے۔",
 "route_error_connection":"آن لائن راستہ سروس سے رابطہ نہیں ہو سکا۔",
 "route_error_unexpected":"آن لائن راستہ سازی میں غیر متوقع خرابی ہوئی۔",
 "route_error_http":"آن لائن راستہ سروس نے غلط جواب دیا ({code})۔",
 "route_error_timeout":"آن لائن راستے کے جواب کا وقت ختم ہو گیا۔ اپنا انٹرنیٹ کنکشن چیک کریں۔",
 "route_error_offline_map_missing":"راستہ سازی سے پہلے آف لائن ABM نقشہ نصب کریں۔",
 "route_error_offline_generic":"ABTINMAP آف لائن راستہ سازی میں خرابی: {error}",
 "route_error_offline_alternatives":"ABTINMAP آف لائن متبادل راستے بنانے میں ناکامی: {error}",
 "route_error_online_failed_generic":"آن لائن راستہ سازی ناکام ہوئی۔",
 "route_duration_minutes":"{value} منٹ","route_duration_hours_minutes":"{hours} گھنٹے {minutes} منٹ",
 "route_no_destination":"کوئی منزل منتخب نہیں",
 "route_open_map_destination":"منزل منتخب کرنے کے لیے نقشے کو دیر تک دبائیں۔",
 "route_destination_ready":"منزل نیویگیشن کے لیے تیار ہے",
 "route_location_unavailable":"موجودہ مقام دستیاب نہیں","route_location_ready":"موجودہ مقام تیار ہے",
 "route_check_gps":"مقام کی اجازت اور GPS چیک کریں۔",
 "route_accuracy":"مقام کی درستگی: {value} م",
 "route_select_destination":"منزل منتخب کریں","route_change_destination":"منزل تبدیل کریں",
 "route_suggested_routes":"تجویز کردہ راستے","route_calculation_failed":"راستے کا حساب ناکام: {error}",
 "route_download_offline_map":"آف لائن راستے کے لیے علاقے کا نقشہ ڈاؤن لوڈ کریں۔",
 "route_online_not_found_check_internet":"آن لائن راستہ نہیں ملا؛ اپنا انٹرنیٹ کنکشن چیک کریں۔",
 "route_set_location_destination_hint":"یہاں راستے کے اختیارات دیکھنے کے لیے مقام اور منزل مقرر کریں۔",
 "route_distance_km":"{value} کلومیٹر","route_distance_m":"{value} م","route_eta":"آمد","route_remaining":"باقی",
 "route_time":"وقت","route_preview_instruction":"دائیں مڑ کر ولیعصر گلی میں جائیں",
 "route_selected":"منتخب راستہ","route_numbered":"راستہ {value}",
 "alert_speed_camera":"اسپیڈ کیمرہ","alert_speed_bump":"اسپیڈ بریکر","alert_police":"ٹریفک پولیس",
 "alert_traffic_light":"ٹریفک لائٹ","abtin_maps_user":"Abtin Maps صارف","as_palette_title":"رنگ پیلیٹ",
 "as_display_mode_subtitle":"دن یا رات کا موڈ منتخب کریں",
 "as_weather_widget_subtitle":"نقشے پر موسم ویجٹ ڈسپلے کی ترتیبات",
}

T["vi"] = {
 "ai_dashcam_title":"Camera thông minh","ai_dashcam_desc":"Ghi hình video và trợ lý lái xe thông minh",
 "dashcam_video_size":"Kích thước video","dashcam_video_size_unlimited":"∞ phút",
 "dashcam_video_size_value":"{value} phút ({size} GB)","dashcam_driver_assistance":"Trợ lý lái xe thông minh",
 "dashcam_fixed_camera_height":"Chiều cao camera cố định","dashcam_camera_height":"Chiều cao camera",
 "dashcam_vehicle_width":"Chiều rộng xe","dashcam_camera_lateral_displacement":"Độ dịch chuyển ngang của camera",
 "dashcam_forward_collision":"Va chạm trực diện","dashcam_dangerous_headway":"Khoảng cách nguy hiểm với xe phía trước",
 "dashcam_stop_and_go":"Dừng và đi","dashcam_lane_departure_solid":"Lệch làn (vạch liền)",
 "dashcam_lane_departure_dashed":"Lệch làn (vạch đứt)","dashcam_traffic_sign_recognition":"Nhận diện biển báo giao thông",
 "hud_title":"Màn hình hiển thị trên kính (HUD)","hud_menu_desc":"Hiển thị thông tin lộ trình trên kính lái",
 "hud_enable":"Bật HUD","hud_enable_desc":"Hiển thị thông tin lộ trình trên kính lái",
 "hud_brightness":"Độ sáng màn hình","hud_mirror":"Hình ảnh phản chiếu","hud_mirror_desc":"Để hiển thị chính xác trên kính",
 "hud_scale":"Tỷ lệ hiển thị","hud_position":"Vị trí trên kính",
 "hud_position_desc":"Vị trí tổng thể của HUD trên kính lái","hud_visible_info":"Thông tin có thể hiển thị",
 "hud_info_speed":"Tốc độ","hud_info_speed_limit":"Giới hạn tốc độ","hud_info_maneuver":"Lộ trình và khúc cua tiếp theo",
 "hud_info_distance":"Khoảng cách đến khúc cua","hud_info_heading":"Hướng (la bàn)","hud_info_route_alerts":"Cảnh báo lộ trình",
 "hud_info_ai_alerts":"Cảnh báo AI","hud_info_other":"Thông tin khác","hud_preview":"Xem trước",
 "hud_note":"Lưu ý: để có tầm nhìn tốt nhất, hãy dùng HUD trong môi trường thiếu sáng.",
 "hud_launch":"Khởi chạy HUD","hud_no_active_navigation":"Bắt đầu dẫn đường để dùng HUD","hud_arrived":"Bạn đã đến nơi",
 "dashcam_level_off":"Tắt","dashcam_level_low":"Thấp","dashcam_level_normal":"Bình thường","dashcam_level_high":"Cao",
 "dashcam_meters_short":"m","delete_language_package_title":"Xóa gói ngôn ngữ",
 "delete_language_package_confirm":"Xóa gói \"{name}\"?","start_button":"Bắt đầu",
 "route_road_prefix":"đến {road}","route_maneuver_depart":"Bắt đầu lái xe{road}","route_maneuver_arrive":"Bạn đã đến nơi",
 "route_maneuver_turn_left":"Rẽ trái{road}","route_maneuver_turn_right":"Rẽ phải{road}",
 "route_maneuver_slight_left":"Rẽ trái nhẹ{road}","route_maneuver_slight_right":"Rẽ phải nhẹ{road}",
 "route_maneuver_sharp_left":"Rẽ trái gắt{road}","route_maneuver_sharp_right":"Rẽ phải gắt{road}",
 "route_maneuver_uturn":"Quay đầu xe{road}","route_maneuver_straight":"Đi thẳng{road}",
 "route_maneuver_continue":"Tiếp tục{road}","route_maneuver_roundabout":"Vào bùng binh{road}",
 "route_maneuver_roundabout_exit":"Ra khỏi bùng binh ở lối ra {exit}{road}",
 "route_maneuver_merge":"Nhập làn{road}","route_maneuver_on_ramp":"Vào đường dẫn lên{road}",
 "route_maneuver_off_ramp":"Ra đường dẫn xuống{road}",
 "route_error_no_route":"Không tìm thấy tuyến đường nào giữa điểm xuất phát và điểm đến.",
 "route_error_no_segment":"Điểm xuất phát hoặc điểm đến không gần mạng lưới đường có thể đi.",
 "route_error_too_big":"Yêu cầu tìm đường quá lớn.",
 "route_error_online_failed":"Dịch vụ tìm đường trực tuyến không thể tính toán tuyến đường.",
 "route_error_offline_unavailable":"Tìm đường trực tuyến không khả dụng ở chế độ ngoại tuyến.",
 "route_error_offline_not_found":"Không tìm thấy tuyến đường nào trên bản đồ ngoại tuyến.",
 "route_error_online_not_found":"Không tìm thấy tuyến đường nào giữa điểm xuất phát và điểm đến.",
 "route_error_invalid_coordinates":"Tọa độ điểm xuất phát hoặc điểm đến không hợp lệ.",
 "route_error_unreadable_response":"Không thể đọc phản hồi của dịch vụ tìm đường.",
 "route_error_invalid_geometry":"Hình học tuyến đường trực tuyến không đầy đủ hoặc không hợp lệ.",
 "route_error_invalid_response":"Phản hồi tìm đường trực tuyến có định dạng không hợp lệ.",
 "route_error_connection":"Không thể kết nối với dịch vụ tìm đường trực tuyến.",
 "route_error_unexpected":"Đã xảy ra lỗi không mong muốn khi tìm đường trực tuyến.",
 "route_error_http":"Dịch vụ tìm đường trực tuyến trả về phản hồi không hợp lệ ({code}).",
 "route_error_timeout":"Hết thời gian chờ phản hồi tìm đường trực tuyến. Kiểm tra kết nối internet.",
 "route_error_offline_map_missing":"Cài đặt bản đồ ABM ngoại tuyến trước khi tìm đường.",
 "route_error_offline_generic":"Lỗi tìm đường ngoại tuyến ABTINMAP: {error}",
 "route_error_offline_alternatives":"Không tạo được tuyến đường thay thế ngoại tuyến ABTINMAP: {error}",
 "route_error_online_failed_generic":"Tìm đường trực tuyến thất bại.",
 "route_duration_minutes":"{value} phút","route_duration_hours_minutes":"{hours} giờ {minutes} phút",
 "route_no_destination":"Chưa chọn điểm đến",
 "route_open_map_destination":"Nhấn giữ bản đồ để chọn điểm đến.",
 "route_destination_ready":"Điểm đến sẵn sàng để dẫn đường",
 "route_location_unavailable":"Vị trí hiện tại không khả dụng","route_location_ready":"Vị trí hiện tại đã sẵn sàng",
 "route_check_gps":"Kiểm tra quyền truy cập vị trí và GPS.",
 "route_accuracy":"Độ chính xác vị trí: {value} m",
 "route_select_destination":"Chọn điểm đến","route_change_destination":"Đổi điểm đến",
 "route_suggested_routes":"Tuyến đường đề xuất","route_calculation_failed":"Tính toán tuyến đường thất bại: {error}",
 "route_download_offline_map":"Tải bản đồ khu vực để tìm đường ngoại tuyến.",
 "route_online_not_found_check_internet":"Không tìm thấy tuyến đường trực tuyến; kiểm tra kết nối internet.",
 "route_set_location_destination_hint":"Đặt vị trí và điểm đến để xem các tùy chọn tuyến đường ở đây.",
 "route_distance_km":"{value} km","route_distance_m":"{value} m","route_eta":"Đến nơi","route_remaining":"Còn lại",
 "route_time":"Thời gian","route_preview_instruction":"Rẽ phải vào phố Valiasr",
 "route_selected":"Tuyến đường đã chọn","route_numbered":"Tuyến {value}",
 "alert_speed_camera":"Camera tốc độ","alert_speed_bump":"Gờ giảm tốc","alert_police":"Chốt cảnh sát giao thông",
 "alert_traffic_light":"Đèn giao thông","abtin_maps_user":"Người dùng Abtin Maps","as_palette_title":"Bảng màu",
 "as_display_mode_subtitle":"Chọn chế độ ngày hoặc đêm",
 "as_weather_widget_subtitle":"Cài đặt hiển thị tiện ích thời tiết trên bản đồ",
}

T["zh"] = {
 "ai_dashcam_title":"智能摄像头","ai_dashcam_desc":"视频录制和智能驾驶助手",
 "dashcam_video_size":"视频大小","dashcam_video_size_unlimited":"∞ 分钟",
 "dashcam_video_size_value":"{value} 分钟（{size} GB）","dashcam_driver_assistance":"智能驾驶助手",
 "dashcam_fixed_camera_height":"固定摄像头高度","dashcam_camera_height":"摄像头高度",
 "dashcam_vehicle_width":"车辆宽度","dashcam_camera_lateral_displacement":"摄像头横向偏移",
 "dashcam_forward_collision":"前方碰撞","dashcam_dangerous_headway":"与前车距离过近",
 "dashcam_stop_and_go":"走走停停","dashcam_lane_departure_solid":"偏离车道（实线）",
 "dashcam_lane_departure_dashed":"偏离车道（虚线）","dashcam_traffic_sign_recognition":"交通标志识别",
 "hud_title":"抬头显示（HUD）","hud_menu_desc":"在挡风玻璃上显示路线信息",
 "hud_enable":"启用 HUD","hud_enable_desc":"在挡风玻璃上显示路线信息",
 "hud_brightness":"显示亮度","hud_mirror":"镜像显示","hud_mirror_desc":"为了在玻璃上正确显示",
 "hud_scale":"显示比例","hud_position":"玻璃上的显示位置",
 "hud_position_desc":"HUD 在挡风玻璃上的整体位置","hud_visible_info":"可显示信息",
 "hud_info_speed":"速度","hud_info_speed_limit":"限速","hud_info_mananeuver":"路线和下一个转弯",
 "hud_info_distance":"到转弯的距离","hud_info_heading":"方向（指南针）","hud_info_route_alerts":"路线警报",
 "hud_info_ai_alerts":"AI 警报","hud_info_other":"其他信息","hud_preview":"预览",
 "hud_note":"注意：为获得最佳可见性，请在光线较暗的环境中使用 HUD。",
 "hud_launch":"启动 HUD","hud_no_active_navigation":"开始导航以使用 HUD","hud_arrived":"您已到达目的地",
 "dashcam_level_off":"关闭","dashcam_level_low":"低","dashcam_level_normal":"正常","dashcam_level_high":"高",
 "dashcam_meters_short":"米","delete_language_package_title":"删除语言包",
 " "delete_language_package_confirm":"删除“{{name}}”语言包？","start_button":"开始",
 "route_road_prefix":"前往 {road}","route_maneuver_depart":"开始行驶{road}","route_maneuver_arrive":"您已到达目的地",
 "route_maneuver_turn_left":"左转{road}","route_maneuver_turn_right":"右转{road}",
 "route_maneuver_slight_left":"稍向左转{road}","route_maneuver_slight_right":"稍向右转{road}",
 "route_maneuver_sharp_left":"急向左转{road}","route_maneuver_sharp_right":"急向右转{road}",
 "route_maneuver_uturn":"掉头{road}","route_maneuver_straight":"直行{road}",
 "route_maneueuver_continue":"继续{road}","route_maneuver_roundabout":"进入环岛{road}",
 "route_maneuver_roundabout_exit":"从环岛第 {exit} 个出口驶出{road}",
 "route_maneuver_merge":"汇入{road}","route_maneuver_on_ramp":"驶入匝道{{road}}",
 "route_maneuver__off_ramp":"驶出匝道{road}",
 "route_error_no_route":"未找到起点和目的地之间的路线。",
 "route_error_no_segment":"起点或目的地不在可行驶的道路网络附近。",
 "route_error_too_big":"路线请求过大。",
 "route_error_online_failed":"在线路线服务无法计算路线。",
 "route_error_offline_unavailable":"离线模式下无法使用在线路线。",
 "route_error_offline_not_found":"离线地图上未找到路线。",
 "route_error_online_not_found":"未找到起点和目的地之间的路线。",
 "route_error_invalid_coordinates":"起点或目的地的坐标无效。",
 "route_error_unreadable_response":"无法读取路线服务的响应。",
 "route_error_invalid_geometry":"在线路线的几何图形不完整或无效。",
 "route_error_invalid_response":"在线路线响应的格式无效。",
 "route_error_connection":"无法连接到在线路线服务。",
 "route_error_unexpected":"在线路线规划期间发生意外错误。",
 "route_error_http":"在线路线服务返回了无效响应（{{code}}）。",
 "route_error_timeout":"在线路线响应超时。请检查您的互联网连接。",
 "route_error_offline_map_missing":"请先安装离线 ABM 地图再进行路线规划。。",
 " "route_error_offline_generic":"ABTINMAP 离线路线规划错误：{error}",
 "route_error_offline_alternatives":"无法创建 ABTINMAP 离线备选路线：{error}",
 " "route_error_online_failed_generic":"在线路线规划失败。",
 "route_duration_minutes":"{value} 分钟","route_duration_hours_minutes":"{hours} 小时 {minutes} 分钟",
 "route_no_destination":"未选择目的地",
 "route_open_map_destination":"长按地图以选择目的地。",
 " "route_destination_ready":"目的地已准备好进行导航",
 "route_location_unavailable":"当前位置不可用","route_location_ready":"当前位置已就绪",
 " "route_check_gps":"检查定位权限和 GPS。",
 "route_accuracy":"定位精度：{value} 米",
 "route_select_destination":"选择目的地","route_change_destination":"更改目的地",
 "route_suggested_routes":"建议路线","route_calculation_failed":"路线计算失败：{error}",
 "route_download_offline_map":"下载区域地图以进行离线路线规划。",
 "route_online_not_found_check_internet":"未找到在线路线；请检查您的互联网连接。",
 "route_set_location_destination_hint":"设置位置和目的地后，此处将显示路线选项。",
 "route_distance_km":"{value} 公里","route_distance_m":"{value} 米","route_eta":"到达","route_remaining":"剩余",
 "route_time":"时间","route_preview_instruction":"右转进入瓦利亚斯尔街",
 "route_selected":"已选路线","route_numbered":"路线 {value}",
 "alert_speed_camera":"测速摄像头","alert_speed_bump":"减速带","alert_police":"交警检查点",
 "alert_traffic_light":"红绿灯","abtin_maps_user":"Abtin Maps 用户","as_palette_title":"调色板",
 "as_display_mode_subtitle":"选择日间或夜间模式",
 "as_weather_widget_subtitle":"地图上天气小组件的显示设置",
}
